Feat(crm): Add signup page when no user
marmelab/react-admin pull request #10017
Opened 2024-07-16 21:18 UTC by arimet

2024-07-17 07:45 UTC, djhi reviewed
You should probably have a custom route for the signup. Take a look at `ra-supabase`. It supports invites among other things, password resets, etc.

2024-07-19 06:50 UTC, jonathan-marmelab requested changes

2024-07-19 06:50 UTC, jonathan-marmelab commented on examples/crm/src/SignupPage.tsx
> +    // For the moment, we only allow one user to sign up. Other users must be created by the administrator.
Maybe you should also handle the `isPending` state here, to avoid showing the form if response takes ages to be retrieved ?

2024-07-19 06:50 UTC, jonathan-marmelab commented on examples/crm/src/dataProvider.ts
> +const dataProviderWithCustomMethode = {
```suggestion
const dataProviderWithCustomMethod = {
```

2024-07-19 06:50 UTC, jonathan-marmelab commented on examples/crm/src/dataProvider.ts
> +    dataProviderWithCustomMethode,
```suggestion
    dataProviderWithCustomMethod,
```

2024-07-19 07:42 UTC, merged