Fix(crm): improve technical code
marmelab/react-admin pull request #10041
Opened 2024-07-22 21:33 UTC by arimet

- Fix(crm): Replace Edit with EditBase for Task
- Fix(crm): Update dataProvider for contact lifecycle
- Fix(crm): Remove uncessary throw inside Deal Form
- Fix(crm): Set context_links for companies optionnal
- Fix(crm): Mock hash function for getContactAvatar

2024-07-22 21:51 UTC, arimet commented
Note: Ci is not on the latest Node LTS...

2024-07-23 08:52 UTC, jonathan-marmelab requested changes

2024-07-23 08:52 UTC, jonathan-marmelab commented on examples/crm/src/dataProvider.ts
> +async function beforeContactUpsert(
Can you add typings to this function as well ?

```ts
async function beforeContactUpsert(
    params: CreateParams<Contact> | UpdateParams<Contact>,
    dataProvider: DataProvider
): Promise<CreateParams<Contact> | UpdateParams<Contact>> {
```

2024-07-23 09:37 UTC, jonathan-marmelab approved these changes

2024-07-23 13:06 UTC, merged

2024-07-23 17:39 UTC, fzaninotto commented on examples/crm/src/dataProvider.ts
> +async function processContactAvatar(
The name is misleading, as the function does more than avatar (it also sets the company name). I'd split it in two.