Mention `CreateInDialog` in `ReferenceManyField` doc
marmelab/react-admin pull request #10054
Opened 2024-07-23 16:39 UTC by erwanMarmelab

## Problem

When rendering a list of related records in a ReferenceManyField, editing and creating a related element isn’t straightforward. One can use CreateButton, but the user experience is clunky.

## Solution

Add a “Adding a related record” section, showing the use of CreateInDialog button.

cf [https://react-admin.github.io/ra-enterprise/?path=/story/ra-form-layout-dialogform-createindialogbutton--in-reference-field](https://react-admin.github.io/ra-enterprise/?path=/story/ra-form-layout-dialogform-createindialogbutton--in-reference-field "smartCard-inline")

## Screenshot

![image](https://github.com/user-attachments/assets/87e5c535-cb1b-4356-8a7b-69e3f07f7d2a)

2024-07-23 16:41 UTC, erwanMarmelab commented on docs/ReferenceManyField.md
Do we want an other section with an example of `<EditInDialogButton>` too ?

2024-07-25 15:03 UTC, djhi approved these changes

2024-07-25 15:05 UTC, djhi requested changes

2024-07-25 15:05 UTC, djhi commented on docs/ReferenceManyField.md
> +                          record={{ employer_id: record.id }}
I think you're missing a `WithRecord` here

2024-07-26 09:12 UTC, djhi approved these changes

2024-07-26 09:12 UTC, merged