Feat(demo): Backport Atomic CRM to RA repo
marmelab/react-admin pull request #10140
Opened 2024-08-14 07:48 UTC by jonathan-marmelab

## Problem

CRM demo is behind Atomic CRM 

## Solution

Backpôrt Atomic CRM changes to RA repository

## How To Test

Run the CRM demo

## Additional Checks

- [X] The PR targets `master` for a bugfix, or `next` for a feature
- [X] The PR includes **unit tests** (if not possible, describe why)
- [ ] ~~The PR includes one or several **stories** (if not possible, describe why)~~ *(N/A)*
- [X] The **documentation** is up to date

Also, please make sure to read the [contributing guidelines](https://github.com/marmelab/react-admin#contributing).

2024-08-14 11:57 UTC, slax57 requested changes
Code looks good! That's an incredible work, well done!

Now, I still found a couple issues while testing:

1. The top bar logo is missing
2. The 'Demo' panel is missing (probably missing an env var)
3. After importing contacts, when browsing to the Dashboard, the 'Last activity' panel is in error, and I see errors in the console `TypeError: a.date.localeCompare is not a function`
4. **nitpick:** In 'My info', clicking on 'Change password' shows a notification telling me an email has been sent, although no email is sent and it actually updates the password right away
5. **nitpick:** After updating the Avatar of Jane Doe, if I login with a wrong username, I'm still logged in as Jane Doe (which is expected), but the Avatar is reset, only in the top bar (I still see the new Avatar in the 'My info' view)

Other than that it seems to work great. Again, well done! :muscle:

2024-08-20 08:43 UTC, fzaninotto requested changes

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/contacts/ContactList.tsx
> -            filterDefaultValues={{ sales_id: identity?.id }}
again, I'm surprised this was removed

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/contacts/ContactList.tsx
> -    const hasOtherFiltersThanDefaultBoolean = hasOtherFiltersThanDefault(
this should have been kept

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/contacts/ContactList.tsx
> -    const tags = await fetchRelatedRecords<Tag>(records, 'tags', 'tags');
I'm surprised by this change: `fetchRelatedRecords` does a `getMany` and should work. Why replace it with a manual `getList`?

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/contacts/ContactList.tsx
> +export const getRelatedIds = (
this one is copied from ra-core

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/contacts/ContactListFilter.tsx
> +            <FilterList
should stay at the bottom

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/dashboard/Dashboard.tsx
> -                    <Welcome />
This one should be reverted

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/dashboard/TasksListEmpty.tsx
> +    return <Typography variant="body2">No results found</Typography>;
deserves better wording

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/deals/DealList.tsx
> -            filterDefaultValues={{
should be kept

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/deals/DealList.tsx
> -    const hasOtherFiltersThanDefaultBoolean = hasOtherFiltersThanDefault(
shouyld be kept

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/notes/utils.ts
> -    now.setSeconds(0);
I won der why this was removed

2024-08-20 08:43 UTC, fzaninotto commented on examples/crm/src/root/defaultConfiguration.ts
> +export const defaultLogo = './logos/logo_atomic_crm.svg';
the file seems missing, the logo isn't displayed in the header

2024-08-20 09:08 UTC, fzaninotto commented on examples/crm/src/companies/CompanyList.tsx
> +        <ListBase perPage={25} sort={{ field: 'name', order: 'ASC' }}>
understood: this is a tradeoff to avoid displaying the empty screen to the second user. Let's live with it as the "my" filter is one click away.

2024-08-20 15:11 UTC, fzaninotto commented on examples/crm/src/contacts/ContactList.tsx
> -    const tags = await fetchRelatedRecords<Tag>(records, 'tags', 'tags');
This is caused by a bug in ra-data-postgrest's `getMany` implementation. When called with an empty array, it generates an incorrect URL (`http://127.0.0.1:54321/rest/v1/tags?id=eq.`) and Postgrest returns a 400 bad request. Until this is fixed we'll have to live with this code.

2024-08-20 16:42 UTC, fzaninotto approved these changes
All problems fixed, except the two nitpicks mentioned by @slax57. I think we're good to go.

2024-08-21 07:42 UTC, merged