[Doc] Create a doc page for `<DateRangeInput>`
marmelab/react-admin pull request #10202
Opened 2024-09-13 06:55 UTC by erwanMarmelab

## Problem

React-admin's enterprise creates a new `<DateRangeInput>` component and document it.

## Solution

Update OSS documentation

2024-09-13 07:18 UTC, djhi requested changes

2024-09-13 07:18 UTC, djhi commented on docs/DateInput.md
> +import { fr } from 'date-fns/locale/fr'
```suggestion
import { fr } from 'date-fns/locale/fr';
```

2024-09-13 07:18 UTC, djhi commented on docs/DateTimeInput.md
> +import { fr } from 'date-fns/locale/fr'
```suggestion
import { fr } from 'date-fns/locale/fr';
```

2024-09-16 13:28 UTC, fzaninotto approved these changes

2024-09-16 13:31 UTC, merged