[Doc] Update `<Filterbutton>`'s screencast
marmelab/react-admin pull request #10213
Opened 2024-09-17 12:37 UTC by erwanMarmelab

## Problem

`<Filterbutton>`'s doc was updated but the screencast was not.

## Solution

- [x] Record and update screencast
- [x] Remove `webm` and `gif` files
- [x] Update imports

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature
- [x] The **documentation** is up to date

2024-09-18 07:03 UTC, fzaninotto requested changes

2024-09-18 07:03 UTC, fzaninotto commented on docs/img/list_filter.mp4
Something is wrong with this video. It's excrutiatingly slow. Also, the example doesn't make sense. A filter "bar" on the "nested" field?? I suggest you follow the exact same scenario as the original.

2024-09-20 08:33 UTC, djhi approved these changes
The video looks good now

2024-10-01 09:50 UTC, fzaninotto approved these changes

2024-10-01 09:51 UTC, merged