Fix double decoding of ids in URLs
marmelab/react-admin pull request #10293
Opened 2024-10-22 12:07 UTC by djhi

## Problem

Fixes #10158. React-router fixed an issue where params weren't properly decoded. However, react-admin still tried to decode them, leading to invalid ids.

## Solution

Remove the decoding from `useEditController` and `useShowController`

## How To Test

There are new stories and tests

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature
- [x] The PR includes **unit tests** (if not possible, describe why)
- [x] The PR includes one or several **stories** (if not possible, describe why)
- [x] The **documentation** is up to date

2024-10-23 15:06 UTC, slax57 requested changes
other than that it looks good!

2024-10-23 15:06 UTC, slax57 commented on packages/ra-core/src/controller/show/useShowController.stories.tsx
> +export const EncodedIdWithPercentage = ({
same

2024-10-23 15:10 UTC, djhi commented on packages/ra-core/src/controller/edit/useEditController.stories.tsx
> +};
Yes, because we had the issue with one but not the other

2024-10-23 15:11 UTC, slax57 commented on packages/ra-core/src/controller/edit/useEditController.stories.tsx
> +};
Ok, but why not factorize the code then?

2024-10-24 08:11 UTC, slax57 approved these changes

2024-10-24 08:12 UTC, merged