Fix `<SimpleList linkType={false}>` UI
marmelab/react-admin pull request #10343
Opened 2024-11-12 16:42 UTC by erwanMarmelab

## Problem

`linkType` should only remove the onClick action but it breaks the UI.

### Without `linkType`
![image](https://github.com/user-attachments/assets/d4f99e0e-7563-4716-83bb-03856857d17e)
### With `linkType={false}`
![image](https://github.com/user-attachments/assets/b6074acc-34f4-43c9-a9f5-0a678722123b)

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature
- [x] The PR includes one or several **stories** (if not possible, describe why)

2024-11-13 07:59 UTC, fzaninotto requested changes

2024-11-13 07:59 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/SimpleList/SimpleList.stories.tsx
> +export const AnyLink = () => (
```suggestion
export const LinkTypeFalse = () => (
```

2024-11-13 07:59 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
> +                    paddingY: 1,
use `px`, `py` and `m` instead

2024-11-13 07:59 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/SimpleList/SimpleList.tsx
> +            sx={{ ...sx }}
Why do you clone the object? Just pass it normally.

2024-11-14 16:16 UTC, djhi approved these changes

2024-11-14 16:16 UTC, merged