Add TextArrayInput to edit arrays of strings
marmelab/react-admin pull request #10384
Opened 2024-11-26 14:41 UTC by fzaninotto

## Problem

Our various array input components don't support the simple case of editing an array of strings with no choices. 

## Solution

2 possibilities:

1. Tweak the `AutocompleteArrayInput` to support simple addition with `freeSolo`. This is not possible because this input heavily relies on suggestions, and can't take a value outside of its choices. Even the `onCreate` support uses a special choice. 
2. Implement a new, simpler  component based on MUI's `<Autocomplete>` component. 

I tried 1. but failed, so I went for 2.

## DX

```jsx
import { Create, SimpleForm, TextArrayInput, TextInput } from 'react-admin';

export const EmailCreate = () => (
    <Create>
        <SimpleForm>
            <TextArrayInput source="to" />
            <TextInput source="subject" />
            <TextInput source="body" multiline minRows={5} />
        </SimpleForm>
    </Create>
);
```

https://github.com/user-attachments/assets/2f8b28bb-7f5c-4bdc-908f-eecb10ebadfe

## How To Test

Launch the storybook and check out the `ra-ui-materialui/inputs/TextArrayInput stories` at http://localhost:9010/?path=/story/ra-ui-materialui-input-textarrayinput--basic. 

## To Do

- [x] Add component
- [x] Add stories
- [x] Add tests
- [x] Add Documentation
- [x] Reference it in other doc pages to make it discoverable

2024-12-03 15:40 UTC, slax57 requested changes

2024-12-05 09:23 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/TextArrayInput.tsx
> +            {...props}
TypeScript says no

2024-12-05 09:23 UTC, fzaninotto commented
Review applied

2024-12-05 13:46 UTC, slax57 commented on examples/simple/src/data.tsx
> +            id: '1 1',
looks like you committed a change from a test unrelated to this PR

2024-12-05 13:46 UTC, slax57 commented on examples/simple/src/data.tsx
> +            id: '1 1',
```suggestion
            id: 1,
```

2024-12-05 13:57 UTC, merged