chore: add storeKey to arrayfield to handle resources with same ids
marmelab/react-admin pull request #10390
Opened 2024-12-01 22:33 UTC by Aijeyomah

## Problem
#10382
_Describe the problem this PR solves_

## Solution
Add support for the same storeKey to the <ArrayField>

_Describe the solution this PR implements_

## How To Test

_Describe the steps required to test the changes_

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature
- [ ] The PR includes **unit tests** (if not possible, describe why)
- [x] The PR includes one or several **stories** (if not possible, describe why)
- [x] The **documentation** is up to date

Also, please make sure to read the [contributing guidelines](https://github.com/marmelab/react-admin#contributing).

2024-12-04 00:56 UTC, Aijeyomah commented
@fzaninotto Can you review? thnaks

2024-12-04 08:15 UTC, djhi commented
Thanks for the PR! As this is a new feature, can you target the `next` branch? Besides, in order to test it, we'll need stories and unit tests. Can you add some, taking inspiration from the `ListBase` component?

2024-12-04 09:43 UTC, Aijeyomah commented
> Thanks for the PR! As this is a new feature, can you target the `next` branch? Besides, in order to test it, we'll need stories and unit tests. Can you add some, taking inspiration from the `ListBase` component?

Yes, I can. Thanks

2025-01-02 13:36 UTC, Aijeyomah commented
> Thanks for the PR! As this is a new feature, can you target the `next` branch? Besides, in order to test it, we'll need stories and unit tests. Can you add some, taking inspiration from the `ListBase` component?

@djhi @fzaninotto I have updated the target branch as well as written the necessary stories and tests for the feature. Please re-review. Thanks

2025-01-07 16:45 UTC, slax57 requested changes
Too bad you took a wrong direction with the fix, but we appreciate the effort to provide good stories, tests, and documentation! Thanks!

2025-01-07 16:45 UTC, slax57 commented on packages/ra-core/src/controller/list/useList.ts
> +
I'm afraid you are going in the wrong direction here :grimacing:  . The fix for #10382 suggested by @fzaninotto was to allow to override the `storeKey` used to store the **selection state** (i.e. used in `useRecordSelection`), but not the **pagination** state.

You can have a look at what was done in `useReferenceManyFieldController` for an example:

https://github.com/marmelab/react-admin/blob/7b319c451d448fe9db00b76fa7ddcc10d4d6dedd/packages/ra-core/src/controller/field/useReferenceManyFieldController.ts#L90-L92

2025-01-07 16:45 UTC, slax57 commented on packages/ra-core/src/controller/list/useList.storeKey.stories.tsx
> +);
This Story is a bit misleading, `StorePosts` is still using a `storeKey`.

Besides, `storeKey={false}` is not the same as having no `storeKey` (for `NoStorePosts` ). I'd expect both lists in `ListsWithoutStoreKeys` to have no `storeKey`.

2025-01-07 16:45 UTC, slax57 commented on packages/ra-core/src/controller/list/useList.storeKey.stories.tsx
> +);
`Layout` should not be shared across stories since both stories do not implement the same routes

2025-01-07 16:45 UTC, slax57 commented on docs/ArrayField.md
> +In the example below, two `ArrayField` components display the same data source (`books`), but each stores its selection state under a different key (`books.selectedIds` and `custom.selectedIds`). Thi
```suggestion
In the example below, two `ArrayField` components display the same data source (`books`), but each stores its selection state under a different key (`customOne.selectedIds` and `customTwo.selectedIds`). This ensures that both components can coexist on the same page without interfering with each other's state.
```

2025-03-17 00:17 UTC, Aijeyomah commented
@slax57 Can you re-review? Thanks.

2025-03-17 08:58 UTC, fzaninotto requested changes

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.spec.tsx
> +            message.includes('React will try recreating this component tree')
This isn't a normal error message - it probably comes from your story, your test, or your implementation.

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.spec.tsx
> +beforeAll(() => {
IMHO, this is a footgun as it will hide potentially important errors. I'd prefer that you do the mock in individual tests and only when necessary

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.stories.tsx
> +                                    isRowSelectable={() => true}
Rows are selectable by default, you shouldn't need this line. Same for the second ArrayInput.

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.spec.tsx
> +        expect(checkboxes.length).toBeGreaterThan(3);
By reading the test, I don't know why you wait for that. If you want to wait for the two lists to render, please use a `findByText` looking for the actual array values instead.

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.spec.tsx
> +        fireEvent.click(checkboxes[1]);
Since you enabled rowClick, I suggest you trigger a click on a piece of text instead. This would make the test much more readable as it's not obvious what `checkboxes[1]` is.

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.spec.tsx
> +        render(<TwoArrayFieldsSelection />);
You shouldn't need to rerender. If you want to come back to the initial state, use more than one `it()` and group them in a `describe()`.

2025-03-17 08:58 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ArrayField.tsx
> +        resource: storeKey || resource, // Prioritize storeKey if provided
I'd prefer that you add support for a custom `storeKey` in `useList`. I know that we currently use `resource` only for selection in `useList`, but this may change in the future.

2026-06-22 08:56 UTC, closed without merging