Allow record override from location everywhere
marmelab/react-admin pull request #10412
Opened 2024-12-12 12:55 UTC by djhi

## Problem

There's no way to redirect to an Edit form with modifications. This makes it cumbersome to prefill an EditForm (see e.g. ra-history Revert button).

## Solution

We already have a mechanism to prefill a form from the location state or search query in `useCreateController` that we leverage for cloning.

- [x] Extract this mechanism into a hook
- [x] Refactor it to merge the location data into a provided record
- [x] Use the hook in `useAugmentedForm`
- [x] Test edition with this mechanism
- [x] Document the `useRecordFromLocation` hook

## How To Test

- https://react-admin-storybook-git-allow-record-override-76c9cb-marmelab.vercel.app/?path=%2Fstory%2Fra-core-form-form--multi-routes-form

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature
- [x] The PR includes **unit tests** (if not possible, describe why)
- [x] The PR includes one or several **stories** (if not possible, describe why)
- [x] The **documentation** is up to date

Also, please make sure to read the [contributing guidelines](https://github.com/marmelab/react-admin#contributing).

2024-12-16 11:03 UTC, djhi commented on packages/ra-core/src/controller/edit/useEditController.stories.tsx
> +export const OverrideRecordWithLocation = ({
Not sure I should keep this one. Wdyt?

2024-12-16 11:03 UTC, djhi commented on packages/ra-core/src/core/SourceContext.stories.tsx
> +        <TestMemoryRouter>
This is required now as we read the location in `useAugmentedForm`

2024-12-17 12:24 UTC, slax57 requested changes

2024-12-17 12:24 UTC, slax57 commented on packages/ra-core/src/form/useAugmentedForm.ts
> +            reset(merge({}, record, recordFromLocation), {
You should probably merge `recordFromLocation` with `defaultValuesIncludingRecord` instead of `record`, otherwise the `defaultValues` are discarded.

2024-12-17 12:24 UTC, slax57 commented on packages/ra-core/src/form/useRecordFromLocation.spec.tsx
> +    });
duplicate test

2024-12-17 12:24 UTC, slax57 commented on packages/ra-core/src/form/useRecordFromLocation.ts
> +    const finalRecordRef = useRef(recordFromLocation);
Suggestion: rename `finalRecordRef` to `previousRecordRef`

2024-12-17 12:24 UTC, slax57 commented on packages/ra-core/src/form/Form.stories.tsx
> +            <SubmitButton />
To mimic the true `<SaveButton>`, `<SubmitButton />` should use `dirtyFields` instead of `isDirty`, which may be different as we know.

2024-12-18 09:40 UTC, slax57 approved these changes

2024-12-18 09:40 UTC, merged