Support function for initialValues
marmelab/react-admin pull request #5222
Opened 2020-09-02 06:37 UTC by djhi

Fixes #5221

2020-09-02 06:54 UTC, fzaninotto requested changes

2020-09-02 06:54 UTC, fzaninotto commented on packages/ra-core/src/form/getFormInitialValues.ts
> +        return values();
not good, we were passing the record as parameter in the previous version.

2020-09-02 06:54 UTC, fzaninotto commented on packages/ra-core/src/form/getFormInitialValues.ts
> +        ...getValues(defaultValue),
`getValues` should take the `record` as parameter.

2020-09-04 07:22 UTC, fzaninotto approved these changes

2020-09-07 10:13 UTC, djhi commented on packages/ra-core/src/form/getFormInitialValues.ts
> +        ...record,
We should probably check whether `initialValues` or `defaultValue` are functions before overriding them with the record as we pass it to them as an argument. What do you think @fzaninotto ?

2020-09-07 11:42 UTC, fzaninotto approved these changes

2020-09-07 11:42 UTC, merged