Ability to disable notification in useCheckAuth and useLogoutIfAccessDenied hooks
marmelab/react-admin pull request #5255
Opened 2020-09-15 02:59 UTC by WiXSL

Implements #5178

2020-09-15 07:12 UTC, djhi approved these changes
:+1:

2020-09-15 07:14 UTC, Luwangel reviewed
Great job, thanks! I think it's a good opportunity to write tests for these two hooks. Do you have time to write them?

2020-09-15 17:01 UTC, WiXSL commented
@Luwangel I don't have time right now, sorry.

2020-09-16 05:16 UTC, WiXSL commented
Done!

2020-09-16 05:39 UTC, djhi requested changes
Nice!

2020-09-16 05:39 UTC, djhi commented on packages/ra-core/src/auth/useCheckAuth.spec.tsx
> +    it('should logout whitout showing a notification', async () => {
```suggestion
    it('should logout whitout showing a notification when disableNotification is true', async () => {
```

2020-09-16 12:17 UTC, Luwangel approved these changes
Thanks :)

2020-09-18 13:54 UTC, djhi approved these changes

2020-09-18 13:55 UTC, merged