Add onSuccess Callback Infos about undoable prop
marmelab/react-admin pull request #5260
Opened 2020-09-16 09:24 UTC by jdemangeon

2020-09-16 09:49 UTC, djhi requested changes

2020-09-16 09:49 UTC, djhi commented on docs/CreateEdit.md
> +Per default, when saving is executed with optimistic rendering, the `onSuccess` callback is directly called. To change it, you need to pass `undoable={false}` to your `<Edit />` or `<Create />` compo
```suggestion
Bydefault, when saving with optimistic rendering, the `onSuccess` callback is called immediatly. To change that, you need to pass `undoable={false}` to your `<Edit />` or `<Create />` component. The `onSuccess` callback will be then called at the end of the dataProvider call.
```

2020-09-16 09:49 UTC, djhi commented on docs/CreateEdit.md
> +In addition, saved object will not be available as an argument to the `onSuccess` callback method when `undoable` feature is enabled.
```suggestion
In addition, the saved object will not be available as an argument of the `onSuccess` callback method when `undoable` feature is enabled.
```

2020-09-16 14:59 UTC, jdemangeon commented
@djhi review applied :+1:

2020-09-16 15:03 UTC, djhi requested changes

2020-09-16 15:03 UTC, djhi commented on docs/CreateEdit.md
> +By default, when saving with optimistic rendering, the `onSuccess` callback is called immediately. To change that, you need to pass `undoable={false}` to your `<Edit />` or `<Create />` component. Th
```suggestion
By default, when saving with optimistic rendering, the `onSuccess` callback is called immediately. To change that, you need to pass `undoable={false}` to your `<Edit />` or `<Create />` component. The `onSuccess` callback will then be called at the end of the dataProvider call.
```

2020-09-16 15:03 UTC, djhi commented on docs/CreateEdit.md
> +By default, when saving with optimistic rendering, the `onSuccess` callback is called immediately. To change that, you need to pass `undoable={false}` to your `<Edit />` or `<Create />` component. Th
Sorry...

2020-09-17 07:08 UTC, jdemangeon commented
Review applied again

2020-09-17 07:15 UTC, djhi approved these changes

2020-09-18 08:19 UTC, merged