More TS fixes
marmelab/react-admin pull request #5298
Opened 2020-09-24 15:43 UTC by djhi

2020-09-24 15:52 UTC, fzaninotto approved these changes

2020-09-25 07:48 UTC, ThieryMichel approved these changes

2020-09-25 13:32 UTC, fzaninotto commented on packages/ra-data-fakerest/package.json
> +        "ra-core": "^3.9.0-beta.1"
we will need to pass over all these before the stable release

2020-09-25 13:35 UTC, fzaninotto requested changes

2020-09-25 13:35 UTC, fzaninotto commented on yarn.lock
> +react-admin@next:
Not good: this is coming from npm, not the monorepo

2020-09-25 16:35 UTC, fzaninotto requested changes

2020-09-25 16:35 UTC, fzaninotto commented on yarn.lock
> +data-generator-retail@^3.0.0:
you probably missed this one in examples/demo/package.json

2020-09-26 16:34 UTC, fzaninotto approved these changes

2020-09-26 16:34 UTC, merged