Remove unused components css rules
marmelab/react-admin pull request #5345
Opened 2020-10-03 21:34 UTC by WiXSL

2020-10-05 09:26 UTC, fzaninotto requested changes
Good cleanup!

2020-10-05 09:26 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/CheckboxGroupInput.tsx
> -        root: {},
For this one, we should use it in the JSX root element instead of removing it.

2020-10-05 12:19 UTC, djhi approved these changes

2020-10-08 14:33 UTC, fzaninotto approved these changes

2020-10-08 14:34 UTC, merged

2020-10-08 14:34 UTC, fzaninotto commented
Thanks!