Fix usePermissions always triggers e re-render even though the permissions are unchanged
marmelab/react-admin pull request #5607
Opened 2020-11-30 17:24 UTC by fzaninotto

## Problem

All react-admin routes (list, edit, create, etc) are wrapped by `WithPermissions`. This component renders the page content optimistically with empty permissions, then calls `authProvider.getPermissions()`, and passes the result to the child.

In many cases, this means the routes will render twice: once with empty permissions, and once with the permissions returned by the `authProvider`. 

## Solution

`WithPermissions` calls `authProvider.getPermissions()` with empty params. In many cases, the result of this call is always the same.

`useGetPermissions` can cache the result from the first call, and initialize its state with it. 

that way, in most cases, the return from  `authProvider.getPermissions()` will be the same as the cached one, and we'll save a re-render.

This should git a short perf boost to all apps, whether they use permissions or not.

## Before

12 renders when coming back to the Post List page

![image](https://user-images.githubusercontent.com/99944/100642575-3927e380-3339-11eb-80aa-f64aab480a60.png)

## After

11 renders when coming back to the Post List page

![image](https://user-images.githubusercontent.com/99944/100642496-21505f80-3339-11eb-8f03-60ff7b912e62.png)

2020-11-30 18:04 UTC, fzaninotto commented
That won't work because even though the `permissions` don't change, `usePermissions` changes the loading state once `auth.getPermissions()` returns, and that triggers a rerender. 

This is unfortunate here as we don't use the loading state.

this means we must introduce a new hook that only stores the permissions, but not the loading state.

2020-12-01 08:26 UTC, djhi approved these changes
I can't figure a better name but I'm not convinced by `usePermissionsOptimized`. I think most people will end up using it just because of the name

2020-12-01 08:54 UTC, djhi requested changes
Oh and you forgot to document it ;)

2020-12-01 08:56 UTC, fzaninotto commented
It's an internal API. I'm not even sure we should export it.

2020-12-01 09:00 UTC, merged