Fix TabbedForm Does not Display Errors in Hidden Tabs on Submit
marmelab/react-admin pull request #5903
Opened 2021-02-12 16:27 UTC by djhi

2021-02-12 17:07 UTC, fzaninotto requested changes

2021-02-12 17:07 UTC, fzaninotto commented on packages/ra-ui-materialui/src/form/FormTabHeader.tsx
> +import * as React from 'react';
please export that component

2021-02-12 17:07 UTC, fzaninotto commented on packages/ra-ui-materialui/src/form/FormTabHeader.tsx
> +    form.subscribe(
You must do that in a useEffect, and return the unsubscribe method

2021-02-15 10:05 UTC, djhi commented on packages/ra-ui-materialui/src/form/FormTabHeader.tsx
> +import * as React from 'react';
Done

2021-02-15 11:50 UTC, fzaninotto approved these changes

2021-02-15 11:50 UTC, merged