Added BulkUpdateButton component
marmelab/react-admin pull request #6072
Opened 2021-03-20 19:47 UTC by WiXSL

Implements #4474

2021-03-29 07:22 UTC, djhi requested changes
Nice!

2021-03-29 07:22 UTC, djhi commented on packages/ra-language-french/src/index.ts
> +                'Êtes-vous sûr(e) de vouloir à jour cet élément ? |||| Êtes-vous sûr(e) de vouloir à jour ces %{smart_count} éléments ?',
```suggestion
                'Êtes-vous sûr(e) de vouloir modifier cet élément ? |||| Êtes-vous sûr(e) de vouloir modifier ces %{smart_count} éléments ?',
```

2021-03-29 07:22 UTC, djhi commented on packages/ra-ui-materialui/src/button/BulkUpdateButton.tsx
> +};
I think we're missing the `data` prop here

2021-03-29 07:22 UTC, djhi commented on packages/ra-ui-materialui/src/button/BulkUpdateButton.tsx
> +};
Besides, we should also support custom `onSuccess` and `onFailure` prop as functions to customize side effects

2021-03-29 07:22 UTC, djhi commented on packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
> +            },
We should also support custom `onSuccess` and `onFailure` prop as functions to customize side effects

2021-03-29 07:22 UTC, djhi commented on packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx
> +            onSuccess: () => {
We should also support custom `onSuccess` and `onFailure` prop as functions to customize side effects

2021-04-13 21:14 UTC, fzaninotto commented
Your PR needs a rebase

2021-04-13 21:20 UTC, fzaninotto requested changes

2021-04-13 21:20 UTC, fzaninotto commented on packages/ra-ui-materialui/src/button/BulkUpdateButton.tsx
> +    undoable ? (
we're deprecating `undoable` in favor of `mutationMode` (see e.g. `DeleteButton`). Could you use `mutationMode` directly here?

2021-04-13 21:20 UTC, fzaninotto commented on docs/List.md
> -const ResetViewsButton = ({ selectedIds }) => {
The new button is great, but the documentation also served as an example to write a custom BulkActionButton. Could you find a way to keep that?

2021-05-01 20:40 UTC, fzaninotto requested changes

2021-05-01 20:40 UTC, fzaninotto commented on packages/ra-ui-materialui/src/button/BulkUpdateWithConfirmButton.tsx
> +            refresh();
You're using refresh() before it's defined, same for other side effects. This may be valid but it's disturbing for the reader.

2021-05-01 20:40 UTC, fzaninotto commented on packages/ra-language-french/src/index.ts
> +            update: 'À jour',
```suggestion
            update: 'Modifier',
```

2021-05-01 20:40 UTC, fzaninotto commented on packages/ra-language-french/src/index.ts
> +                'À jour %{name} |||| À jour %{smart_count} %{name}',
```suggestion
                'Modifier %{name} |||| Modifier %{smart_count} %{name}',
```

2021-05-31 16:08 UTC, WiXSL commented
Is this ok to be merge?

2021-05-31 21:35 UTC, fzaninotto approved these changes

2021-05-31 21:35 UTC, merged

2021-05-31 21:35 UTC, fzaninotto commented
Thanks!

2021-08-13 08:47 UTC, mjomble commented
@WiXSL I'm getting errors that seem to be caused by this change:

```
Material-UI: The `fade` color utility was renamed to `alpha` to better describe its functionality.

You should use `import { alpha } from '@material-ui/core/styles'`
```

2021-08-13 08:51 UTC, fzaninotto commented
@mjomble That's a deprecation warning due to the latest material-ui minor update. It's already tracked by #6490.