restore deprecated undoable prop original behavior
marmelab/react-admin pull request #6153
Opened 2021-04-12 10:23 UTC by ThieryMichel

For retrocompatibility undoable=false should be on pessimistic mode, currently it is on undoable mode.

2021-04-12 10:27 UTC, djhi requested changes

2021-04-12 10:27 UTC, djhi commented on packages/ra-ui-materialui/src/button/DeleteButton.tsx
> +const useMutationMode = (mutationMode, undoable) => {
Can you extract this in a dedicated file ?

2021-04-13 21:07 UTC, fzaninotto requested changes

2021-04-13 21:07 UTC, fzaninotto commented on packages/ra-ui-materialui/src/button/DeleteButton.tsx
> +    useEffect(() => {
I'm -1 with this useEffect and the related warnings. A simple function, rather than a hook, will be enough.

2021-04-29 21:48 UTC, fzaninotto commented
bump, could you please apply the review?

2021-04-30 08:08 UTC, djhi reviewed
There is a linter warning about performances

2021-05-01 20:32 UTC, fzaninotto approved these changes

2021-05-01 20:32 UTC, merged