Add hideOnScroll prop to AppBar
marmelab/react-admin pull request #6178
Opened 2021-04-16 15:03 UTC by WiXSL

Implements #6174

2021-04-19 08:10 UTC, djhi requested changes
As we want to keep the default behavior, I think having to pass `false` explicitly is not very intuitive. What do you think about adding a `stickOnScroll` prop which would be `false` by default? Maybe there is a better name for it though ;)

2021-04-19 08:15 UTC, fzaninotto commented
Why don't you call this prop `container` and let users pass a Fragment instead of HideOnScroll?

2021-04-20 08:17 UTC, djhi requested changes
:joy: :tada:

2021-04-20 08:17 UTC, djhi commented on docs/Theming.md
> +    <AppBar {...props} conatainer={Fragment} />
```suggestion
    <AppBar {...props} container={Fragment} />
```

Achievement unlocked: Corrected El Corrector!

2021-04-20 12:43 UTC, djhi approved these changes

2021-04-20 16:05 UTC, fzaninotto approved these changes

2021-04-20 16:05 UTC, merged

2021-04-20 16:05 UTC, fzaninotto commented
thanks!