Add children to ListActions component
marmelab/react-admin pull request #6218
Opened 2021-04-27 21:25 UTC by WiXSL

Implements #6212

2021-04-28 07:03 UTC, djhi commented
:+1:  Maybe we should do the same for the other action components as well.

2021-04-29 17:14 UTC, fzaninotto reviewed
Thanks for your patch. However, I'm not comfortable with this change, and for 2 reasons:

- it creates 2 ways to do one simple thing. This is confusing, which way should a developer use and why? 
- your API "hides" that some other buttons are included. I think that will lead to WTF moments for developers. 

Overall, I don't think we should implement that.

2021-04-29 21:52 UTC, WiXSL commented
Ok, how about move the logic of the actions to hooks and you always override the actions prop like now, but having control of default actions by calling this hooks (or not).

Example: 

```jsx
import Button from '@material-ui/core/Button';
import { TopToolbar, Edit, useEditDefaultActions } from 'react-admin';

const PostEditActions = (props) => {
     const DefaultActions = useEditDefaultActions(props);

    return <TopToolbar>
        <DefaultActions/> 
        {/* Add your custom actions */}
        <Button 
            color="primary"
            onClick={() => { alert('Your custom action'); }}
        >
            Custom Action
        </Button>
    </TopToolbar>;
};

export const PostEdit = (props) => (
    <Edit actions={<PostEditActions />} {...props}>
        ...
    </Edit>
);
```

2021-05-17 12:51 UTC, WiXSL commented
@fzaninotto,
What do you think of this idea?

2021-05-17 13:04 UTC, djhi commented
Why a hook here? We could just have a component rendering a fragment with the default actions right?

2021-05-17 13:05 UTC, WiXSL commented
You are right.

2021-05-31 21:17 UTC, fzaninotto commented
When I think about it, only the `<ListActions>` are hard to override. Maybe this is where we should do the change. 

First, the documentation could be simplified since we now use the various context:

```diff
const ListActions = (props) => {
    const {
        className,
-       exporter,
-       filters,
-       maxResults,
        ...rest
    } = props;
    const {
-       currentSort,
-       resource,
-       displayedFilters,
-       filterValues,
-       hasCreate,
-       basePath,
-       selectedIds,
-       showFilter,
        total,
    } = useListContext();
    return (
        <TopToolbar className={className} {...sanitizeListRestProps(rest)}>
-           {filters && cloneElement(filters, {
-               resource,
-               showFilter,
-               displayedFilters,
-               filterValues,
-               context: 'button',
-           })}
+           {cloneElement(filters, { context: 'button' })}
-           <CreateButton basePath={basePath} />
+           <CreateButton />
-           <ExportButton
-               disabled={total === 0}
-               resource={resource}
-               sort={currentSort}
-               filterValues={filterValues}
-               maxResults={maxResults}
-           />
+           <ExportButton disabled={total === 0} maxResults={maxResults} />
            {/* Add your custom actions */}
            <Button
                onClick={() => { alert('Your custom action'); }}
                label="Show calendar"
            >
                <IconEvent />
            </Button>
        </TopToolbar>
    );
};
```

For a simpler use case, the doc is even simpler:

```jsx
const ListActions = () => (
    <TopToolbar >
        {cloneElement(filters, { context: 'button' })}
        <CreateButton />
        <ExportButton />
        {/* Add your custom actions */}
        <Button
            onClick={() => { alert('Your custom action'); }}
            label="Show calendar"
        >
            <IconEvent />
        </Button>
    </TopToolbar>
);
```

I think this is simple enough that we don't have to introduce a new component for that.

2021-06-03 03:41 UTC, WiXSL commented
So, I should revert everything and update the only documentation?

2021-06-17 10:35 UTC, djhi requested changes
Thanks!

2021-06-17 10:35 UTC, djhi commented on docs/List.md
> +You can add extra actions to a `<List>` by using the `actions` prop:
The original sentence was fine imo

2021-06-17 10:35 UTC, djhi commented on docs/List.md
> +If you want to have control over default actions as well, you can replace the entire `actions` component by your own:
```suggestion
This allows you to further control how the default actions behaves. For example, you could disable the `<ExportButton>` when the list is empty:
```

2021-06-17 12:35 UTC, djhi requested changes

2021-06-17 12:35 UTC, djhi commented on docs/List.md
> +This allows you to further control how the default actions behaves. For example, you could disable the `<ExportButton>` when the list is empty:
```suggestion
This allows you to further control how the default actions behave. For example, you could disable the `<ExportButton>` when the list is empty:
```

Achievement unlocked: tricked El Corrector :laughing:

2021-06-17 12:51 UTC, djhi approved these changes

2021-06-17 14:16 UTC, fzaninotto requested changes

2021-06-17 14:16 UTC, fzaninotto commented on docs/List.md
> +    useListContext
useListContext is already included line 131

2021-06-17 14:16 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/ListActions.tsx
> + *             <ExportButton
why  not use the simpler version?

```
{cloneElement(props.filters, { context: 'button' })}  
<CreateButton/>
<ExportButton/>
```

2021-06-17 20:20 UTC, fzaninotto approved these changes

2021-06-17 20:21 UTC, merged

2021-06-17 20:21 UTC, fzaninotto commented
Thanks!