[Docs] Add data example for ra-simple-rest
marmelab/react-admin pull request #6278
Opened 2021-05-13 10:46 UTC by karltaylor

This PR adds a small data example to help to get up and running with `ra-data-simple-rest`

I had trouble figuring out the correct data format, and it looks like [other people have too](https://stackoverflow.com/questions/60622649/ra-data-simple-rest-is-not-working-error-total-is-not-a-number-and-newrecords).

2021-05-17 08:39 UTC, djhi requested changes

2021-05-17 08:39 UTC, djhi commented on packages/ra-data-simple-rest/README.md
> +An example of `getList` data is:
```suggestion
The API response when called by `getList` should look like this:
```

2021-05-31 20:24 UTC, fzaninotto approved these changes

2021-05-31 20:24 UTC, merged

2021-05-31 20:24 UTC, fzaninotto commented
Thanks!