Add SimpleFormIterator label function
marmelab/react-admin pull request #6305
Opened 2021-05-25 08:05 UTC by iamstiil

Hopefully this finally works 😅 

Original PRs: #6292 #6294

2021-05-25 12:35 UTC, djhi requested changes

2021-05-25 14:45 UTC, djhi requested changes
Can you also update the documentation? https://github.com/marmelab/react-admin/blob/master/docs/Inputs.md#arrayinput

2021-06-04 15:15 UTC, djhi requested changes

2021-06-04 15:15 UTC, djhi commented on docs/Inputs.md
> +Furthermore, if you want to manipulate the label displayed left of each item, you can pass a function to `SimpleFormIterator` via the `labelFn` prop.
```suggestion
Furthermore, if you want to customize the label displayed for each item, you can pass a function to `SimpleFormIterator` via the `labelFn` prop.
```

Depending on the theme, the label might not be on the left

2021-06-11 14:37 UTC, djhi requested changes

2021-06-11 14:37 UTC, djhi commented on packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
> +        labelFn = DefaultLabelFn,
```suggestion
        getItemLabel = DefaultLabelFn,
```

2021-06-11 14:37 UTC, djhi commented on packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
> +                                {labelFn(index)}
```suggestion
                                {getItemLabel(index)}
```

2021-06-11 14:37 UTC, djhi commented on packages/ra-ui-materialui/src/form/SimpleFormIterator.tsx
> +    labelFn?: (index: number) => string;
```suggestion
    getItemLabel?: (index: number) => string;
```

2021-06-11 14:37 UTC, djhi commented on packages/ra-ui-materialui/src/form/SimpleFormIterator.spec.tsx
> +                                    labelFn={index => `3.${index}`}
```suggestion
                                    getItemLabel={index => `3.${index}`}
```

2021-06-11 14:37 UTC, djhi commented on docs/Inputs.md
> +Furthermore, if you want to customize the label displayed for each item, you can pass a function to `SimpleFormIterator` via the `labelFn` prop.
```suggestion
Furthermore, if you want to customize the label displayed for each item, you can pass a function to `SimpleFormIterator` via the `getItemLabel` prop.
```

2021-06-11 14:37 UTC, djhi commented on docs/Inputs.md
> +    <SimpleFormIterator labelFn={(index) => `${index + 1}. link`}>
```suggestion
    <SimpleFormIterator getItemLabel={(index) => `${index + 1}. link`}>
```

2021-06-18 14:04 UTC, djhi approved these changes

2021-06-22 20:06 UTC, fzaninotto approved these changes

2021-06-22 20:07 UTC, merged

2021-06-22 20:07 UTC, fzaninotto commented
Thanks!