Add ability to define filters as array of Inputs
marmelab/react-admin pull request #6368
Opened 2021-06-17 17:14 UTC by fzaninotto

## Problem

`<ListActions>` is hard to write, partly because of [the filter button/form combo](https://marmelab.com/react-admin/List.html#the-filter-buttonform-combo). The `<Filter>` element renders twice, which isn't a common practice, and creates a few problems.

## Solution

Allow `<List filters>` to be an array of inputs instead of a React element. 

```diff
-const PostFilter = props => (
-    <Filter {...props}>
-        <SearchInput source="q" alwaysOn />
-        <TextInput
-            source="title"
-            defaultValue="Qui tempore rerum et voluptates"
-        />
-        <QuickFilter
-            label="resources.posts.fields.commentable"
-            source="commentable"
-            defaultValue
-        />
-    </Filter>
-);
+const postFilter = [
+    <SearchInput source="q" alwaysOn />,
+    <TextInput source="title" defaultValue="Qui tempore rerum et voluptates" />,
+    <QuickFilter
+        label="resources.posts.fields.commentable"
+        source="commentable"
+        defaultValue
+    />,
+];

const PostList = props => {
         <List
             {...props}
             bulkActionButtons={<PostListBulkActions />}
-            filters={<PostFilter />}
+            filters={postFilter}
             sort={{ field: 'published_at', order: 'DESC' }}
             exporter={exporter}
         >
```

This allows to put the filters in a context, and to use `<FilterForm>` and `<FilterButton>` directly:

```jsx
const  ListActions = () => (
    <TopToolbar>
        <FilterButton />
        <CreateButton />
        <ExportButton />
    </TopToolbar>
);
```

- [x] Add support for array filters in `<List>`
- [ ] Write tests
- [ ] Update documentation

2021-06-22 17:30 UTC, fzaninotto commented
Switching to RFR

2021-06-28 08:50 UTC, djhi requested changes
Awesome! I remember having eslint issues about missing keys with the array syntax for the `<Resource>` though.

2021-06-28 08:50 UTC, djhi commented on docs/Inputs.md
> +An `Input` component displays an input, or a dropdown list, a list of radio buttons, etc. Such components allow to edit a record property, and are common in the `<Edit>`, `<Create>` component, and in
```suggestion
An `Input` component displays an input, or a dropdown list, a list of radio buttons, etc. Such components allow to edit a record property, and are common in the `<Edit>` and `<Create>` components, and in the List Filters.
```

2021-06-28 14:18 UTC, fzaninotto commented
@djhi I have had no eslint warning, and GitHub doesn't show any... Would you have a reproducible case?

2021-06-28 15:26 UTC, djhi commented
Nope, it was just something I remembered while working with the `<Resource>` in a render function. All good then!

2021-06-28 15:26 UTC, djhi approved these changes

2021-06-28 15:26 UTC, merged