Refactor arrayinput context
marmelab/react-admin pull request #6612
Opened 2021-09-23 15:10 UTC by djhi

- [x] Introduce ArrayInputContext
- [x] Refactor SimpleFormIterator and extract components
- [ ] Introduce SimpleFormIteratorItemContext and hook

2021-09-24 07:02 UTC, fzaninotto requested changes

2021-09-24 07:02 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
> +                            basePath={basePath}
so many props... Perhaps we need a context there, too?

2021-09-24 07:12 UTC, djhi commented on packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx
> +            <Button label="ra.action.add">
I know, it's planned for the next commit. I'm extracting all buttons

2021-09-24 07:12 UTC, djhi commented on packages/ra-ui-materialui/src/input/ArrayInput/ArrayInput.spec.tsx
> +            <ThemeProvider theme={theme}>
Because we use our Button component instead of the MUI ones

2021-09-27 07:41 UTC, fzaninotto approved these changes

2021-09-27 07:41 UTC, merged