Allow to send custom message in `checkError`
marmelab/react-admin pull request #6619
Opened 2021-09-27 12:54 UTC by dklimpel

Fixes #6547

Allow to send custom message in `checkError` like in `checkAuth`
https://github.com/marmelab/react-admin/blob/d33a4ee57e1e6347c9f9ad435b197c00af2d6e3a/docs/Authentication.md#L609
https://github.com/marmelab/react-admin/blob/d33a4ee57e1e6347c9f9ad435b197c00af2d6e3a/packages/ra-core/src/auth/useCheckAuth.ts#L67-L70

Example
```js
  checkError: ({ status }) => {
    if (status === 401) {
      return Promise.reject({ message: "Message 401" });
    } else if (status === 403) {
      return Promise.reject({ message: "Message 403" });
    }
    return Promise.resolve();
  },
```

2021-09-28 07:34 UTC, fzaninotto commented
Thanks for the PR! Could you add a unit test?

2021-09-28 08:45 UTC, dklimpel commented
Im not sure how to creat a good unit test for it.
At the moment there is a test:
https://github.com/marmelab/react-admin/blob/b0f997473868c68746188ef92ba2e325974f3ec5/packages/ra-core/src/auth/useLogoutIfAccessDenied.spec.tsx#L108-L119

But it checks only that there is one notification, not the content of it.

I could not find a similar unit test in https://github.com/marmelab/react-admin/blob/next/packages/ra-core/src/auth/useCheckAuth.spec.tsx

2021-09-28 08:48 UTC, dklimpel commented
Is this a good example for check the notify message?
https://github.com/marmelab/react-admin/blob/43c4fafc8bcedebc386c7d3dc3b63cfd56420a17/packages/ra-core/src/controller/details/useCreateController.spec.tsx#L122-L132

2021-10-05 07:45 UTC, djhi commented
Hi @dklimpel, sorry for the delay. Yes, you can use the same pattern as in `useCreateController.spec.tsx`.

2021-10-05 11:17 UTC, dklimpel commented
I am not able to write a test, sorry.
The "problem" is, that there is no `dispatch`.
Similar places in the code test the notifications in this `dispatch`
E.g.
https://github.com/marmelab/react-admin/blob/43c4fafc8bcedebc386c7d3dc3b63cfd56420a17/packages/ra-core/src/auth/Authenticated.spec.tsx#L51-L56

https://github.com/marmelab/react-admin/blob/43c4fafc8bcedebc386c7d3dc3b63cfd56420a17/packages/ra-core/src/controller/details/useCreateController.spec.tsx#L119-L121

This test is valid, bot has no test for notification, because `expect(dispatch).toHaveBeenCalledTimes(0);` 
```js
    it('new test', async () => {
        const history = createMemoryHistory();

        const { dispatch, queryByText } = renderWithRedux(
            <Router history={history}>
	            <AuthContext.Provider value={authProvider}>
	                <TestComponent error={new Error('denied')} />
	                <TestComponent error={new Error('denied')} />
	            </AuthContext.Provider>
            </Router>
        );
        await waitFor(() => {
            expect(authProvider.logout).toHaveBeenCalledTimes(1);
            expect(notify).toHaveBeenCalledTimes(1);
            expect(dispatch).toHaveBeenCalledTimes(0);
            expect(queryByText('logged in')).toBeNull();
        });
    });
```

2021-11-09 02:31 UTC, WiXSL commented
> I am not able to write a test, sorry. The "problem" is, that there is no `dispatch`. Similar places in the code test the notifications in this `dispatch` E.g.
> 

@dklimpel, you have access to the notifications, you just have to modify the `authProvider.checkAuth` function  inside `useLogoutIfAccessDenied.spec.tsx` to show any message.
You can do it like this:

```js
checkError: params => {
      if (params instanceof Error) {
          return Promise.reject(new Error(params.message === 'denied' ? 'logout' : params.message));
      }
      return Promise.resolve();
  },
```
And then make a test like this:

```jsx
    it('should notify if passed an error with a message that makes the authProvider throw', async () => {
        const { queryByText } = renderInRouter(
            <AuthContext.Provider value={authProvider}>
                <TestComponent error={new Error('Test message')} />
            </AuthContext.Provider>
        );
        await waitFor(() => {
            expect(authProvider.logout).toHaveBeenCalledTimes(1);
            expect(notify).toHaveBeenCalledTimes(1);
            expect(notify.mock.calls[0][0]).toEqual('Test message');
            expect(queryByText('logged in')).toBeNull();
        });
    });

2021-11-21 20:56 UTC, WiXSL commented
Can we dismiss the error CodeQL is throwing?

2021-11-21 21:26 UTC, dklimpel commented
Can you re-run CI? I have merged newest `next` branch.

2021-11-21 22:29 UTC, dklimpel commented
I am confused why there is an error in `navigation.js`

```
  Running:  navigation.js                                                                  (7 of 10)


  Navigation
    Sidebar
      1) should have tabbable menu items
    Skip Navigation Button
      ✓ should appear when a user immediately tabs on the homepage (307ms)


  1 passing (5s)
  1 failing

  1) Navigation
       Sidebar
         should have tabbable menu items:
     AssertionError: Timed out retrying: expected '<a.MuiMenuItem-root.MuiMenuItem-gutters.MuiButtonBase-root.RaMenuItemLink-root.css-is19is.RaMenuItemLink-active>' to have class 'Mui-focusVisible'
      at Context.eval (http://localhost:8080/__cypress/tests?p=integration/navigation.js:111:66)
```

2021-11-21 22:52 UTC, WiXSL commented
I've re-run it, now seems ok

2021-12-28 21:40 UTC, WiXSL approved these changes

2022-01-17 20:49 UTC, WiXSL requested changes

2022-01-17 20:49 UTC, WiXSL commented on docs/Authentication.md
> +| `checkError`     | Error is an auth error                    | `void | { redirectTo?: string, message?: string }` route to redirect to after logout, message to notify the user |
```suggestion
| `checkError`     | Error is an auth error                    | `void | { redirectTo?: string, message?: string | boolean  }` route to redirect to after logout, message to notify the user or `false` to disable notification |
```

2022-01-18 10:31 UTC, fzaninotto approved these changes

2022-01-18 10:32 UTC, merged

2022-01-18 10:32 UTC, fzaninotto commented
Thanks!