Remove prop injection in main page components
marmelab/react-admin pull request #6746
Opened 2021-11-04 08:59 UTC by fzaninotto

2021-11-07 22:08 UTC, fzaninotto commented
Switching to RFR

2021-11-08 11:03 UTC, djhi requested changes
Awesome!

2021-11-08 12:49 UTC, fzaninotto commented on packages/ra-core/src/controller/show/useShowController.ts
> +    const { id } = useParams<{ id?: string }>();
I don't see the use case for reusing that type, or for reusing the hook outside of the Show controller. Nice to have.

2021-11-08 13:28 UTC, djhi commented on packages/ra-core/src/controller/show/useShowController.ts
> +    const { id } = useParams<{ id?: string }>();
Agreed

2021-11-08 13:28 UTC, djhi approved these changes

2021-11-08 14:15 UTC, merged