Fix notify function when no type is passed
marmelab/react-admin pull request #6768
Opened 2021-11-10 18:18 UTC by nidebo

#6713 was fixing this problem but #6760 makes it happen again

2021-11-10 18:21 UTC, WiXSL commented
I've had added the exact change in #6760, but reverted for some reason, It seams ok.

2021-11-15 08:23 UTC, djhi requested changes

2021-11-15 08:23 UTC, djhi commented on packages/ra-core/src/sideEffect/useNotify.ts
> +                dispatch(showNotification(message));
Thanks!

```suggestion
            } else {
                const { type: messageType, ...options } = type || {};
                dispatch(showNotification(message, messageType, options));
            }
```

2021-11-15 09:23 UTC, nidebo commented on packages/ra-core/src/sideEffect/useNotify.ts
> +                dispatch(showNotification(message));
Applied, thanks!

2021-11-15 09:41 UTC, djhi approved these changes
Thanks!

2021-11-15 09:59 UTC, merged