Refactor error boundaries
marmelab/react-admin pull request #6854
Opened 2021-11-15 15:11 UTC by djhi

There's a downside. We used to display the error **inside** our layout. It's now **outside** it. I may revisit this later to make the integration nicer but this is on the critical path for react-router-v6.

2021-11-15 15:31 UTC, WiXSL requested changes

2021-11-15 15:31 UTC, WiXSL commented on UPGRADE.md
> +export const Error = (props: ErrorProps) => {
JS => No types allowed

2021-11-15 15:42 UTC, WiXSL approved these changes

2021-11-15 15:46 UTC, merged

2021-11-16 08:29 UTC, fzaninotto commented on docs/Theming.md
> -    errorInfo,
errorInfo was used inside the component JSX, how do we get it now?