Add support for router basename
marmelab/react-admin pull request #6917
Opened 2021-11-29 16:44 UTC by djhi

2021-12-02 12:49 UTC, WiXSL requested changes

2021-12-02 12:49 UTC, WiXSL commented on docs/Admin.md
> +Use this prop to make all routes and links in your Admin relative to a "base" portion of the URL pathname that they all share. This is useful when including the Admin inside a larger app. See https:/
`informations.` => **information**.

2021-12-06 14:04 UTC, djhi commented on docs/Admin.md
> +Use this prop to make all routes and links in your Admin relative to a "base" portion of the URL pathname that they all share. This is useful when including the Admin inside a larger app. See https:/
```suggestion
Use this prop to make all routes and links in your Admin relative to a "base" portion of the URL pathname that they all share. This is useful when including the Admin inside a larger app. See https://reactrouter.com/docs/en/v6/api#router for more information.
```

2021-12-06 15:20 UTC, djhi commented
With or without the basename, the app is served the same way and works

2021-12-06 15:52 UTC, fzaninotto commented
So what's the use of the basename prop?

2021-12-06 16:52 UTC, djhi commented
Actually, it only matters when using the browser history and not serving the app from the domain root.

2021-12-07 08:48 UTC, fzaninotto approved these changes

2021-12-07 08:49 UTC, fzaninotto commented
Then you should change the doc accordingly, to explain that it's only necessary when using browser history (and modify the example to include the history).

2021-12-07 16:50 UTC, fzaninotto approved these changes

2021-12-07 16:50 UTC, merged