Make possible to use a SimpleList as a child of an ArrayField
marmelab/react-admin pull request #6975
Opened 2021-12-10 16:30 UTC by Luwangel

## Description

The `<ArrayField>` builds a list context by passing null as total. The `SimpleList` expects a total > 0 to be rendered. Both are incompatible.

I studied two solutions:

1. Compute the total using ids (chosen)
2. Remove the total > 0 condition

To not introduce breaking changes, and because it's cleaner, I choose the first solution.

## Related Issue

Fixing https://github.com/marmelab/react-admin/issues/6974

2021-12-10 16:57 UTC, WiXSL approved these changes

2021-12-14 16:40 UTC, djhi requested changes
Can you add a test for the ArrayField and SimpleList?

2021-12-15 14:29 UTC, fzaninotto commented
Why don't you use useList? It's the perfect use case for it.

https://github.com/marmelab/react-admin/blob/next/docs/useList.md

2021-12-15 14:39 UTC, Luwangel commented
> Why don't you use useList? It's the perfect use case for it.
> 
> https://github.com/marmelab/react-admin/blob/next/docs/useList.md

The fix here is to make the ArrayField / SimpleList work together. But you're right, there are other ways to build this kind of feature.

2021-12-15 15:58 UTC, fzaninotto approved these changes

2021-12-15 15:58 UTC, merged