Migrate useGetMany to react-query
marmelab/react-admin pull request #7006
Opened 2021-12-16 15:59 UTC by fzaninotto

BC break: useGetMany no longers does query batching by default. For that, users must now cann useGetManyAccumulate.

- [x] Create `useGetMany` hook using react-query
- [ ] Create `useGetManyAccumulate` hook
- [ ] use `useGetManyAccumulate` in `ReferenceField`
- [ ] use `useGetManyAccumulate` in `ReferenceArrayField`
- [ ] use `useGetManyAccumulate` in `ReferenceInput`
- [ ] use `useGetManyAccumulate` in `ReferenceArrayInput`
- [ ] use `useGetManyAccumulate` in `ReferenceManyInput`
- [ ] Fix tests
- [ ] Add upgrade guide

2021-12-16 16:02 UTC, fzaninotto commented on packages/ra-core/src/dataProvider/useGetManyAggregate.ts
> +    return useQuery<RecordType[], Error, RecordType[]>(
this approach is actually more powerful than the previous one: not only do we no longer have to mess with useState, we don't need to batch the side effects anymore either. 

Bonus: both the individual and the aggregated queries are in the cache, so after visiting a post list and displaying a post, its tags will display right away.

2021-12-20 09:19 UTC, wattroll commented
Wonderful. And I was just wondering why my `ReferenceField`s aren't going through react-query. I'll give this a try and have a little look at the code :eyes:.

2021-12-20 09:24 UTC, wattroll commented
Seem to be causing troubles with `ReferenceField > AutocompleteInput` combination:


In a nutshell: selecting an Autocomplete options item that  isn't in the `useGetMany` cache shows "not found" error message during the fetching of the item and adds an empty string to the autocomplete options:

https://user-images.githubusercontent.com/79251424/146743353-8231be1a-211c-409d-8bea-c0989d92dc59.mp4



Doesn't happen with the items that have been fetched previously:


https://user-images.githubusercontent.com/79251424/146743394-e8e1c5ff-6bc7-44fc-8e02-90938d0d5d5d.mp4

I got this by checking out the branch and running the demo. Hope you can reproduce, if not I'll dig around further.

2021-12-20 09:31 UTC, wattroll commented
Can `useGetList` optimistically update the `useGetMany` cache?

2021-12-20 13:39 UTC, fzaninotto commented
@wattroll thanks for the report, I'll look into it.

2021-12-21 11:52 UTC, WiXSL requested changes
**UPGRADE.md**:

```diff
-Specialized data provider hooks (like `useGetList` and `useUpdate`) have a new signature. There are 2 changes:
+Specialized data provider hooks (like `useGetList`, `useGetMany`, `useGetManyReference`, `useGetOne` and `useUpdate`) have a new signature. There are 2 changes:

2021-12-21 11:54 UTC, WiXSL requested changes

2021-12-21 11:54 UTC, WiXSL commented on packages/ra-core/src/dataProvider/useGetMany.ts
> +    return useQuery<RecordType[], Error, RecordType[]>(
```suggestion

    return useQuery<RecordType[], Error, RecordType[]>(
```

2021-12-21 11:55 UTC, WiXSL requested changes

2021-12-21 11:55 UTC, WiXSL commented on packages/ra-core/src/controller/field/useReferenceArrayFieldController.ts
>   * @returns {ReferenceArrayProps} The reference props
```suggestion
 * @returns {UseReferenceArrayFieldControllerParams} The reference props
```

2021-12-21 11:57 UTC, WiXSL requested changes

2021-12-21 11:57 UTC, WiXSL commented on packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
>   * @return {Object} controllerProps Fetched data and callbacks for the ReferenceArrayInput components
```suggestion
 * @return {UseReferenceArrayInputParams} controllerProps Fetched data and callbacks for the ReferenceArrayInput components
```

2021-12-21 11:57 UTC, WiXSL commented on packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
> +    props: UseReferenceArrayInputPArams
```suggestion
    props: UseReferenceArrayInputParams
```

2021-12-21 11:57 UTC, WiXSL commented on packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
> +export interface UseReferenceArrayInputPArams {
```suggestion
export interface UseReferenceArrayInputParams {
```

2021-12-21 11:59 UTC, WiXSL requested changes

2021-12-21 11:59 UTC, WiXSL commented on packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
>  import { useGetList } from '../../dataProvider/useGetList';
```suggestion
```

2021-12-21 11:59 UTC, WiXSL commented on packages/ra-core/src/controller/input/useReferenceArrayInputController.ts
> +import { useGetManyAggregate } from '../../dataProvider';
```suggestion
import { useGetManyAggregate, useGetList } from '../../dataProvider';
```

2021-12-21 12:07 UTC, WiXSL reviewed
`useGetManyAggregate` hook is not mentioned at all in the docs. Maybe in another PR ?

2021-12-21 12:11 UTC, WiXSL requested changes

2021-12-21 12:28 UTC, WiXSL reviewed
The first time I filter the `Orders` list o the demo by `Customers` I get this error:

![2021-12-21 092649](https://user-images.githubusercontent.com/8268610/146929974-06d2c02a-9e0d-4e9e-9175-1565e4b2794f.png)

2021-12-21 12:45 UTC, fzaninotto commented
> `useGetManyAggregate` hook is not mentioned at all in tehe docs. Maybe in another PR ?

I'm not sure I want to make it public API yet.

2021-12-21 12:53 UTC, WiXSL requested changes

2021-12-21 12:53 UTC, WiXSL commented on UPGRADE.md
> +Specialized data provider hooks (like `useGetOne`, `useGetList`, `useGetMany` and `useUpdate`) have a new signature. There are 2 changes:
```suggestion
Specialized data provider hooks (like `useGetList`, `useGetMany`, `useGetManyReference`, `useGetOne` and `useUpdate`) have a new signature. There are 2 changes:
```

2021-12-21 12:53 UTC, WiXSL commented on UPGRADE.md
> +Specialized data provider hooks (like `useGetOne`, `useGetList`, `useGetMany` and `useUpdate`) have a new signature. There are 2 changes:
I've added `useGetManyReference` here, is simpler than reviewing the same in the other PR

2021-12-21 13:49 UTC, merged

2021-12-21 13:49 UTC, fzaninotto commented
Thanks a lot for the review, @WiXSL!