[BC Break] Rename Record type to RaRecord
marmelab/react-admin pull request #7078
Opened 2022-01-13 14:41 UTC by fzaninotto

- [x] [BC Break] Rename type
- [x] Make it build
- [ ] Add Upgrade instructions

Closes #5074

2022-01-13 15:07 UTC, fzaninotto commented
Note: I'm not particularly fond of `RaRecord`, but I'm not sure the alternatives are better:

- `Entity` would be the correct term, but it doesn't clic if you didn't study DDD, and it conflicts wit hthe term 'record' that we use all arount the documentation 
- `Data` is too generic
- `RecordData` is... meh
- `RecordType` doesn't follow the pattern we use (never append or prepend 'type'  or 'interface'). Same for `IRecord`.
- `AdminRecord` doesn't mean anything

If someone comes up with a better name before we release 4.0, the renaming should be straightforward, so please voice your opinion!

2022-01-14 09:04 UTC, djhi requested changes

2022-01-14 12:42 UTC, WiXSL approved these changes
Other that the conflicts, everything looks ok.

2022-01-14 12:51 UTC, djhi approved these changes

2022-01-14 12:51 UTC, WiXSL reviewed
Hold on, I'm trying the demo, I think I've found something...

2022-01-16 20:31 UTC, merged