fix: initialValue prop not used when input value is null
marmelab/react-admin pull request #7133
Opened 2022-01-24 15:52 UTC by thdk

fixes #7132

I have replaced the lodash get method so that it is easier for maintainers / contributors to see what happens.
Lodash `get` will not use the default value when the result is `null`. While we need the initialValue to be returned for both null and undefined values as written in react admin docs. See docs for, the DateInput component.

2022-01-24 16:31 UTC, WiXSL requested changes

2022-01-24 16:31 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    let inputInitialValue = record ? record[source] : undefined;
```suggestion
    let inputInitialValue = record ? get(record, source) : undefined;
```

2022-01-24 16:31 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    let inputInitialValue = record ? record[source] : undefined;
We still need to use lodash to support nested source

2022-01-24 17:02 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    let inputInitialValue = record ? record[source] : undefined;
Thank you for your contribution!

2022-01-24 18:58 UTC, WiXSL requested changes

2022-01-24 18:58 UTC, WiXSL commented on packages/ra-core/src/form/useInput.spec.tsx
> +    it('applies the initialValue when input has null value', () => {
```suggestion
    it('should apply initialValue when input has null value', () => {
```

2022-01-24 19:03 UTC, WiXSL approved these changes

2022-01-24 20:23 UTC, thdk commented
@WiXSL I've just found out how to test is with the examples/simple project. Maybe wait with review untill I confirmed it is working as expected there.

2022-01-24 20:28 UTC, thdk commented
@WiXSL Yep, I can confirm this is now working as expected!

2022-01-24 21:36 UTC, WiXSL requested changes

2022-01-24 21:36 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    let inputInitialValue = get(record, source);
```suggestion
    const inputInitialValue = get(record, source, initialValue);
```

2022-01-24 21:36 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    if (inputInitialValue === null || inputInitialValue === undefined) {
```suggestion
```

2022-01-24 21:36 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +        inputInitialValue = initialValue;
```suggestion
```

2022-01-24 21:36 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +        initialValue: inputInitialValue,
```suggestion
	initialValue: inputInitialValue ?? initialValue,
```

2022-01-24 21:36 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    }
```suggestion
```

2022-01-24 21:36 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> +    let inputInitialValue = get(record, source);
Maybe is simpler like this

2022-01-24 21:39 UTC, WiXSL requested changes

2022-01-24 21:39 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> -        initialValue: get(record, source, initialValue),
```js
const inputInitialValue = get(record, source, initialValue);

const { input, meta } = useFinalFormField(finalName, {
	initialValue: inputInitialValue ?? initialValue,

2022-01-24 21:39 UTC, WiXSL commented on packages/ra-core/src/form/useInput.ts
> -        initialValue: get(record, source, initialValue),
Maybe you can rewrite it like this.

2022-01-25 10:53 UTC, WiXSL approved these changes

2022-01-25 13:29 UTC, WiXSL commented
@thdk, So after discussion the solution is to fix the documentation, not the inputs.
So `null` value should be handled in userland.

2022-01-25 14:54 UTC, fzaninotto commented
Superseded by #7139

2022-01-25 14:54 UTC, closed without merging