[BC Break] Remove redux
marmelab/react-admin pull request #7177
Opened 2022-02-02 17:50 UTC by fzaninotto

- [x] Remove `<Admin customReducers>`
- [x] Remove `<Admin initialState>`
- [x] Do not create a Redux `<Provider>` in `<Admin>`
- [x] Remove dependencies on `redux` and `react-redux` packages
- [x] MAke sure tests and demos still work
- [x] Fix doc
- [x] Add changelog

2022-02-02 17:57 UTC, fzaninotto commented
I'm surprised that the build of the e-commerce demo doesn't change much:

```
File sizes after gzip:

  607.9 kB (-1.69 kB)  build/static/js/main.886b6121.js
  85.79 kB             build/static/js/327.3776b9a6.chunk.js
  67.96 kB             build/static/js/775.729f778c.chunk.js
  58.95 kB             build/static/js/250.42aa2365.chunk.js
  12.43 kB             build/static/js/292.eea62de7.chunk.js
  5.73 kB (+1 B)       build/static/js/908.0296630d.chunk.js
  3.95 kB              build/static/js/376.72118f7b.chunk.js
  3.73 kB              build/static/js/477.84064d46.chunk.js
  3.61 kB              build/static/js/247.4f700bc0.chunk.js
  1.43 kB (+1 B)       build/static/js/151.cf8ab998.chunk.js
```

While bundlephobia tells me that [react-redux alone weighs 5,4 kB](https://bundlephobia.com/package/react-redux@7.2.6).

2022-02-02 19:01 UTC, WiXSL reviewed
There is still a dependency to `"@types/react-redux": "^7.1.1"`, in the main `react-admin/package.json`, I don't know if it's necessary

2022-02-03 08:20 UTC, djhi requested changes
There's an eslint warning left

2022-02-03 08:20 UTC, djhi commented on UPGRADE.md
> +The `<Admin initialState>` prop used to be used to initialize the store. As there is no store, you cannot set the react-admin defaults this way.
```suggestion
The `<Admin initialState>` prop used to be used to initialize the redux store. As there is no redux store anymore, you cannot set the react-admin defaults this way.
```

2022-02-03 08:20 UTC, djhi commented on UPGRADE.md
> +React-admin used `dispatch` in many other places, but they were already behind a hook (`useRecordSelection`, `useListParams`, `useExpanded`, `useNotify`, `useSidebarState`), and not documented. If yo
```suggestion
React-admin used `dispatch` in many other places, but they were already behind a hook (`useRecordSelection`, `useListParams`, `useExpanded`, `useNotify`, `useSidebarState`), and not documented. If you dispatched react-admin actions manually, you'll have to look for the hook alternatives.
```

2022-02-03 09:08 UTC, djhi approved these changes

2022-02-03 09:09 UTC, merged