Add documentation about filter operators
marmelab/react-admin pull request #7241
Opened 2022-02-15 14:33 UTC by fzaninotto

Adding this doc show that #7122 isn't required.

2022-02-15 16:36 UTC, djhi requested changes

2022-02-15 16:36 UTC, djhi commented on docs/FilteringTutorial.md
> +Some API backend (e.g. JSON Server) know how to handle this syntax. If your API doesn't understand these 'virtual fields', you will have to transform them into the expected syntax in the Data Provide
```suggestion
Some API backends (e.g. JSON Server) know how to handle this syntax. If your API doesn't understand these 'virtual fields', you will have to transform them into the expected syntax in the Data Provider.
```

2022-02-15 18:47 UTC, WiXSL requested changes

2022-02-15 18:47 UTC, WiXSL commented on docs/FilteringTutorial.md
> +    <DateInput source="released_gte" label="Released after" />
```suggestion
    <DateInput source="released_gte" label="Released after" />,
```

2022-02-15 18:47 UTC, WiXSL commented on docs/FilteringTutorial.md
> +```js
```suggestion
```json
```

2022-02-15 18:47 UTC, WiXSL commented on docs/FilteringTutorial.md
> +        });
```suggestion
        }));
```

2022-02-16 07:21 UTC, fzaninotto commented on docs/FilteringTutorial.md
> +```js
no, it's actually JavaScript

2022-02-16 08:06 UTC, djhi approved these changes

2022-02-16 08:06 UTC, merged