Update datagrid style overrides
marmelab/react-admin pull request #7270
Opened 2022-02-18 06:55 UTC by smeng9

The datagrid override seems is forgotten in the first beta version.

This pull request also adds a table wrapper, so we can set a width for table and make a scroll bar appear right below the table.

(Previously in examples, the scrollbar always appears on the bottom of the page, when scrolling horizontally datagrid may cover the menu)

2022-02-18 08:31 UTC, fzaninotto commented
Thanks for the overrideResolver, which was indeed forgotten.

I don't uderstand the need for a wrapper though:

1- you can add it to your markup directly

```jsx
const PostList = () => (
  <List>
     <Wrapper>
       <Datagrid>
           //..
       </Datagrid>
     </Wrapper>
  </List>
);

2- you can normally fix the height of the table through the `<Datagrid sx>` prop

2022-02-18 16:31 UTC, smeng9 commented
Hi @fzaninotto Thanks for your reply. I will explain why we need a wrapper for table.

We are trying to achieve the following css effect by setting the datagrid `{{width: "100%", overflowX: "auto"}}` so it will not overflow parent container and have the table scrollable horizontally. See the visualization attached.
![scrollbar](https://user-images.githubusercontent.com/38666763/154719298-94ebb06d-2a81-4caf-b0c7-e8dd50de9f1d.PNG)

We had thought about your two methods.
For the first method
```
const PostList = () => (
  <List>
     <div style={{width: "100%", overflowX: "auto"}}>
       <Datagrid>
           //..
       </Datagrid>
     </div>
  </List>
);
```
This will break the bulkactions because `overflowx`=auto and `overflowy` will interfere with each other (This is a CSS "feature", See: https://www.brunildo.org/test/Overflowxy2.html) So it will make `overflowy` hidden as well. The way we added bulkactions is setting a negative transform to it, but it is considered overflow, so it will not be visible. See the attached example.
![bulkaction](https://user-images.githubusercontent.com/38666763/154720840-15a445bb-fc4f-4fe9-8555-a0fa9fea4685.PNG)

For the second method, adding sx property to datagrid also does not work well.
The table will not respect width: "100%" rule after overflow because it is a table, not a div. It will only have 100% when there are not too many columns. Forcing it to `display: block` also breaks the layout when there is not enough columns. That is the reason we need a wrapper div just for the table to make the table horizontally scrollable. See attached screenshot for problem.
![table100](https://user-images.githubusercontent.com/38666763/154721901-bd47bb31-b647-4f49-8132-c8dd0676d516.PNG)


This CSS problem does not appear in v3 because bulkaction was not part of the datagrid in v3, but now it seems gets moved into the datagrid in v4.

2022-02-24 20:24 UTC, smeng9 commented
Hi @fzaninotto any further questions on moving this PR forward?

2022-02-25 08:29 UTC, fzaninotto requested changes
Thanks. You also need to add the doc for this change. Could you update the table of available CSS class names in Datagrid.md?

2022-02-25 18:52 UTC, smeng9 commented
documentation is done

2022-03-01 22:01 UTC, fzaninotto approved these changes

2022-03-01 22:02 UTC, merged

2022-03-01 22:02 UTC, fzaninotto commented
Thanks!