Fix inconsistencies in ReferenceInput and ReferenceArrayInput
marmelab/react-admin pull request #7273
Opened 2022-02-18 14:16 UTC by WiXSL

2022-02-23 16:29 UTC, fzaninotto requested changes

2022-02-23 16:29 UTC, fzaninotto commented on docs/ReferenceArrayInput.md
> +**Note**: `<ReferenceArrayInput>` doesn't accept the [common input props](./Inputs.md#common-input-props) is the responsability of children to apply them.
```suggestion
**Note**: `<ReferenceArrayInput>` doesn't accept the [common input props](./Inputs.md#common-input-props) ; it is the responsability of children to apply them.
```

2022-02-23 16:29 UTC, fzaninotto commented on docs/ReferenceInput.md
> +**Note**: `<ReferenceInput>` doesn't accept the [common input props](./Inputs.md#common-input-props) is the responsability of children to apply them.
```suggestion
**Note**: `<ReferenceInput>` doesn't accept the [common input props](./Inputs.md#common-input-props) ; it is the responsability of children to apply them.
```

2022-02-28 08:11 UTC, djhi approved these changes

2022-02-28 10:50 UTC, merged