Add LanguageSwitcher
marmelab/react-admin pull request #7332
Opened 2022-03-02 09:39 UTC by djhi

I'm considering renaming this component to `LocaleMenuButton`. @fzaninotto, what do you think ?

2022-03-02 09:56 UTC, fzaninotto approved these changes

2022-03-02 10:02 UTC, fzaninotto requested changes

2022-03-02 10:02 UTC, fzaninotto commented on packages/ra-ui-materialui/src/button/LocalesMenuButton.spec.tsx
> +describe('LanguageSwitcher', () => {
```suggestion
describe('LocalesMenuButton', () => {
```

2022-03-02 11:38 UTC, WiXSL requested changes

2022-03-02 11:38 UTC, WiXSL commented on docs/LocalesMenuButton.md
> +import { Box, Typography } from '@material-ui/core';
```suggestion
import { Box, Typography } from '@mui/material';
```

2022-03-02 11:41 UTC, WiXSL requested changes

2022-03-02 11:41 UTC, WiXSL commented on packages/ra-ui-materialui/src/button/LocalesMenuButton.spec.tsx
> +    test('should allow to change language', async () => {
```suggestion
    it('should allow to change language', async () => {
```

2022-03-02 11:45 UTC, WiXSL commented on docs/LocalesMenuButton.md
> +| `& .RaLocalesMenuButton-selectedLanguage`      | Applied to the `Typography` component that shows the current language |
Technically, is not a `Typography` is a `div`, mee

2022-03-02 11:46 UTC, WiXSL approved these changes

2022-03-02 12:52 UTC, djhi commented on docs/LocalesMenuButton.md
> +| `& .RaLocalesMenuButton-selectedLanguage`      | Applied to the `Typography` component that shows the current language |
```suggestion
| `& .RaLocalesMenuButton-selectedLanguage`      | Applied to the current language element |
```

2022-03-04 09:50 UTC, fzaninotto requested changes
Almost perfect!

2022-03-04 09:50 UTC, fzaninotto commented on docs/Reference.md
> +* [`<LocalesMenuButton>`](./LocalesMenuButton.md)
It's not ordered alphabetically anymore

2022-03-04 10:36 UTC, fzaninotto approved these changes

2022-03-04 10:36 UTC, merged