Make e-commerce demo canonical
marmelab/react-admin pull request #7360
Opened 2022-03-07 22:48 UTC by fzaninotto

- [x] Invoices
- [x] Orders
- [x] Finishing touches
- [x] Fix UserMenu on small screens
- [x] Fix AutocompleteInput doesn't have a minimum width (and doesn't support `sx`)

2022-03-08 08:25 UTC, djhi requested changes

2022-03-08 08:25 UTC, djhi commented on packages/ra-ui-materialui/src/input/AutocompleteInput.tsx
> +}));
You have to update the upgrade guide and the docs about this.

2022-03-08 11:25 UTC, WiXSL requested changes
Customers: In the following gif you can see two issues, The moving inputs when selecting items and the cut of avatar on the app bar

![chrome-capture (1)](https://user-images.githubusercontent.com/8268610/157231029-cc6956f5-32f7-4903-ba05-0f26d609d650.gif)

2022-03-09 11:32 UTC, djhi approved these changes
:fire:

2022-03-09 11:33 UTC, djhi commented on packages/ra-core/src/dataProvider/useIsDataLoaded.ts
> +export const useIsDataLoaded = (
It would be nice to document this

2022-03-09 13:04 UTC, merged