Fix exporter override
marmelab/react-admin pull request #7395
Opened 2022-03-16 21:13 UTC by WiXSL

Fixes #7394

2022-03-21 21:37 UTC, fzaninotto requested changes
This deserves an integration test

2022-03-21 21:37 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/ListView.tsx
> +        exporter,
I think the change should be in ListActions, which should read the `exporter` from the `ListContext` rather than the props.

2022-03-22 08:15 UTC, djhi approved these changes

2022-03-22 09:00 UTC, fzaninotto approved these changes

2022-03-22 09:00 UTC, merged