Fix FilterForm reset
marmelab/react-admin pull request #7442
Opened 2022-03-29 10:32 UTC by djhi

Fixes #7432

2022-03-29 10:49 UTC, WiXSL requested changes

2022-03-29 10:49 UTC, WiXSL commented on packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> +                    console.log({ newValues, displayedFilters });
```suggestion
```

2022-03-29 11:03 UTC, WiXSL requested changes
This is great!
However, I found last problem.
1- Add "Title" filter in simple project's PostList.
2- Try to remove the filter entirely by clicking in the remove button.

Result: The filter stays there instead of being removed

2022-03-29 11:36 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> +    values: Record<string, any>,
could you name this one `formValues` for clarity?

2022-03-29 11:37 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> +    values: Record<string, any>,
not fan of functions that mutate their arguments

2022-03-29 11:39 UTC, djhi commented on packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> +                    console.log({ newValues, displayedFilters });
Oups ^^

2022-03-29 12:08 UTC, WiXSL requested changes

2022-03-29 12:08 UTC, WiXSL commented on packages/ra-ui-materialui/src/list/filter/FilterForm.tsx
> +    console.log({ displayedFilters });
```suggestion
```

2022-03-29 12:47 UTC, WiXSL requested changes
Now the `Commentable` filter is always On in simple project's PostList

2022-03-29 15:08 UTC, WiXSL approved these changes
Now, is ok 👍

2022-03-30 07:49 UTC, fzaninotto approved these changes

2022-03-30 07:49 UTC, merged