Fix SelectInput / SelectArrayInput onChange handler
marmelab/react-admin pull request #7519
Opened 2022-04-11 13:17 UTC by WiXSL

Fixes #7518

SelectInput / SelectArrayInput  change event handler should receive the event object unless the change was fired due to the creation of a new item, in that case it should receive the new value

2022-04-12 11:23 UTC, fzaninotto commented
Also, it seems the accepted `onChange` arguments are fuzzy: event or value? We should choose one, and expect it everywhere. I don't mind if we support both for BC, but the types (and documentation) must be clear about the idiomatic way.

2022-04-12 11:43 UTC, WiXSL commented
> I approve the changes, but I have a few questions:
> 
> * Are `SelectArrayInput` and `SelectInput` the only components affected by this? What about `TextInput` and the others for example?

The only other inputs that do not pass the event object are `AutocompleteInput` and `AutocompleteArrayInput` (that I know of)
  According to @djhi, this comes from problems with final-form, maybe It could be improved now that we use react-hook-form 

> * Why do we need to do a difference with what we send to the `onChange` callback when we add an item vs when we select another? Is it documented somewhere?

As of this PR, my intention was just to maintain the functionality of `master` preventing a BC.
But I think the answer is in the fact that you can create new items, and in that case you don't have the value in the event object.
Maybe this can be changed, to pass two arguments, the event object and the new item to the onChange event handler.

I don't think all of this behavior is properly documented.

2022-04-12 11:47 UTC, WiXSL commented
> Also, it seems the accepted `onChange` arguments are fuzzy: event or value? We should choose one, and expect it everywhere. I don't mind if we support both for BC, but the types (and documentation) must be clear about the idiomatic way.

Ok, so, to be clear, do you want me to use this PR to change the onChange event handlers of these inputs to always pass the event object?
In the case of newly created items, a second arguments must be used then, since the event object doesn't include this new value

2022-04-13 07:45 UTC, slax57 requested changes

2022-04-13 07:45 UTC, slax57 commented on packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
> +            console.log(eventOrChoice);
console.log spotted

2022-04-13 07:46 UTC, slax57 commented on packages/ra-ui-materialui/src/input/SelectArrayInput.tsx
> +            console.log(eventOrChoice);
otherwise I'm happy with the code 😅

2022-04-27 08:48 UTC, merged