Allow To Create An Admin Without Resources
marmelab/react-admin pull request #7609
Opened 2022-04-29 16:32 UTC by djhi

Fixes #7598

2022-05-01 11:51 UTC, fzaninotto requested changes

2022-05-01 11:51 UTC, fzaninotto commented on packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
> +    console.log({ status });
console.log spotted

2022-05-01 11:51 UTC, fzaninotto commented on packages/ra-core/src/core/useConfigureAdminRouterFromChildren.tsx
> +            resources,
I suggest you use the same `routesandResources`  as in the effect, so that the reader doesn't try to understand why there is a difference

2022-05-02 08:49 UTC, slax57 approved these changes
Okay actually it was not as complicated as I imagined 😅

2022-05-02 09:06 UTC, fzaninotto approved these changes

2022-05-02 09:06 UTC, merged