Add middlewares support to create and edit controllers
marmelab/react-admin pull request #7701
Opened 2022-05-17 09:01 UTC by djhi

2022-05-17 09:46 UTC, slax57 approved these changes
👏

2022-05-17 13:55 UTC, fzaninotto requested changes

2022-05-17 13:55 UTC, fzaninotto commented on packages/ra-core/src/controller/create/useCreateController.ts
> +        addMiddleware: addMiddleware,
I'd call it `registerMutationMiddleware` and the other `unregisterMutationMiddleware`

2022-05-17 13:55 UTC, fzaninotto commented on packages/ra-core/src/controller/saveContext/useAddMiddleware.ts
> +export const useAddMiddleware = <
"middleware" is generic. Middleware for what?

I'd call it `useRegisterMutationMiddleware`

2022-05-17 13:55 UTC, fzaninotto commented on packages/ra-core/src/controller/saveContext/useMutationMiddlewares.ts
> +            const next = (...newArgs: any) => {
![image](https://user-images.githubusercontent.com/99944/168824864-39f0ab6a-ecfb-4bd9-af6c-dfe1837e7865.png)

This magic code is a bot hard to reread, would you mind adding a bit of comments?

2022-05-17 13:55 UTC, fzaninotto commented on packages/ra-core/src/controller/edit/useEditController.spec.tsx
> +                        <SaveContextProvider
Why do we need all that? We don't register anything, it shouldn't be required.

2022-05-17 13:55 UTC, fzaninotto commented on packages/ra-core/src/controller/edit/useEditController.spec.tsx
> +                                    <SaveContextProvider
Same. Why would we add a SeveContext if we don't use it?

2022-05-17 13:55 UTC, fzaninotto commented on packages/ra-core/src/controller/edit/useEditController.spec.tsx
> +        const middleware: Middleware<ReturnType<typeof useUpdate>[0]> = jest.fn(
You should document that type in the hook jsDoc, or we'll look for it every time

2022-05-18 07:00 UTC, fzaninotto commented on packages/ra-core/src/controller/edit/useEditController.spec.tsx
> +                        save,
why do you unstructure save, saving and the others if you don't use them? I don't see the purpose of this change. Same for the following tests.

2022-05-18 11:38 UTC, fzaninotto commented on packages/ra-core/src/controller/edit/useEditController.spec.tsx
> +                            <SaveContextProvider
you don't need a SaveContext for this test. Same for some of the following tests

2022-05-18 12:23 UTC, fzaninotto approved these changes

2022-05-18 12:25 UTC, merged

2022-05-18 12:25 UTC, fzaninotto commented
\o/