Add LabelPrefix context to better guess correct input labels
marmelab/react-admin pull request #7710
Opened 2022-05-18 20:48 UTC by fzaninotto

Fixes #7646

Instead of using the `resource`, the function that builds field and input labels can use the value of a context, which is set by the forms. This allows for better defaults in forms when using `<ReferenceInput>` and `<ArrayInput>`.

The change is made BC by keeping the previous behavior when the `resource` is passed explicitly.

I also took the opportunity to fix default input labels in `<SimpleFormIterator>` children (instead of `resources.posts.fields.aothors.123.name`, they are now `resources.posts.fields.aothors.name`).

2022-05-18 21:29 UTC, djhi requested changes
SimpleFormIteratorItem should set a prefix as well if I understand correctly, shouldn't it?

2022-05-18 21:29 UTC, djhi commented on packages/ra-core/src/util/getFieldLabelTranslationArgs.ts
> +function onlyDigits(s) {
Use an arrow function for consistency?

2022-05-18 21:38 UTC, fzaninotto commented
> SimpleFormIteratorItem should set a prefix as well if I understand correctly, shouldn't it?

No, ArrayInput doesn't change the LabelPrefix, as developers will prefer to have the entire path in the message. For instance:

```jsx
const PostEdit = () => (
   <Edit>
     <SimpleForm>
       <ArrayInput source="backlinks">
          <SimpleFormIterator>
             <TextInput source="url" />
```

`ArrayInput` will generate for the backlinks sources like `backlinks.0.url`, `backlinks.1.url`, etc. What the developers need is a constant label for each input, BUT keeping the context of the post: `resources.posts.fields.backlinks.url`. So we shouldn't try to change the prefix in ArrayInput - this is really designed for ReferenceInputs (and other inputs reacting a new ResourceContext).

2022-05-19 08:45 UTC, fzaninotto commented on packages/ra-core/src/form/Form.tsx
> +            <LabelPrefixContextProvider prefix={`resources.${resource}.fields`}>
What should be the label prefix if we're not in the context of a resource?

2022-05-19 08:55 UTC, slax57 commented on packages/ra-core/src/form/Form.tsx
> +            <LabelPrefixContextProvider prefix={`resources.${resource}.fields`}>
IMO we should not have a `<LabelPrefixContextProvider ...>` in this case. Anyways the prefix should never be `"resources..fields"`. But maybe I'm warning for nothing, maybe this case will never happen. This is why I expressed my concern as a question 😅

2022-05-19 12:44 UTC, fzaninotto commented on packages/ra-core/src/form/Form.tsx
> +            <LabelPrefixContextProvider prefix={`resources.${resource}.fields`}>
I added a special prefix for that case

2022-05-19 12:52 UTC, fzaninotto commented on packages/ra-core/src/form/Form.tsx
> +            <LabelPrefixContextProvider prefix={`resources.${resource}.fields`}>
So apparently there were tests in the code to make sure that in this case the translation message is indeed `resources.undefined.fields.name`. Changing this breaks tests, and maybe also existing apps. Let's not address that case with this PR.

2022-05-19 13:02 UTC, merged