Warning when using null value on TextInput in EditPost Issue #7782
marmelab/react-admin pull request #7800
Opened 2022-06-08 21:19 UTC by winniecarole

please make the merge request

<img width="330" alt="image" src="https://user-images.githubusercontent.com/76600604/172719092-d14d97e5-d155-4a40-88d9-6b1c8690ff95.png">

2022-06-09 09:26 UTC, slax57 requested changes
Sorry but you're heading to the wrong direction imo with this PR. The fix should be around the TextInput component, and should not be specific to the PostEdit page!

Besides, please do not commit IDE specific files:
- .idea/misc.xml
- .idea/workspace.xml

2022-06-09 09:26 UTC, slax57 commented on docs/InputNullValue.md
> +}
What is the purpose of this file? :thinking: 

You did not add any new components so there is no need for a dedicated documentation file.

2022-06-09 09:26 UTC, slax57 commented on packages/ra-core/src/controller/edit/useEditController.ts
> +                            }
How can you expect this code to work on any other page that the PostEdit page of the demo? :thinking:

2022-06-13 07:30 UTC, slax57 commented
> Please tell me where the textInput component is because I can't find it. If possible the file where I have to make the modification

@winniecarole Sorry I do not know this upfront. Event I would have to do somme digging to find out where to make the modification.

Dealing with form inputs is not easy in react-admin. If you are struggling with this fix don't worry, maybe you can start with easier issues to begin with.

2022-09-29 13:40 UTC, WiXSL commented
Shouldn't #8188 make this PR unnecessary?

2022-09-30 04:45 UTC, fzaninotto commented
No news for some time, closing.

2022-09-30 04:45 UTC, closed without merging