Add ability to accept more than one child in `<ReferenceField>`
marmelab/react-admin pull request #7812
Opened 2022-06-10 17:27 UTC by fzaninotto

## Problem

Developers often need to render more than one field of the reference table (e.g. if the `users` table has a `first_name` and a `last_name` field) in a `<ReferenceField>`. And `<FunctionField>` is a bit cumbersome. 

## Solution 

Let `<ReferenceField>` accept more than one child, so that developers can use as many `<Field>` as they like:

```jsx
import { Show, SimpleShowLayout, ReferenceField, TextField, DateField, FunctionField } from 'react-admin';

export const PostShow = () => (
    <Show>
        <SimpleShowLayout>
            <TextField source="id" />
            <TextField source="title" />
            <DateField source="published_at" />
            <ReferenceField label="Author" source="user_id" reference="users">
                <TextField source="first_name" />{' '}
                <TextField source="last_name" />
            </ReferenceField>
        </SimpleShowLayout>
    </Show>
);
```

2022-06-13 09:19 UTC, slax57 requested changes
Otherwise, that's great! And we can probably do the same with ReferenceManyField too

2022-06-13 09:19 UTC, slax57 commented on docs/ReferenceField.md
> +That's why you often need to set an explicit `label` on a `<RefezrenceField>`:
```suggestion
That's why you often need to set an explicit `label` on a `<ReferenceField>`:
```

2022-06-13 11:45 UTC, djhi requested changes

2022-06-13 11:45 UTC, djhi commented on docs/ReferenceField.md
> +A `<ReferenceField>` displays nothing on its own, it just fetches the data, pust it in a [`RecordContext`](./useRecordContext.md), and lets its child to render it. Usual child components for `<Refere
```suggestion
A `<ReferenceField>` displays nothing on its own, it just fetches the data, puts it in a [`RecordContext`](./useRecordContext.md), and lets its children render it. Usual child components for `<ReferenceField>` are other `<Field>` components (e.g. [`<TextField>`](./TextField.md)).
```

2022-06-13 13:05 UTC, slax57 approved these changes
Build is failing though :slightly_frowning_face:

2022-06-13 17:26 UTC, fzaninotto commented
Back to WIP to address other reference field components

2022-06-15 10:42 UTC, fzaninotto commented
back to RFR

2022-06-15 14:32 UTC, djhi requested changes
:100:

2022-06-15 14:32 UTC, djhi commented on docs/ReferenceArrayField.md
> +`<ReferenceArrayField>` fetches all the related records, and displays them all, too. You can use the `filter` prop to filter the list of related records to dispaly (this works by filtering the record
```suggestion
`<ReferenceArrayField>` fetches all the related records, and displays them all, too. You can use the `filter` prop to filter the list of related records to display (this works by filtering the records client-side, after the fetch).
```

2022-06-16 08:07 UTC, slax57 commented on packages/ra-ui-materialui/src/field/ReferenceManyField.tsx
> +// FIXME kept for backwards compatibility, unused, to be removed in v5
Shouldn't we add some JSDoc to warn that this component is deprecated?

2022-06-16 08:07 UTC, slax57 commented on packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
> +import React, { ReactElement, ReactNode } from 'react';
`ReactElement` is unused

2022-06-16 11:30 UTC, merged