[RFR] Add rich text input toolbar buttons
marmelab/react-admin pull request #7816
Opened 2022-06-11 14:11 UTC by bladx

As discussed in https://github.com/marmelab/react-admin/issues/7806, here is the PR to have both ColorButtons (including font and highlight color) and ImageButtons components for RichTextInput toolbar.

This is my first PR ever on any non-private repository, so please feel free to make me some feedbacks (english or french).

Plus, I noticed that the translation of all buttons (existing ones as well) do not exist, so even in french the titles are in english (default).

2022-06-11 15:12 UTC, bladx commented
I also just noticed that the toolbar is not responsive (missing the flex-wrap so the screen has an horizontal scroll bar).

2022-06-14 14:44 UTC, slax57 requested changes
Otherwise this is a really great contribution, thanks! :pray:

2022-06-14 14:44 UTC, slax57 commented on packages/ra-input-rich-text/src/buttons/ColorButtons.tsx
> +         */
This comment seems out of place, I think you can simply remove it

2022-06-14 19:16 UTC, bladx commented
Thanks for the kind feedback :)

2022-06-15 07:08 UTC, djhi commented
> Plus, I noticed that the translation of all buttons (existing ones as well) do not exist, so even in french the titles are in english (default).

Yes, thank you for this reminder. We're going to include english and french translations directly inside this package.

2022-06-15 07:11 UTC, djhi requested changes
Thanks a lot!

2022-06-15 07:11 UTC, djhi commented on packages/ra-input-rich-text/src/buttons/ColorButtons.tsx
> +export const ColorButtons = (props: Omit<ToggleButtonProps, 'value'>) => {
Would you mind moving this component at the top of the file ? We usually put first the most important things.

2022-06-16 08:25 UTC, slax57 approved these changes

2022-06-16 11:30 UTC, fzaninotto commented
Could you please fix the linter warnings?

2022-06-16 18:11 UTC, bladx commented
> Could you please fix the linter warnings?

Sorry I introduced them in my last code review commit and did not pay attention.
This should be alright now.

2022-06-17 08:49 UTC, fzaninotto approved these changes

2022-06-17 09:31 UTC, merged

2022-06-17 09:32 UTC, fzaninotto commented
Thanks!