Fix Hide `<Logout />` button if irrelevant.
marmelab/react-admin pull request #7842
Opened 2022-06-16 09:27 UTC by septentrion-730n

Closes https://github.com/marmelab/react-admin/issues/7839

Hide logout button if irrelevant.

2022-06-16 09:32 UTC, fzaninotto requested changes
It seems you're missing a unit test...

2022-06-16 09:32 UTC, fzaninotto commented on examples/simple/src/posts/PostList.tsx
> +            disableAuthentication
Please add a dedicated story instead of modifying the simple example to test it

2022-06-16 09:32 UTC, fzaninotto commented on packages/ra-ui-materialui/src/auth/Logout.tsx
> +    return !authenticated ? null : (
Use the *leave early* pattern instead of a ternary to make it clearer.

```jsx
if (!authenticated) return null;
```

2022-06-17 06:47 UTC, djhi requested changes

2022-06-17 06:47 UTC, djhi commented on packages/ra-ui-materialui/src/auth/Logout.spec.tsx
> +const MinimalAdmin = authProvider => {
It seems this is not used

2022-06-17 07:00 UTC, fzaninotto commented
Awesome! Just fix the linter warning and we're good to merge.

2022-06-17 07:25 UTC, slax57 requested changes

2022-06-17 07:25 UTC, slax57 commented on packages/ra-ui-materialui/src/auth/Logout.spec.tsx
> +export default { title: 'ra-ui-materialui/input/AutocompleteArrayInput' };
This is wrong + you don't need this unless you're writing a story

2022-06-17 07:36 UTC, slax57 approved these changes

2022-06-17 07:41 UTC, djhi approved these changes

2022-06-17 07:41 UTC, merged