[Doc] Add documentation for the Menu component
marmelab/react-admin pull request #7907
Opened 2022-06-28 22:01 UTC by fzaninotto

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/99944/176307822-4254f10b-9bbb-4a5c-994e-5af1fe451e6c.png">

2022-06-28 22:02 UTC, fzaninotto commented on docs/Layout.md
> -| `sidebar`   | Optional | `Component` | -        | A React component rendered at the side of the screen                  |
Even if the `sidebar` prop exists, I see no reason to use it, so let's make it a private API. `menu`, on the other side, is the preferred way to set a custom menu, so it should be documented.

2022-06-28 22:03 UTC, fzaninotto commented on packages/ra-ui-materialui/src/layout/Menu.tsx
> -        dense,
passed as rest props to the root component, a mui `MenuList`

2022-06-28 22:04 UTC, fzaninotto commented on packages/ra-ui-materialui/src/layout/Menu.tsx
> +Menu.Item = MenuItemLink;
This is technically a new feature but I think it's really minor, plus it's backwards compatible.

2022-06-28 22:05 UTC, fzaninotto commented on packages/ra-ui-materialui/src/layout/MenuItemLink.tsx
> -interface Props {
This change is required to let TS compile the Menu component after it reexports the MenuItem component.

2022-06-29 06:28 UTC, septentrion-730n approved these changes

2022-06-29 12:00 UTC, slax57 requested changes

2022-06-29 12:00 UTC, slax57 commented on docs/Admin.md
>      <Admin menu={Menu} dataProvider={simpleRestProvider('http://path.to.my.api')}>
```suggestion
    <Admin menu={MyMenu} dataProvider={simpleRestProvider('http://path.to.my.api')}>
```

2022-06-29 12:00 UTC, slax57 commented on docs/Layout.md
> +import { DashboardMenuItem, Menu, MenuItemLink } from 'react-admin';
```suggestion
import { Menu } from 'react-admin';
```

2022-06-29 12:00 UTC, slax57 commented on docs/Layout.md
> +But you don't have to use react-admin-s `<Menu>` component. In fact, the `<Layout menu>` component can render anything you like, e.g. using [MUI's `<Menu>` component](https://mui.com/material-ui/reac
```suggestion
But you don't have to use react-admin's `<Menu>` component. In fact, the `<Layout menu>` component can render anything you like, e.g. using [MUI's `<Menu>` component](https://mui.com/material-ui/react-menu/).
```

2022-06-29 12:00 UTC, slax57 commented on docs/Menu.md
> +You can create a custom menu component using react-admin's `<Menu>` and `<MenuItemLink>` components:
```suggestion
You can create a custom menu component using react-admin's `<Menu>` and `<Menu.Item>` components:
```

2022-06-29 12:00 UTC, slax57 commented on docs/Menu.md
> +Chech [the `<Menu.Item>` section](#menuitem) for more information.
```suggestion
Check [the `<Menu.Item>` section](#menuitem) for more information.
```

2022-06-29 12:00 UTC, slax57 commented on packages/ra-ui-materialui/src/layout/Menu.tsx
> +const Root = styled(MenuList, {
Isn't this a BC (for styling)?

2022-06-29 15:59 UTC, fzaninotto commented on packages/ra-ui-materialui/src/layout/Menu.tsx
> +const Root = styled(MenuList, {
it's not: the style is the same

2022-06-29 17:35 UTC, merged