Feat: Add ra-data-localforage package
marmelab/react-admin pull request #7959
Opened 2022-07-08 23:16 UTC by arimet

- [ ] Add `ra-data-localforage` to packages
- [ ] Update Makefile
- [ ] Update DataProviderList.md
- [ ] Update yarn.lock

![ra-application](https://user-images.githubusercontent.com/18294269/178080094-44615a30-fcb9-46c6-8c82-353ef353c115.gif)

2022-07-21 10:10 UTC, djhi requested changes
Nice!

2022-09-29 13:59 UTC, slax57 requested changes
Very minor comment. Otherwise, all good! :muscle:

2022-09-29 13:59 UTC, slax57 commented on packages/ra-data-localforage/src/index.ts
> +    const data = localForageData ? localForageData : defaultData;
```suggestion
    const data = localForageData ?? defaultData;
```

2022-09-29 14:13 UTC, slax57 approved these changes

2022-09-29 14:14 UTC, merged