Fix type error when queryOptions enable is set to false
marmelab/react-admin pull request #7987
Opened 2022-07-18 21:21 UTC by yanchesky

Fixes https://github.com/marmelab/react-admin/issues/7986

2022-07-19 07:27 UTC, djhi commented
Thanks for the error report and the PR! Would you mind trying to add a unit test for this case?

2022-07-21 06:46 UTC, djhi requested changes
Thanks!

2022-07-21 06:46 UTC, djhi commented on packages/ra-core/src/controller/list/useListController.ts
> +                (data === undefined || data.length === 0))
```suggestion
                (data == null || data.length === 0))
```

Might be even safer

2022-07-21 06:46 UTC, djhi commented on packages/ra-ui-materialui/src/list/datagrid/Datagrid.tsx
> +    if (data === undefined || data.length === 0 || total === 0) {
```suggestion
    if (data == null || data.length === 0 || total === 0) {
```
same

2022-07-21 06:56 UTC, djhi approved these changes
Thanks!

2022-07-21 07:44 UTC, yanchesky commented
Fixing failed unit test might be cumbersome 🤔. I have run it on the local machine and out of 10 tests on unchanged code:

- 4 times all tests passed
- 3 times "should notify if passed an error with a message that makes the authProvider throw" test failed
- 2 times "should take only last change in case of a burst of changes (case of inputs being currently edited)" test failed
- 1 time both 👆 failed

2022-07-26 05:36 UTC, yanchesky commented
I couldn't find the exact reason why the test `should take only last change in case of a burst of changes (case of inputs being currently edited)` sometimes fails. I've run this test only and it never failed. I suspect that it may be related to `react-router-dom` because right before the test fails, the error is raised `An update to HistoryRouter inside a test was not wrapped in act`. However, this error occurs even if the test passes so I'm not sure about this. 
However, knowing that I've come up with 2 solutions that make this test suite work. (By work I mean 10 test runs without any fail)

1. Create `history` and pass it to the CoreAdminContext component.
2. pass `disableSyncWithLocation` prop to the ListController component.

If that is ok with you I will make a commit fixing it.

 Snapshot of the mock requests that cause the test to fail:
```
"calls": Array [
    Array [
      "posts.listParams",
      Object {
        "filter": Object {},
        "order": "ASC",
        "page": 1,
        "perPage": 10,
        "sort": "id",
      },
    ],
    Array [
      "posts.listParams",
      Object {
        "filter": Object {
          "q": "hello",
        },
        "order": "ASC",
        "page": 1,
        "perPage": 10,
        "sort": "id",
      },
    ],
  ],
  ```

2022-07-27 14:03 UTC, ITopGun commented
Hi

2022-09-07 12:55 UTC, WiXSL commented
Could you resolve the conflict?

2022-09-08 08:30 UTC, yanchesky commented on packages/ra-core/src/controller/list/useListController.ts
> +            data == null ||
Thanks for the info. I will check it soon.

2022-09-22 14:18 UTC, yanchesky commented on packages/ra-core/src/controller/list/useListController.ts
> +            data == null ||
Changed it as you suggested and seems it's working now. However on my machine, some tests are failing, but they are failing on the master branch as well. 
unit test that fail: "should apply validation to both itself and its inner inputs"
e2e tests that fail: "should validate ArrayInput", and sometimes "should have tabbable menu items"

2022-09-23 07:52 UTC, fzaninotto approved these changes

2022-09-23 07:52 UTC, merged

2022-09-23 07:52 UTC, fzaninotto commented
Thanks!