Fix NumberInput state only changes on blur
marmelab/react-admin pull request #8033
Opened 2022-08-03 17:27 UTC by fzaninotto

Closes #7919

2022-08-03 17:29 UTC, fzaninotto commented
For some reason I don't understand, the `isTouched` attribute of the field state never changes, even though the 'touchedFields' from the form state is correct. We have the same problem on `TextInput`, so I believe the problem is in `useInput`, but I couldn't find it. 

I've validated that the problem doesn't come from react-hook-form (cf https://codesandbox.io/s/useformstate-forked-i4rwpe?file=/src/App.js)

2022-08-03 20:23 UTC, fzaninotto commented
OK, so the bug is actually only happening in tests, and it's a react-hook-form bug (https://github.com/react-hook-form/react-hook-form/issues/8786). I'll look for a workaround.

2022-08-03 21:11 UTC, septentrion-730n approved these changes

2022-08-04 07:03 UTC, djhi requested changes

2022-08-04 07:03 UTC, djhi commented on packages/ra-ui-materialui/src/input/NumberInput.spec.tsx
> +import { useFormContext, useWatch, useFormState } from 'react-hook-form';
eslint warning left

2022-08-04 07:23 UTC, djhi approved these changes

2022-08-04 07:54 UTC, merged