Fix Display notification on each submit if form has errors
marmelab/react-admin pull request #8057
Opened 2022-08-09 15:51 UTC by arimet

Replace useIsFormInvalid by useNotifyIsFormInvalid. 
Form now display notification on each submit if form has errors

https://user-images.githubusercontent.com/18294269/183698273-b016ae3d-2673-4bc0-a575-8d95de6d2171.mp4

2022-08-09 16:17 UTC, slax57 requested changes

2022-08-09 16:17 UTC, slax57 commented on packages/ra-core/src/form/useNotifyIsFormInvalid.ts
>  /**
You forgot to update the JSDoc

2022-08-09 16:55 UTC, septentrion-730n approved these changes

2022-08-10 08:14 UTC, slax57 approved these changes

2022-08-10 08:17 UTC, merged