add 'children' prop to Resources
marmelab/react-admin pull request #8079
Opened 2022-08-17 08:03 UTC by hiaselhans

React admin makes it fast to develop admin-interfaces with react.
However, when resources get more and more functions it is a bit unhandy to pass CustomRoutes to <Admin/>

This PR adds children as a property of resources and makes it possible to define the whole resource with custom sub-routes in a seperate typescript module:

``` tsx
import ListView from "./list";
import CustomRoute from "./customroute";

const MyResource = () => {
    return {
        list: ListView,
        children: <CustomRoute/>
    }
}
```

2022-08-22 08:15 UTC, fzaninotto commented
Thanks! Thats an interesting feature. 

As it's an enhancement, please rebase your PR against the `next` branch. 

Also, please document that feature and add some unit tests to make sure it works.

2022-08-30 14:24 UTC, WiXSL requested changes

2022-08-30 14:24 UTC, WiXSL commented on docs/CustomRoutes.md
> +import posts, {PostAnalytics} from './posts';
```suggestion
import posts, { PostAnalytics } from './posts';
```

2022-08-30 14:24 UTC, WiXSL commented on docs/CustomRoutes.md
> +            <Route path="analytics" element={<PostAnalytics/>}>
```suggestion
            <Route path="analytics" element={<PostAnalytics/>} />
```

2022-08-30 14:24 UTC, WiXSL commented on docs/CustomRoutes.md
>  import { Route } from "react-router-dom";
```suggestion
import { Route } from "react-router-dom";
import simpleRestProvider from 'ra-data-simple-rest';
```

2022-08-30 14:27 UTC, WiXSL requested changes
Thanks for your work!
You are still missing some test to prove that it works.

2022-09-01 18:23 UTC, hiaselhans commented on docs/CustomRoutes.md
>  import { Route } from "react-router-dom";
good catch!

2022-09-01 18:25 UTC, hiaselhans commented
thx @WiXSL !

i fixed the comments and added a test.
In my local env 3 unrelated tests are failing. However rebasing to next will flood the changeset in this PR

2022-09-02 08:59 UTC, fzaninotto approved these changes

2022-09-02 08:59 UTC, merged

2022-09-02 08:59 UTC, fzaninotto commented
Thanks!

2022-09-02 09:42 UTC, hiaselhans commented
Great, thank you!