Feat: add useGetRecordId documentation
marmelab/react-admin pull request #8107
Opened 2022-08-26 14:23 UTC by arimet

2022-08-26 15:38 UTC, djhi requested changes

2022-08-26 15:38 UTC, djhi commented on docs/useGetRecordId.md
> +`useGetRecordId` takes optional argument `recordId` if used inside a RecordContextProvider or if recordId can be guessed from the URL
```suggestion
`useGetRecordId` takes an optional `recordId` argument if used inside a `RecordContextProvider` or if `recordId` can be guessed from the URL
```

2022-08-29 16:07 UTC, slax57 requested changes

2022-08-29 16:07 UTC, slax57 commented on docs/useGetRecordId.md
> +`useGetRecordId` takes an optional `recordId` argument if used inside a `RecordContextProvider` or if `recordId` can be guessed from the URL
I'm not fond of the wording, which suggests the `recordId` argument is needed if used inside a `RecordContextProvider` or if `recordId` can be guessed from the URL, when it is actually the opposite.

2022-08-29 16:07 UTC, slax57 commented on docs/useGetRecordId.md
> +import { useListContext, useUnselect } from 'react-admin';
```suggestion
import { useGetRecordId } from 'react-admin';
```

2022-08-29 16:18 UTC, slax57 approved these changes

2022-08-30 16:04 UTC, fzaninotto requested changes

2022-08-30 16:04 UTC, fzaninotto commented on docs/navigation.html
> +  <li {% if page.path == 'useGetRecordId.md' %} class="active" {% endif %}><a class="nav-link" href="./useGetRecordId.html"><code>useGetRecordId</code></a></li>
It shouldn't be in this section, but rather in the Hooks section with useRecordContext

2022-08-31 08:30 UTC, fzaninotto approved these changes

2022-08-31 08:30 UTC, merged