Simpleformiterator-ui
marmelab/react-admin pull request #8124
Opened 2022-08-31 14:54 UTC by fzaninotto

2022-08-31 15:51 UTC, fzaninotto commented
The rationale for separating the remove button from the others in the first place was that it's destructive. Maybe we should keep that. Let me think again about the best compromise.

Back to WIP.

2022-08-31 16:09 UTC, slax57 commented
> The rationale for separating the remove button from the others in the first place was that it's destructive. Maybe we should keep that. Let me think again about the best compromise.
> 
> Back to WIP.

The different colors still make it clear enough, imho

2022-08-31 16:16 UTC, WiXSL commented
Woow this is great!

2022-09-01 08:38 UTC, fzaninotto commented
OK, I've made up my mind, this is back to RFR!

2022-09-01 13:32 UTC, WiXSL requested changes

2022-09-01 13:32 UTC, WiXSL commented on docs/SimpleFormIterator.md
> +In this example, the inputs for each row appear inline, with no helper text. This dense layout is adapted to arrays with many items. If you need more room, omit the `inline` prop to use the default d
```suggestion
In this example, the inputs for each row appear inline, with no helper text. This dense layout is adapted to arrays with many items. If you need more room, omit the `inline` prop to use the default layout, where each input is displayed in a separate row.
```

2022-09-01 13:40 UTC, WiXSL requested changes

2022-09-01 13:40 UTC, WiXSL commented on docs/SimpleFormIterator.md
> +In this example, the inputs for each row appear inline, with no helper text. This dense layout is adapted to arrays with many items. If you need more room, omit the `inline` prop to use the default d
Maybe is better `in the example above...` since this line is between two examples

2022-09-01 14:01 UTC, WiXSL requested changes
Looking at the `ArrayInput` stories, specially `Nested Inline`, the inputs look to dense.
And the separation line between items gets too close to the inputs

2022-09-01 16:12 UTC, fzaninotto commented
> Looking at the ArrayInput stories, specially Nested Inline, the inputs look to dense.
> And the separation line between items gets too close to the inputs

This story shows the "densest" density we can get. I still think it's not dense enough ;)

You can see the default density in the `Basic` story, and I don't think there is a density problem there. On the contrary, I find it barely usable because everything is so far from everything. 

![image](https://user-images.githubusercontent.com/99944/187962005-f60a7016-4e7d-452b-8930-893cce7a65c9.png)

As for the separator line, I'm not 100% satisfied with the result either, but the alternatives I tested were worse.

2022-09-01 16:16 UTC, WiXSL approved these changes

2022-09-02 09:39 UTC, slax57 approved these changes

2022-09-02 09:40 UTC, merged