Add support for getLocales in i18nProvider
marmelab/react-admin pull request #8143
Opened 2022-09-06 10:07 UTC by fzaninotto

Follows #7758

2022-09-06 10:14 UTC, djhi requested changes
:+1:

2022-09-06 10:14 UTC, djhi commented on docs/TranslationSetup.md
> +The second argument to the `polyglotI18nProvider` function is the default locale. The third is the list of supported locales - and is used by the `<LocaleMenuButton>` component to display a list of l
```suggestion
The second argument to the `polyglotI18nProvider` function is the default locale. The third is the list of supported locales - and is used by the [`<LocaleMenuButton>`](./LocalesMenuButton.md) component to display a list of languages.
```

2022-09-06 11:05 UTC, WiXSL requested changes

2022-09-06 11:05 UTC, WiXSL commented on examples/simple/src/i18nProvider.tsx
> +import frenchMessages from './i18n/fr';
Lint warning

2022-09-06 11:05 UTC, WiXSL commented on packages/ra-i18n-polyglot/src/index.ts
>      let locale = initialLocale;
Shouldn't we throw a warning if the `initialLocal` is not in the `availableLocales`? Maybe I'm nitpicking here

2022-09-06 11:10 UTC, WiXSL requested changes
`TranslationSetup.md` - line 152:
The specified anchor `using-specific-polyglot-features` is in the README of polyglot package, not above in the document.

This solution is all-or-nothing: you can't silence only *some* missing translation warnings. An alternative solution consists of passing a default translation using the `_` translation option, as explained in the **Using Specific Polyglot Features section(#using-specific-polyglot-features)** above.

2022-09-08 08:06 UTC, djhi approved these changes

2022-09-08 08:48 UTC, slax57 approved these changes

2022-09-08 12:32 UTC, WiXSL approved these changes

2022-09-08 12:53 UTC, merged