Fix localStorageStore.reset() does not remove all items
marmelab/react-admin pull request #8161
Opened 2022-09-14 10:18 UTC by fzaninotto

I have a unit test for it in the configurable branch - I haven't added ift here to avoi!d conflicts

2022-09-14 10:20 UTC, fzaninotto commented on packages/ra-core/src/store/localStorageStore.ts
> -                if (storage.key(i)?.substring(0, prefixLength) === prefix) {
The problem was that once you remove an item, the index of the next item decreases... So `storage.key(i)` 'jumps' one item each time we delete one.

2022-09-14 10:23 UTC, slax57 requested changes

2022-09-14 10:23 UTC, slax57 commented on packages/ra-core/src/store/localStorageStore.ts
> +            });
I agree with the analysis and the fix
But why did you also remove the `if (storage.key(i)?.substring(0, prefixLength) === prefix)` part? This should be kept IMO

2022-09-15 07:25 UTC, slax57 approved these changes

2022-09-15 07:25 UTC, merged