[Doc] Fix FormDataConsumer usage example
marmelab/react-admin pull request #8189
Opened 2022-09-22 13:41 UTC by WiXSL

Fixes #8179

2022-09-22 13:57 UTC, fzaninotto requested changes

2022-09-22 13:57 UTC, fzaninotto commented on docs/Inputs.md
> +**Important**: By default `react-hook-form` submits values of unmounted input components, so if you don't want this behaivour you can set `shouldUnregister` prop to `true` in the form
I'd put the shouldUnregister directly in the first example (L513) instead of duplicating it. then, you can explain why it's necessary.

2022-09-22 15:01 UTC, fzaninotto commented on docs/Inputs.md
> +**Important**: By default `react-hook-form` submits values of unmounted input components, to prevent this from happen in the above example, `shouldUnregister` prop was set to `true` in the `<SimpleFo
```suggestion
**Note**: By default, `react-hook-form` submits values of unmounted input components. In the above example, the `shouldUnregister` prop of the `<SimpleForm>` component prevents that from happening. That way, when end users hide an input, its value isn't included in the submitted data.
```

2022-09-22 16:18 UTC, merged

2022-09-23 14:29 UTC, afilp commented
I think that this may be an issue when hiding/showing filters too. At least this is what happened with a custom filter of mine when pressing the "clear" ("x") button. The query was still sending the filter value.

2022-09-23 15:24 UTC, fzaninotto commented
You'll have to write your own filter form.

https://marmelab.com/react-admin/FilteringTutorial.html#building-a-custom-filter