Fix: FormTab not turning red after ArrayInput global validation error
marmelab/react-admin pull request #8198
Opened 2022-09-26 11:24 UTC by thibault-barrat

Fixes #8190 

https://user-images.githubusercontent.com/41492953/192263783-f72b96ec-c706-4d4f-8298-3747dc924704.mov

2022-09-26 11:27 UTC, arimet approved these changes

2022-09-26 11:30 UTC, WiXSL approved these changes

2022-09-26 15:28 UTC, fzaninotto requested changes
The code seems fine. Could you please add a story and a unit test for the fix?

2022-09-27 09:22 UTC, thibault-barrat commented
> The code seems fine. Could you please add a story and a unit test for the fix?

I added the story and the test

2022-09-27 13:50 UTC, slax57 approved these changes

2022-09-27 14:53 UTC, merged