[Doc] Improve AutocompleteArrayInput doc
marmelab/react-admin pull request #8322
Opened 2022-10-27 13:36 UTC by fzaninotto

2022-10-27 14:09 UTC, WiXSL requested changes

2022-10-27 14:09 UTC, WiXSL commented on docs/AutocompleteArrayInput.md
> +You can opt-out of this translation by setting [the `translateChoice` prop](#translatechoice) to `false`.
#translatechoice is missing

2022-10-27 15:41 UTC, fzaninotto commented on docs/AutocompleteArrayInput.md
> +You can opt-out of this translation by setting [the `translateChoice` prop](#translatechoice) to `false`.
Right, fixed

2022-10-28 09:07 UTC, slax57 requested changes

2022-10-28 09:07 UTC, slax57 commented on docs/AutocompleteArrayInput.md
> +    { id: 'u003', label: 'myroot.roles.u003' },
```suggestion
    { id: 'admin', name: 'myroot.roles.admin' },
    { id: 'u001', name: 'myroot.roles.u001' },
    { id: 'u002', name: 'myroot.roles.u002' },
    { id: 'u003', name: 'myroot.roles.u003' },
```

2022-10-28 09:07 UTC, slax57 commented on docs/AutocompleteArrayInput.md
> +<AutocompleteArrayInput source="tags" choices={choices} translateChoice={false}/>
```suggestion
<AutocompleteArrayInput source="roles" choices={choices} translateChoice={false}/>
```

2022-10-28 09:08 UTC, fzaninotto commented on docs/AutocompleteArrayInput.md
> +| `debounce`                 | Optional | `number`              | `250`                    | The delay to wait before calling the setFilter function injected when used in a ReferenceArray Input.
That's on purpose, to let the component name wrap and not force the table layout to go beyond the content width

2022-10-28 09:09 UTC, fzaninotto commented on docs/AutocompleteArrayInput.md
> +| `shouldRender Suggestions` | Optional | `Function`            | `() => true`             | A function that returns a `boolean` to determine whether or not suggestions are rendered.  |
Same

2022-10-28 09:09 UTC, fzaninotto commented on docs/AutocompleteArrayInput.md
> +| `setFilter`                | Optional | `Function`            | `null`                   | A callback to inform the `searchText` has changed and new `choices` can be retrieved based on this `search
same

2022-10-28 09:37 UTC, merged