Add <ReferenceOneField queryOptions> support
marmelab/react-admin pull request #8348
Opened 2022-11-03 11:58 UTC by fzaninotto

2022-11-03 16:28 UTC, WiXSL approved these changes

2022-11-03 16:30 UTC, WiXSL requested changes

2022-11-03 16:30 UTC, WiXSL commented on packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx
> +        total: number;
```suggestion
        total?: number;
```

2022-11-03 16:34 UTC, WiXSL requested changes

2022-11-03 16:34 UTC, WiXSL commented on packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
> +        total: number;
```suggestion
        total?: number;
```

2022-11-03 17:19 UTC, fzaninotto commented on packages/ra-core/src/controller/field/useReferenceOneFieldController.tsx
> +        total: number;
TypeScript disagrees

2022-11-03 17:20 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ReferenceOneField.tsx
> +        total: number;
Same

2022-11-04 09:48 UTC, slax57 approved these changes

2022-11-04 09:48 UTC, merged