Fix authProvider hooks support for redirectTo: absolute URL
marmelab/react-admin pull request #8382
Opened 2022-11-10 18:01 UTC by fzaninotto

2022-11-11 16:56 UTC, WiXSL requested changes

2022-11-11 16:56 UTC, WiXSL commented on packages/ra-core/src/auth/useLogout.ts
> +                const redirectToParts = finalRedirectTo.split('?');
It throws an error here in simple project with:
```js
//authProvider
{
   logout: () => {
         return Promise.resolve({ redirectTo: 'https://...' }); 
        //return Promise.resolve({ redirectTo: false }); // as well
    },
}
```

2022-11-12 14:23 UTC, WiXSL approved these changes

2022-11-14 09:22 UTC, slax57 approved these changes

2022-11-14 09:22 UTC, merged