Add ability to reorder fields in DatagridConfigurable and SimpleFormConfigurable
marmelab/react-admin pull request #8416
Opened 2022-11-21 17:26 UTC by fzaninotto

2022-11-22 12:18 UTC, WiXSL approved these changes

2022-11-22 13:39 UTC, WiXSL requested changes
I believe you forgot to update the screencast.
And maybe a few tests wouldn't hurt 😃

2022-11-22 17:32 UTC, fzaninotto commented
Screencasts added. As for the tests, they are left as an exercise for the reader ;)

2022-11-22 17:41 UTC, fzaninotto commented on packages/ra-ui-materialui/src/preferences/FieldsSelector.tsx
> +    };
Fun fact: this method was almost entirely written by gitHub Copilot!

2022-11-22 18:20 UTC, WiXSL approved these changes

2022-11-23 16:12 UTC, slax57 requested changes

2022-11-23 16:12 UTC, slax57 commented on packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.tsx
> +                .filter(column => !omit?.includes(column.source))
I don't think you should use `omit` here. Reordering the columns shouldn't re-apply the omit param IMO.

2022-11-23 16:12 UTC, slax57 commented on packages/ra-ui-materialui/src/preferences/FieldsSelector.tsx
> +                .filter(field => !omit?.includes(field.source))
same

2022-11-28 10:52 UTC, slax57 approved these changes

2022-11-28 10:55 UTC, merged