Fix broken referenceKey prop on SelectColumnsButton
marmelab/react-admin pull request #8432
Opened 2022-11-24 15:54 UTC by wcoppens

Fixes #8431

This commit fixes the broken referenceKey prop for the SelectColumnsButton.

2022-11-24 20:39 UTC, WiXSL commented
Test are failing

2022-11-24 20:39 UTC, WiXSL requested changes
Test are failing

2022-11-24 20:40 UTC, WiXSL requested changes

2022-11-24 20:40 UTC, WiXSL commented on packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.tsx
> +        `preferences.${props.preferenceKey}` || `preferences.${resource}.datagrid`;
Fix lint warning

2022-11-25 12:33 UTC, wcoppens commented
@WiXSL My bad, updated the codestyle and added some extra tests to verify working.

2022-11-25 13:19 UTC, WiXSL requested changes

2022-11-25 13:19 UTC, WiXSL commented on packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.spec.tsx
> +    it('should render a datagrid with columns using the given preference key', async () => {
Move this test inside the already defined describe function above

2022-11-25 14:23 UTC, WiXSL approved these changes

2022-11-27 20:34 UTC, fzaninotto requested changes

2022-11-27 20:34 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/datagrid/SelectColumnsButton.tsx
> +        : `preferences.${resource}.datagrid`;
For consistency, please use the same syntax as in `DatagridConfigurable`:

```jsx
    const finalPreferenceKey = preferenceKey || `${resource}.datagrid`;

    const [availableColumns, setAvailableColumns] = useStore<
        ConfigurableDatagridColumn[]
    >(`preferences.${finalPreferenceKey}.availableColumns`, []);

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const [_, setOmit] = useStore<string[]>(
        `preferences.${finalPreferenceKey}.omit`,
        omit
    );
```

2022-12-02 13:59 UTC, fzaninotto commented
Sorry, needs rebase

2022-12-08 09:44 UTC, slax57 requested changes
Could you please also apply the changes regarding the `props` type that are suggested in #8479
- typing `props` with `SelectColumnsButtonProps` 
- using the `sanitizeRestProps` function

Also, there are 2 linter warnings you need to fix:
![2022-12-08_10-42](https://user-images.githubusercontent.com/14542336/206413590-236a2585-de32-4d9c-90f8-5de8cf77fa62.png)

Thanks

2022-12-08 10:05 UTC, septentrion-730n commented
Hi @wcoppens 

I did not see your PR, sorry about that!

2022-12-08 14:36 UTC, slax57 approved these changes
Thanks!

2022-12-08 14:37 UTC, merged