[Doc] Improve instructions for setting up a redirection url for third-party auth
marmelab/react-admin pull request #8494
Opened 2022-12-12 14:50 UTC by fzaninotto

Refs #8457

2022-12-12 15:21 UTC, djhi requested changes

2022-12-12 15:21 UTC, djhi commented on docs/AuthProviderWriting.md
> +This method is used when integrating a third-party authentication providers such as [Auth0](https://auth0.com/). React-admin provides a route at the `/auth-callback` path, to be used as the callback
```suggestion
This method is used when integrating a third-party authentication provider such as [Auth0](https://auth0.com/). React-admin provides a route at the `/auth-callback` path, to be used as the callback URL in the authentication service. After logging in using the authentication service, users will be redirected to this route. The `/auth-callback` route calls the `authProvider.handleCallback` method on mount. 
```

2022-12-13 11:05 UTC, slax57 requested changes

2022-12-13 14:12 UTC, slax57 approved these changes

2022-12-13 14:13 UTC, merged