Add disableAuthentication paragraph on the <Show> documentation
marmelab/react-admin pull request #8565
Opened 2023-01-10 19:49 UTC by septentrion-730n

2023-01-10 19:55 UTC, WiXSL requested changes

2023-01-10 19:55 UTC, WiXSL commented on docs/Show.md
> +By default, the `<Show>` component will automatically redirect the user to the login page if the user is not authenticated. If you want to disable this behavior and allow anonymous access to a creati
```suggestion
By default, the `<Show>` component will automatically redirect the user to the login page if the user is not authenticated. If you want to disable this behavior and allow anonymous access to a show page, set the `disableAuthentication` prop to `true`.
```

2023-01-10 19:55 UTC, WiXSL commented on docs/Show.md
> +By default, the `<Show>` component will automatically redirect the user to the login page if the user is not authenticated. If you want to disable this behavior and allow anonymous access to a creati
😃

2023-01-11 06:59 UTC, fzaninotto approved these changes

2023-01-11 06:59 UTC, merged