Fix NumberInput should support entering a decimal number with a transitory invalid value
marmelab/react-admin pull request #8610
Opened 2023-01-30 15:16 UTC by slax57

Fix https://github.com/marmelab/react-admin/issues/8593

2023-01-30 15:29 UTC, fzaninotto requested changes

2023-01-31 08:56 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/NumberInput.tsx
> +        setValue(value => (value !== stringValue ? stringValue : value));
OK, understood: the use case is: a user enters "0.0" and blurs. The form value is "0", but the displayed value is different - and this is misleading. Updating the displayed value based on the form value helps the user know what's going to be submitted.

2023-01-31 08:56 UTC, fzaninotto approved these changes

2023-01-31 08:56 UTC, merged

2023-02-02 09:02 UTC, slax57 commented on packages/ra-ui-materialui/src/input/NumberInput.tsx
> +        setValue(value => (value !== stringValue ? stringValue : value));
Yes exactly :slightly_smiling_face: