add Postgres data provider
marmelab/react-admin pull request #8611
Opened 2023-01-30 15:29 UTC by mingfang

2023-01-30 15:30 UTC, fzaninotto requested changes

2023-01-30 15:30 UTC, fzaninotto commented on docs/DataProviderList.md
> +* **[Postgres](https://github.com/mingfang/ra-postgres-dataprovider)
The syntax isn't correct: the list shows first the name of the backend in bold, then the name of the adapter. Could you please fix it?

2023-01-30 15:32 UTC, fzaninotto commented
There is something I don't understand: node-pg is a server-side module. React-admin is supposed to work with an API. Does that restrict the usage of your data provider to server-side rendered apps?

2023-01-30 15:46 UTC, mingfang commented
> There is something I don't understand: node-pg is a server-side module. React-admin is supposed to work with an API. Does that restrict the usage of your data provider to server-side rendered apps?

node-pg is server side only.

To work on the client side, then the combination of 
Neon WSProxy https://github.com/neondatabase/wsproxy and
Neon Serverless(pg drop-in replacement) https://github.com/neondatabase/serverless

The flow would be React-Admin(client side) -websocket-> wsproxy(server side) -> Postgres

2023-01-30 15:51 UTC, fzaninotto commented
Understood. You probably need to mention that in your Readme though ;)

2023-01-30 16:15 UTC, mingfang commented
> 



> Understood. You probably need to mention that in your Readme though ;)

I added this information to my Readme as suggested.

2023-01-30 17:17 UTC, mingfang commented
> There is something I don't understand. Does that mean that the credentials to the Posgres database have to be prensent in the dataProvider, i.e. in the JS code sent to the client? If that's the case, this is highly vulnerable to all sorts of attacks and I can't see any real-life scenario.

The sample code hardcoded the credentials to keep the code simple as a demonstration only.
The Postgres credentials should be secured the same way as any other RA providers.

2023-01-30 17:28 UTC, mingfang commented
> 



> Then you should update your documentation to show a secure-by-default example.

I moved the URL to an .env.sample file

2023-01-31 08:48 UTC, fzaninotto commented
> I moved the URL to an .env.sample file

This doesn't change the fact that the connection string will be bundled in the client JS. 

All in all, I don't see any secure usage for this package, and I prefer not in include it in the list of available data providers.

2023-01-31 08:48 UTC, closed without merging