Improve AppBar Customization
marmelab/react-admin pull request #8681
Opened 2023-02-24 09:12 UTC by fzaninotto

## Problem

Adding new buttons or a search engine to the appBar is cumbersome

## Solution

- [x] Add a `<TitlePortal>` component to avoid copy/pasting a large `<Typography>` from the doc
- [x] Add a `toolbar` prop to let users override the default toolbar
- [x] Fix styling glitches
- [x] Add Storybook
- [x] Add a dedicated doc chapter
- [x] Include screenshots in the doc

2023-02-24 09:44 UTC, djhi requested changes
:muscle:

2023-02-24 09:44 UTC, djhi commented on docs/AppBar.md
> +React-admin's `<AppBar>` renders a MUI `<AppBar>`, which supports a `color` prop top set the app bar color depending on the theme. By defaulmt, the app bar color is set to the `secondary` theme color
```suggestion
React-admin's `<AppBar>` renders a MUI `<AppBar>`, which supports a `color` prop top set the app bar color depending on the theme. By default, the app bar color is set to the `secondary` theme color.
```

2023-02-24 09:44 UTC, djhi commented on docs/AppBar.md
> +By defautl, the `<AppBar>` renders two buttons in addition to the user menu: the language menu and the refresh button.
```suggestion
By default, the `<AppBar>` renders two buttons in addition to the user menu: the language menu and the refresh button.
```

2023-02-24 09:44 UTC, djhi commented on docs/AppBar.md
> +The appearance of the user menu depends on the return value of `authProvider.getIdentity()`. The user menu icon renders an anonymous avatar, or the `avatar` property of the identity object if present
```suggestion
The content of the user menu depends on the return value of `authProvider.getIdentity()`. The user menu icon renders an anonymous avatar, or the `avatar` property of the identity object if present. If the identity object contains a `fullName` property, it is displayed after the avatar. 
```

2023-02-24 10:47 UTC, djhi approved these changes

2023-02-26 17:40 UTC, fzaninotto commented
Switching to RFR

2023-02-27 08:13 UTC, djhi approved these changes

2023-02-27 08:13 UTC, merged

2023-03-24 17:10 UTC, cduran-seeri commented on docs/Reference.md
> +* [<`TitlePortal>`](./AppBar.md#children)
Thanks! Found a typo, I'm not sure if this is critical
```
<`Title>` to `<Title>`
<`TitlePortal>` to `<TitlePortal>`
```