Use Vite for the CRM demo
marmelab/react-admin pull request #8696
Opened 2023-03-02 16:39 UTC by djhi

2023-03-03 15:57 UTC, slax57 requested changes
Changes look good :slightly_smiling_face: 

However I'm having a weird issue when running the CRM demo locally.
The 'loading state' spinner in the AppBar keeps spinning for a while, and then I get this error in the console:

```
Unknown method
overrideMethod	@	react_devtools_backend.js:2655
onError	@	query.js:356
reject2	@	retryer.js:67
(anonymous)	@	retryer.js:132
```

Seems to be related to the react devtools, which is weird, but I don't see it in the 'prod' demo, and I tried to refresh the page and all, still same result.

Do you see it on your end too?

2023-03-03 16:11 UTC, slax57 commented
FI it also happens when running `yarn build` and `yarn preview`

2023-03-03 16:31 UTC, djhi commented
This problem already exists on the deployed demo: https://marmelab.com/react-admin-demo/

2023-03-09 14:09 UTC, slax57 approved these changes

2023-03-09 14:19 UTC, merged