[Doc] Improve `<Confirm>` documentation
marmelab/react-admin pull request #8711
Opened 2023-03-06 21:07 UTC by fzaninotto

2023-03-07 09:22 UTC, slax57 requested changes

2023-03-07 09:22 UTC, slax57 commented on docs/Confirm.md
> +React-admin has built-in buttons to delete a record and ask for confirmation before deleting ([`<DeleteWithConfirmButton>`](./Buttons.md#deletewithconfirmbutton)). But yon can also use the `<DeleteBu
```suggestion
React-admin has built-in buttons to delete a record and ask for confirmation before deleting ([`<DeleteWithConfirmButton>`](./Buttons.md#deletewithconfirmbutton)). But you can also use the `<DeleteButton>` with `mutationMode="pessimistic"` to get the same result:
```

2023-03-07 09:26 UTC, fzaninotto commented on docs/Confirm.md
> +React-admin has built-in buttons to delete a record and ask for confirmation before deleting ([`<DeleteWithConfirmButton>`](./Buttons.md#deletewithconfirmbutton)). But yon can also use the `<DeleteBu
You're right, this is confusing. I should not mention `<DeleteWithConfirm>` at all.

2023-03-08 08:32 UTC, slax57 approved these changes

2023-03-08 08:35 UTC, merged