[Doc] Add documentation for `fetchJson`
marmelab/react-admin pull request #8712
Opened 2023-03-07 14:29 UTC by slax57

2023-03-07 14:49 UTC, djhi requested changes

2023-03-07 14:49 UTC, djhi commented on docs/DataProviders.md
> +For instance, the `simpleRestProvider` function accepts an HTTP client function as second argument. By default, it uses react-admin's [`fetchUtils.fetchJson()`](./fetchJson.md) function as HTTP clien
```suggestion
For instance, the `simpleRestProvider` function accepts an HTTP client function as its second argument. By default, it uses react-admin's [`fetchUtils.fetchJson()`](./fetchJson.md) function as the HTTP client. It's similar to the HTML5 `fetch()`, except it handles JSON decoding and HTTP error codes automatically.
```

2023-03-07 14:49 UTC, djhi commented on docs/fetchJson.md
> +React-admin includes a `fetchJson` utility function to make HTTP calls. It's a wrapper around the browser's `fetch` function, which adds the following features:
```suggestion
React-admin includes a `fetchJson` utility function to make HTTP calls. It's a wrapper around the browser's `fetch` function, that adds the following features:
```

2023-03-07 14:49 UTC, djhi commented on docs/fetchJson.md
> +import simpleRestProvider from 'ra-data-simple-rest';
```suggestion
import simpleRestProvider from 'ra-data-simple-rest';
import { PostList } from './posts';
```

2023-03-07 14:49 UTC, djhi commented on docs/fetchJson.md
> +**Tip:** `fetchJson` is included in the `fetchUtils` member of the `react-admin` package.
```suggestion
**Tip:** `fetchJson` is included in the `fetchUtils` object exported by the `react-admin` package.
```

2023-03-07 14:49 UTC, djhi commented on docs/fetchJson.md
> +import simpleRestProvider from 'ra-data-simple-rest';
```suggestion
import simpleRestProvider from 'ra-data-simple-rest';
import { PostList } from './posts';
```

2023-03-07 14:49 UTC, djhi commented on packages/ra-core/src/dataProvider/fetch.ts
> + * Utility function to make HTTP calls. It's similar to HTML5 `fetch()`, except it handles JSON decoding and HTTP error codes automatically.
```suggestion
 * Utility function to make HTTP calls. It's similar to the HTML5 `fetch()`, except it handles JSON decoding and HTTP error codes automatically.
```

2023-03-07 20:48 UTC, fzaninotto commented on docs/fetchJson.md
> +### Parameters
We don't need 2 levels of heading here. Make it a top-level heading (`###` => `##`)

2023-03-08 08:45 UTC, djhi approved these changes

2023-03-08 09:15 UTC, merged