Fix custom redirect in `Create` and `Edit` with `warnWhenUnsavedChanges`
marmelab/react-admin pull request #8839
Opened 2023-04-18 09:32 UTC by slax57

Fix https://github.com/marmelab/react-admin/issues/8819

2023-04-18 20:12 UTC, fzaninotto requested changes

2023-04-18 20:12 UTC, fzaninotto commented on packages/ra-core/src/controller/edit/useEditController.ts
> +                    if (shouldRedirectAfterUpdate) {
You should add the same comment as for the useCreateController here, otherwise it's unclear why you need to do that.

2023-04-18 20:12 UTC, fzaninotto commented on packages/ra-core/src/controller/create/useCreateController.ts
> +                        // We need to wait for the 'isSubmitting' for state to be updated
I don't understand that comment.

2023-04-24 14:14 UTC, slax57 commented
What fixed the issue in my PR was probably luck, because I am avoiding the unfavorable case of a race condition, but not fixing the race condition itself.

Basically the issue is the following:

`useAugmentedForm` defines the form's `handleSubmit` fn as:
```ts
        async (values, event) => {
            // ...
            let errors = await saveContext.save(values, event);
            // ...
        }
```

The `saveContext.save` is defined by the Edit/Create controller as:
```ts
const [update] = useUpdate(resource, recordCached, {
        ...otherMutationOptions,
        mutationMode,
        returnPromise: mutationMode === 'pessimistic',
});

const save = useCallback(
    data => 
        async data => {
            const mutate = getMutateWithMiddlewares(update);
            await mutate(
                resource,
                { id, data, meta: mutationMeta },
                {
                    onSuccess: async data => {
                        redirect(redirectTo, resource, data.id, data);
                    }
                }
        }
);
```

Which means `save` will call `redirect()` before resolving.

However, in `useWarnWhenUnsavedChanges`, we define:

```ts
        let unblock = navigator.block((tx: Transition) => {
            if (
                !isSubmitting &&
                (isSubmitSuccessful ||
                    window.confirm(translate('ra.message.unsaved_changes')))
            ) {
                unblock();
                tx.retry();
            }
        });
```

Which means the navigation **will be blocked** when `isSubmitting==true`.

This is why the redirect fails silently, it is actually blocked by `useWarnWhenUnsavedChanges`, which thinks the form is still submitting, because the `handleSubmit` fn RA provides to RHF has not resolved yet.

My fix was basically delaying the call to `redirect()` a bit later, but it still does not depend on the RHF's form submitting status, so it is probably not robust enough...

So far I can't think of a good way to fix this. I to put more thinking into this...

2023-04-26 15:23 UTC, slax57 commented
Superseded by https://github.com/marmelab/react-admin/pull/8859

2023-04-26 15:23 UTC, closed without merging