Update tutorial to use create-react-admin
marmelab/react-admin pull request #8881
Opened 2023-05-04 08:40 UTC by djhi

2023-05-04 09:29 UTC, fzaninotto requested changes
Neat, the tutorial is now easier to start!

2023-05-04 09:29 UTC, fzaninotto commented on docs/CreateReactAdmin.md
> +
Could you add a screencast?

2023-05-05 12:00 UTC, djhi commented on docs/CreateReactAdmin.md
> +
Done

2023-05-09 11:13 UTC, fzaninotto approved these changes

2023-05-09 11:13 UTC, merged