Fix custom input's onChange handlers should have access to updated context value
marmelab/react-admin pull request #8903
Opened 2023-05-11 20:04 UTC by WiXSL

I'm updating a project from ra-v3 to ra-v4 where the value of change inputs is accessed from within the onChange / onBlur event handler, and it doesn't have the updated value.

I found out that :
In react-admin **v3** inputs run custom event handlers **after** react-final-form ones.
In react-admin **v4** inputs run custom event handlers **before** react-hook-form ones.

So, changing this order of execution to match ra-v3 allows `useFormContext().getValues()` to have the latest value inside the event handlers.
It doesn't seem to have any other effect.

2023-05-12 08:31 UTC, slax57 commented
Hi! Thanks for submitting this! :slightly_smiling_face: 

However, I'm not sure I understand, though. You can still access the newer value of the input via `e.target.value`, right? So why would you need to access it via `useFormContext().getValues()`? What is the benefit? :thinking:

2023-05-12 13:00 UTC, WiXSL commented
The benefit is to grab all the values of the form at once to give it to a process, including the one that just have been changed, without having to differentiate that one by grab it from another place.
I have a lot of code that takes all the values from the event handlers like that, and I have to go handler by handler taking the value that has changed from e.target.value plus the rest of the form values.

2023-05-12 14:41 UTC, slax57 commented
I see. Thanks for the clarifications. :slightly_smiling_face: 
I was wondering, because this change is technically a BC.
However I can't think of any scenario where this would be problematic, so I would be OK to accept the change.
@djhi  @fzaninotto  what do you think? Can you think of a scenario where this might break things?

2023-05-12 14:42 UTC, slax57 approved these changes

2023-05-15 11:15 UTC, fzaninotto requested changes
I agree that this is a welcome change, however I'd prefer that you PR against `next`. As it may break things in corner cases, we need to prevent that from happening in a bug fix release. 

Also, the order change was introduced by @djhi in 9dfaf4e6357864e9435c2a8eb369655e89b9869a. I wonder it you have any recollection of why you didi so?

2023-05-15 11:15 UTC, fzaninotto commented on packages/ra-core/src/form/useInput.spec.tsx
> +        };
This one should probably be named `setXXX`, it's not a getter

2023-05-15 13:42 UTC, closed without merging