[WIP] Replace rowStyle with rowSx
marmelab/react-admin pull request #8925
Opened 2023-05-17 18:39 UTC by zhujinxuan

2023-05-17 21:12 UTC, djhi requested changes
Thanks! This is nice but please make it an alternative to `rowStyle`, not a replacement.

2023-05-25 14:56 UTC, zhujinxuan commented
Sorry, I was busy this week. I will make the change next Tuesday.

2023-06-13 15:03 UTC, zhujinxuan commented
Sorry for the delay, I have had a back pain in last few weeks that kept me away from computer. I have add `rowStyle` back to the document, to the `ra-ui-materialui` and to `Datagrid.stories.tsx`. But I keep the `rowSx` change for the demo because I think it would be better if the code style of demo is more consistent with mui. 

Please let me know if there is any thing needed to be updated about this PR.

2023-06-13 15:44 UTC, djhi commented on docs/Datagrid.md
> +You can customize the styles of rows and cells in `<Datagrid>` (applied to the `<DatagridRow>` element) based on the record, thanks to the `rowSx` prop, which expects a function. React-admin calls th
```suggestion
You can customize the styles of rows and cells in `<Datagrid>` (applied to the `<DatagridRow>` element) based on the record, thanks to the `rowSx` prop, which expects a function. React-admin calls this function for each row, passing the current record and index as arguments. The function should return a Material UI [`sx`](https://mui.com/system/getting-started/the-sx-prop/), which react-admin uses as a `<TableRow sx>` prop. 
```

2023-06-13 15:46 UTC, djhi commented on docs/SimpleList.md
> +This optional prop should be a function, which gets called for each row. It receives the current record and index as arguments, and should return a style object. The style object is applied to the `<
```suggestion
This optional prop should be a function, which gets called for each row. It receives the current record and index as arguments, and should return a Material UI [`sx`](https://mui.com/system/getting-started/the-sx-prop/). The style object is applied to the `<ListItem>` `sx` prop.
```

2023-06-14 08:11 UTC, djhi approved these changes
Great! Thanks!

2023-06-14 08:20 UTC, mshd approved these changes

2023-06-14 17:31 UTC, zhujinxuan commented
Hi, @fzaninotto . I made this change because there is no way to style a single cells. We can add `sx` to `Datagrid`, but it cannot style single cell because cell classes in each row are the same. Currently, the only way to style a single cell is to use `nth` two times, which is not intuitive.

2023-06-16 07:45 UTC, djhi commented
I actually think `rowSx` to be pretty intuitive as you define the styles according to the record at the same place whereas `rowClass` would require you to check two different props to ensure you applied the correct className for the conditions you check on the record.

2023-07-03 12:42 UTC, slax57 commented
Personally, I'm also in favor of adding the `rowSx` prop.
Besides, this feature allows for things like setting the style of the row directly depending on the record, for instance using a numeric value (like a percentage) from the record directly to compute a bg or fg color.
This would be way harder to do with `rowClass`.

2023-08-10 14:44 UTC, fzaninotto commented
Seems I'm in minority, so we'll go for it! I'll just deprecate the `rowStyle` property in another Pr to avoid confusion. 

Thanks for your contribution!

2023-08-10 14:44 UTC, merged