Automatically convert TS examples to JS
marmelab/react-admin pull request #9005
Opened 2023-06-14 07:59 UTC by djhi

Done client side and only when needed.
I compared locally with the previous docs and didn't notice any difference even with CPU throttling x6 on slow 3G

## How to test

- Open AccordionForm.md
- Click on the AccordionForm.Panel section 
- Scroll down
- The first snippet is bi-lingual
<img width="1494" alt="image" src="https://github.com/marmelab/react-admin/assets/99944/739e21be-c745-40af-bc63-755b19b16a38">

2023-06-14 16:36 UTC, fzaninotto commented
When I click on a language tab, the screen "jumps". Can we avoid that?

2023-06-14 16:37 UTC, fzaninotto commented
Also, it seems the indentation differs between JS and TS. Can we make it consistent?

2023-06-14 16:55 UTC, djhi commented
> Also, it seems the indentation differs between JS and TS. Can we make it consistent?

I'm afraid we have inconsistent indentation everywhere so we'd have to apply the same everywhere as well

2023-06-15 13:08 UTC, slax57 requested changes
Code seems good.

BUT, I saw 2 issues:
- Once you switch to TSX, **all** JSX code snippets disappear! (it can be seen in `AccordionForm.md`)
- New lines are not preserved when they are in the JSX code. Example in the code below taken from `Tutorial.md`:

```tsx
// in src/App.tsx
import { Admin, Resource, ListGuesser, EditGuesser, ShowGuesser } from 'react-admin';
import { dataProvider } from './dataProvider';

export const App = () => (
    <Admin dataProvider={dataProvider}>

    </Admin>
);
```

The new lines between `<Admin>` and `</Admin>` are not preserved.

2023-06-15 13:23 UTC, djhi commented on docs/css/style-v17.css
> +}
As discussed with Francois, it's actually unnecessary. @fzaninotto Did I get that right?

2023-06-15 13:23 UTC, djhi commented on docs/js/ra-doc-exec.js
> +const builtJSCodeBlocksFromTS = async () => {
Typo

2023-06-15 15:51 UTC, slax57 approved these changes

2023-06-15 15:51 UTC, slax57 commented
@fzaninotto I'll let you check one last time :wink:

2023-06-16 07:56 UTC, fzaninotto approved these changes

2023-06-16 07:56 UTC, merged