Update documentation about AutocompleteInput and AutocompleteArrayInput
marmelab/react-admin pull request #9046
Opened 2023-06-26 09:39 UTC by djhi

2023-06-26 09:42 UTC, djhi commented
Fixes #8545

2023-06-27 08:10 UTC, slax57 requested changes
Also, the title of the PR is misleading, because you also changed something in the code, not only the docs

2023-06-27 08:10 UTC, slax57 commented on docs/AutocompleteArrayInput.md
> +`optionText` is also useful when the choices are records [fetched from another resource](#fetching-choices), and `<AutocompleteArrayInput>` is a child of a [`<ReferenceArrayInput>`](./ReferenceArrayI
To me, this line is redundant with line 325

2023-06-27 08:10 UTC, slax57 commented on docs/AutocompleteArrayInput.md
> +</ReferenceArrayInput>
This example is redundant with example given lines 328-330.

Besides, you removed the example where we actually pass a React element to `optionText`. We should keep at least one such example IMO.

2023-07-03 13:32 UTC, slax57 approved these changes

2023-07-03 13:33 UTC, merged