Rich Text Input - working as JSON
marmelab/react-admin pull request #9065
Opened 2023-06-30 16:13 UTC by jhrncar

I have added a optional prop useJson to RichTextInput. It is very common for these kinds of inputs to be stored in JSON format rather than raw HTML and TipTap has full supoort for this approach - the getJSON() function. IT automatically parses the output back in to the editor and is compatible with everything i found so far.

2023-07-03 08:09 UTC, slax57 requested changes
Thanks for the contribution :slightly_smiling_face: 

It looks like a quick feature to implement indeed, so I'm in favor of adding it. :slightly_smiling_face: 

Could you please also:
- Add a test to prove that it works
- Add a story to make it easier to test this new prop
- Document this new prop in the component's documentation file

Thank you so much

2023-07-03 13:40 UTC, slax57 commented
No worries, it's a promising start so far :slightly_smiling_face: 
Feel free to ask us if you need help running the tests or the storybook.

2023-07-05 10:05 UTC, jhrncar commented
Do you guys have any guide on how you do tests and stories? In the Contribution part of the README it doesnt say it :D

2023-07-05 13:35 UTC, adguernier commented
Hi ! 

The stories live near the component, so you have a `RichTextInput.stories.tsx` for `RichTextInput.tsx` component. You can add a  story to test the behavior of the component with your new prop.

Then, to see the result, you can launch _Storybook_ with `make storybook`.

Same for test: you have a file `RichTextInput.spec.tsx` near `RichTextInput.tsx`. You can run test with `yarn test-unit RichTextInput`.

Hope this help :slightly_smiling_face:

2023-07-14 14:29 UTC, jhrncar reviewed
Story, test implemented and passed. Doc implemented

2023-07-14 14:53 UTC, jhrncar commented
I have stated it in the documentation, but I will say it here as well:

using this prop (useJSON) will **destroy** the compatibility with react-admin's <RichTextField>. A user will have to create his own renderer, unless one is provided - this would require major changes to the <RichTextField>. Currently, it uses dangerouslySetInnerHTML with external sanitizers - the renderer based on JSON should be safer from the start. I have provided a link to a renderer made by 3rd party that served as a basis for my own <RichTextField> - however I have not tested it in production enogh (unlike this prop) so that i will be comfortable making it public. 

Let me know your thoughts on this guys

2023-07-17 09:57 UTC, slax57 requested changes
@jhrncar Thank you so much for the work you've started! :slightly_smiling_face: 

Unfortunately, I kind of agree with you that it can be a bit disturbing not to have a Field component matching this Input.
Hence, I'm not in favor of merging this PR in its current state.

Since building the matching Field component would require more work, and a 3rd party lib (which means yet another dependency to maintain), I believe it would be more adequate to publish this component (the RichTextInput with JSON support) along with the corresponding Field component in an external package.

If you are willing to publish them as such, we could then add a link to your package in the official doc.

WDYT?

2023-07-17 10:30 UTC, jhrncar commented
> @jhrncar Thank you so much for the work you've started! 🙂
> 
> Unfortunately, I kind of agree with you that it can be a bit disturbing not to have a Field component matching this Input. Hence, I'm not in favor of merging this PR in its current state.
> 
> Since building the matching Field component would require more work, and a 3rd party lib (which means yet another dependency to maintain), I believe it would be more adequate to publish this component (the RichTextInput with JSON support) along with the corresponding Field component in an external package.
> 
> If you are willing to publish them as such, we could then add a link to your package in the official doc.
> 
> WDYT?

Yes, I see your point, but how as I am quite unexperienced with making packages etc, how would this work? Because, if a user would install this package, it would need to overwrite the React-Admin's RichTextInput and RichTextField, no?

2023-07-18 09:03 UTC, closed without merging