[Doc] Clearer explanation for some props in AutompleteInput
marmelab/react-admin pull request #9071
Opened 2023-07-03 14:43 UTC by adguernier

2023-07-04 07:50 UTC, fzaninotto requested changes

2023-07-04 07:50 UTC, fzaninotto commented on docs/AutocompleteInput.md
> -In that case, react-admin uses the [`recordRepresentation`](./Resource.md#recordrepresentation) of the related resource to display the record label. In the example above, `<AutocompleteInput>` uses t
I don't think you should remove this sentence. If it's hard to understand, perhaps you need to add a snippet about the `<Resource>` definition?

2023-07-04 07:50 UTC, fzaninotto commented on docs/img/autocomplete-input-with-create.mp4
Could you make a wider screencast (it's a bit narrow), and go beyond clicking on the "create" option to show the entire option creation process?

2023-07-04 11:23 UTC, fzaninotto commented on docs/AutocompleteInput.md
> +</Admin>
That's not valid React!

```suggestion
import { Admin, Resource, ListGuesser } from 'react-admin';
import { dataProvider } from './dataProvider';
import { PostCreate } from './PostCreate';

export const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="posts" list={ListGuesser} create={PostCreate} />
        <Resource name="authors" recordRepresentation={record => record.name} />
    </Admin>
    );
```

Also, I would put that snippet *after* the PostCreate snippet.

2023-07-04 11:23 UTC, fzaninotto commented on docs/AutocompleteInput.md
>  <ReferenceInput label="Author" source="author_id" reference="authors">
You need to make it a component

2023-07-05 07:47 UTC, fzaninotto approved these changes

2023-07-05 07:48 UTC, djhi approved these changes

2023-07-05 07:52 UTC, fzaninotto commented on docs/AutocompleteInput.md
> +        <Resource name="authors" recordRepresentation="last_name" />
I used `last_name` in this example because `name` is the default, so it makes no sense to set it.

2023-07-05 07:53 UTC, fzaninotto commented
The video is too wide and too tall, and it's barely readable.

2023-07-05 08:44 UTC, adguernier commented
> The video is too wide and too tall, and it's barely readable.

I update videos, let me know if their are ok :)

2023-07-05 12:15 UTC, fzaninotto approved these changes

2023-07-05 12:15 UTC, merged

2023-07-05 14:35 UTC, slax57 commented on docs/AutocompleteInput.md
> +The `Create %{item}%` option will only be displayed once the user has already set a filter (by typing in some input). If you expect your users to create new items often, you can make this more user-f
Actually this was not a typo, this is the way we declare template variables in polyglot :grimacing: 
(see https://github.com/marmelab/react-admin/blob/master/packages/ra-language-english/src/index.ts#L16)