[Doc] Fix code examples syntax errors
marmelab/react-admin pull request #9083
Opened 2023-07-06 15:40 UTC by WiXSL

2023-07-06 15:58 UTC, djhi requested changes

2023-07-06 15:58 UTC, djhi commented on docs/AuthRBAC.md
> +            <AccordionForm.Panel label="Description">
```suggestion
            <AccordionForm.Panel name="description" label="Description">
```

2023-07-06 15:58 UTC, djhi commented on docs/AuthRBAC.md
> +            <AccordionForm.Panel label="Images">
```suggestion
            <AccordionForm.Panel name="images" label="Images">
```

2023-07-06 15:58 UTC, djhi commented on docs/AuthRBAC.md
> +            <AccordionForm.Panel label="Stock">
```suggestion
            <AccordionForm.Panel name="stock" label="Stock">
```

2023-07-06 15:58 UTC, djhi commented on docs/AuthRBAC.md
> +            <AccordionForm.Panel label="Description">
This actually required for permissions

2023-07-06 16:00 UTC, djhi commented on docs/Menu.md
> +const CustomLayout = (props) => (
Please change the codefence language instead. Same where possible.

2023-07-06 16:57 UTC, WiXSL commented
Back to RFR

2023-07-07 08:13 UTC, adguernier approved these changes

2023-07-07 10:05 UTC, slax57 approved these changes
Incredible work, thank you so much! :muscle: :pray:

2023-07-07 10:06 UTC, merged