[[Doc] add a sections to explain explicitly how to disable features like bulk actions
marmelab/react-admin pull request #9086
Opened 2023-07-07 14:20 UTC by adguernier

2023-07-07 14:21 UTC, djhi requested changes

2023-07-07 14:21 UTC, djhi commented on docs/Datagrid.md
> +## How to disable checkboxes
```suggestion

## How to disable checkboxes

```

2023-07-10 08:46 UTC, slax57 requested changes

2023-07-10 08:46 UTC, slax57 commented on docs/List.md
> +You can remove the `<ExportButton>` by passing false to the exporter prop.
```suggestion
You can remove the `<ExportButton>` by passing `false` to the exporter prop.
```

2023-07-10 08:46 UTC, slax57 commented on docs/List.md
> +## How to disable `storeKey`
```suggestion
## How to disable storing the list parameters in the Store
```

2023-07-10 08:46 UTC, slax57 commented on docs/List.md
> +You can disable `storeKey` feature by setting the `storeKey` prop to `false`. When disabled, parameters will not be persisted in the store.
```suggestion
You can disable the `storeKey` feature by setting the `storeKey` prop to `false`. When disabled, the list parameters (pagination, sorting and filters) will not be persisted in [the Store](./Store.md).
```

2023-07-10 08:46 UTC, slax57 commented on docs/List.md
> +## How to remove `<ExportButton>`
```suggestion
## How to remove the `<ExportButton>`
```

2023-07-10 15:48 UTC, slax57 approved these changes

2023-07-10 15:50 UTC, djhi requested changes

2023-07-10 15:50 UTC, djhi commented on docs/List.md
> +You can remove the `<ExportButton>` by passing `false` to the exporter prop.
```suggestion
You can remove the `<ExportButton>` by passing `false` to the `exporter` prop.
```

2023-07-10 15:51 UTC, djhi approved these changes

2023-07-10 15:51 UTC, merged