RA-OSS-18 - Ability to style emptyText on fields
marmelab/react-admin pull request #9137
Opened 2023-07-28 16:05 UTC by gitstart

Here is the GitStart Ticket for this pull request: [RA-OSS-18](https://developers.gitstart.com/client/reactadmin-oss/ticket/RA-OSS-18)
[ISSUE](https://github.com/marmelab/react-admin/issues/8951)
## Loom Video:
https://www.loom.com/share/a15ca7e68a04480e9c55fc4ab96d8308?sid=ba2c408c-4d7b-41c9-a2aa-0f2bdecdd546

2023-07-31 10:08 UTC, fzaninotto commented
As this is a new feature, please rebase on `next` rather than `master`.

2023-07-31 10:09 UTC, fzaninotto commented
You must also update the documentation in `Fields.md` and add unit tests.

2023-08-03 07:39 UTC, gitstart commented
> You must also update the documentation in `Fields.md` and add unit tests.

PR has been rebased to `next` @fzaninotto

2023-08-03 13:22 UTC, fzaninotto requested changes
Note that since the value of `emptyText` is no longer a `string`, its title becomes misleading. But we won't add another prop just for that, or introduce a BC break by renaming it, so we'll live with this incoherence.

2023-08-03 13:22 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ImageField.spec.tsx
> +        'hould render the emptyText ReactNode when value is %s',
```suggestion
        'should render the emptyText ReactNode when value is %s',
```

2023-08-03 13:22 UTC, fzaninotto commented on docs/Fields.md
> +| [`emptyText`](#emptytext)     | Optional | `string` &#124; `ReactNode`    | ''       | Defines a text or element to be shown when a field has no value (not supported in array fields)
```suggestion
| [`emptyText`](#emptytext)     | Optional | `string | ReactNode`    | ''       | Defines a text or element to be shown when a field has no value (not supported in array fields)                                                                    |
```

2023-08-03 13:22 UTC, fzaninotto commented on docs/Fields.md
> +            <TextField source="email" emptyText={<b>missing data</>} />
```suggestion
            <TextField source="email" emptyText={<em>missing data</em>} />
```

2023-08-03 13:22 UTC, fzaninotto commented on docs/ReferenceField.md
> +| `emptyText` | Optional | `string` &#124; `ReactNode`    | ''       | Defines a text or element to be shown when the field has no value or when the reference is missing |
```suggestion
| `emptyText` | Optional | `string | ReactNode`    | ''       | Defines a text or element to be shown when the field has no value or when the reference is missing |
```

2023-08-03 13:22 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/BooleanField.spec.tsx
> +            expect(renderedEmptyText).toBeTruthy();
`getByXXX` throws if the searched element is not found. This `expect` doesn't really make sense. So either use `queryByYYY` or remove the `expect`. 

See https://testing-library.com/docs/react-testing-library/cheatsheet/#queries

Same for other tests.

2023-08-03 13:22 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/DateField.spec.tsx
> +                    source="foo.bar"
```suggestion
                    source="foo"
```

2023-08-03 13:22 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/NumberField.spec.tsx
> +                    source="foo.bar"
```suggestion
                    source="foo"
```

2023-08-03 13:22 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/UrlField.spec.tsx
> +                    className="foo"
Remove this one, as it's useless in that case

2023-08-08 12:40 UTC, fzaninotto commented
Can you please remove the changes that aren't related to your new feature? The ones you cherry-picked related ti WizardForm for example.

2023-08-08 14:20 UTC, gitstart commented
> Can you please remove the changes that aren't related to your new feature? The ones you cherry-picked related to WizardForm for example.

@fzaninotto Seems like other changes are from the `next` branch

2023-08-08 14:34 UTC, fzaninotto commented
I think you messed up your rebase. 

Let me reiterate: you need to remove the changes you didn't make from this PR.

2023-08-28 08:20 UTC, fzaninotto commented
Bump, can you please fix your rebase?

2023-10-27 11:14 UTC, fzaninotto commented
No news for some time, closing.

2023-10-27 11:14 UTC, closed without merging