[Doc] Convert `<Datagrid>` documentation to TS
marmelab/react-admin pull request #9207
Opened 2023-08-21 13:53 UTC by djhi

2023-08-21 15:40 UTC, slax57 requested changes

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in src/posts.js
```suggestion
// in src/posts.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in src/PostList.js
```suggestion
// in src/PostList.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in ./ResetViewsButton.js
```suggestion
// in ./ResetViewsButton.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in ./CustomResetViewsButton.js
```suggestion
// in ./CustomResetViewsButton.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in ./CustomResetViewsButton.js
```suggestion
// in ./CustomResetViewsButton.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in src/users.js
```suggestion
// in src/users.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in src/posts.js
```suggestion
// in src/posts.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in src/posts.js
```suggestion
// in src/posts.tsx
```

2023-08-21 15:40 UTC, slax57 commented on docs/Datagrid.md
>  // in src/posts.js
```suggestion
// in src/posts.tsx
```

2023-08-21 15:52 UTC, adguernier commented on docs/Datagrid.md
> +				isValidElement<FieldProps>(child) ? (
Why not using `React.isValidElement` as other snippets ?

2023-08-21 15:52 UTC, adguernier commented on docs/Datagrid.md
> +import { DatagridHeaderProps, FieldProps, List, Datagrid } from "react-admin";
```suggestion
import { DatagridHeaderProps, FieldProps, List, Datagrid, DatagridHeader } from "react-admin";
```

2023-08-22 13:33 UTC, slax57 requested changes

2023-08-22 13:33 UTC, slax57 commented on docs/Datagrid.md
> +const DatagridHeader = ({ children }: DatagridHeaderProps) => (
In this snippet you are both importing `DatagridHeader` from `"react-admin"` and declaring `const DatagridHeader`. This cannot work. You should remove the import I believe.

2023-08-22 13:34 UTC, djhi commented on docs/Datagrid.md
> +import { DatagridHeaderProps, FieldProps, List, Datagrid, DatagridHeader } from "react-admin";
```suggestion
import { DatagridHeaderProps, FieldProps, List, Datagrid } from "react-admin";
```

2023-08-22 14:44 UTC, slax57 approved these changes

2023-08-22 14:44 UTC, merged