Add `<SortButton sx>` prop to customize button style
marmelab/react-admin pull request #9223
Opened 2023-08-25 16:38 UTC by fzaninotto

Closes #9161

2023-08-26 12:49 UTC, djhi requested changes
You should also add a root css class and assign it to the Root element (with cslx to add className). It's not done automatically by MUI and prevents targetting this element from its parent styles

2023-08-28 08:19 UTC, fzaninotto commented
Review applied

2023-08-28 09:45 UTC, slax57 approved these changes

2023-08-28 09:47 UTC, slax57 requested changes
My bad, this PR is missing one more thing: updating the documentation to mention we support the `sx` prop now.

2023-08-28 11:41 UTC, djhi approved these changes

2023-08-28 12:52 UTC, merged