Fix useReferenceManyFieldController fails with error when the record is not yet present
marmelab/react-admin pull request #9236
Opened 2023-08-31 13:40 UTC by djhi

Can't find a way to unit test it though

2023-08-31 14:35 UTC, slax57 requested changes
Is it possible to describe the case where you ran into this issue, and/or paste the error you got? This would make it easier for people having this same error to find this issue.

2023-08-31 14:35 UTC, slax57 commented on packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
> +            enabled: !!get(record, source),
```suggestion
            enabled: get(record, source) != null,
```

Remember that `0` is a valid id

2023-08-31 15:49 UTC, djhi commented on packages/ra-core/src/controller/field/useReferenceManyFieldController.ts
> +            enabled: !!get(record, source),
Good catch :)

2023-09-01 13:05 UTC, slax57 approved these changes

2023-09-01 13:05 UTC, merged