Fix typos and invalid code fences languages
marmelab/react-admin pull request #9238
Opened 2023-09-01 14:08 UTC by djhi

2023-09-01 14:12 UTC, fzaninotto requested changes

2023-09-01 14:12 UTC, fzaninotto commented on docs/ListTutorial.md
> +            <TextField<Book> source="year" />
This is overkill IMHO

2023-09-01 14:12 UTC, fzaninotto commented on docs/ListTutorial.md
> +                    <TextField<Post> source="id" />
this, too

2023-09-01 14:20 UTC, djhi commented on docs/ListTutorial.md
> +            <TextField<Book> source="year" />
```suggestion
            <TextField source="id" />
            <TextField source="title" />
            <TextField source="author" />
            <TextField source="year" />
```

2023-09-01 15:04 UTC, djhi commented on docs/ListTutorial.md
> +                        <TextField<User> source="name" />
```suggestion
                    <ReferenceField label="User" source="userId" reference="users">
                        <TextField source="name" />
```

2023-09-01 15:04 UTC, djhi commented on docs/ListTutorial.md
> +                    <TextField<Post> source="body" />
```suggestion
                    <TextField source="title" />
                    <TextField source="body" />
```

2023-09-01 15:05 UTC, djhi commented on docs/ListTutorial.md
> +}
```suggestion
```

2023-09-01 15:06 UTC, fzaninotto commented on docs/ListTutorial.md
> +};
Now useless

2023-09-01 15:33 UTC, djhi commented on docs/ListTutorial.md
> +
```suggestion
```

2023-09-04 07:45 UTC, fzaninotto approved these changes

2023-09-04 07:46 UTC, merged