Fix `<RichTextInput>` does not trigger `onBlur`
marmelab/react-admin pull request #9272
Opened 2023-09-12 15:44 UTC by slax57

Fix https://github.com/marmelab/react-admin/issues/9265

2023-09-12 15:45 UTC, mchaffotte approved these changes

2023-09-12 16:34 UTC, fzaninotto requested changes

2023-09-12 16:34 UTC, fzaninotto commented on packages/ra-input-rich-text/src/RichTextInput.tsx
> +import * as React from 'react';
I don't know why you did that, but every React file in react-admin has this line as first and I don't think we should change it.

2023-09-13 12:47 UTC, adguernier approved these changes

2023-09-13 13:04 UTC, fzaninotto approved these changes

2023-09-13 13:04 UTC, merged