Fix RichTextInput does not update when its editorOptions prop changes
marmelab/react-admin pull request #9289
Opened 2023-09-18 10:27 UTC by djhi

2023-09-19 15:46 UTC, djhi commented on packages/ra-input-rich-text/src/RichTextInput.tsx
> +        [disabled, editorOptions, readOnly, id]
Unfortunately, the editorOptions is not a simple object. It contains classes with circular references so no

2023-09-19 15:47 UTC, djhi commented on packages/ra-input-rich-text/src/RichTextInput.stories.tsx
> +    };
We do, it wasn't visible with the poor list UI I copied from tiptap docs without their styles. Should be better now

2023-09-20 07:55 UTC, slax57 requested changes
Navigation with keyboard is functional and the console warnings are gone, so GJ!

However, now, when I select an option in the dropdown list, then the list remains open instead of closing right away. Can you fix this too?

2023-10-02 14:03 UTC, slax57 approved these changes
All errors fixed, nice job! :muscle:

2023-10-02 14:04 UTC, merged