match code and illustrations for SearchInput
marmelab/react-admin pull request #9376
Opened 2023-10-20 16:17 UTC by erwanMarmelab

## Problem
On the documentation, videos, pictures and gifs are showing `<SearchInput />` element, but in the code it's writed `<TextInput label="Search" />` as this:

![image](https://github.com/marmelab/react-admin/assets/131013150/a2621b8b-cee2-4d7d-a1e5-8419cc9b134d)

## Solution
Match code and illustrations by apllying `<SearchInput />` everywhere.

2023-10-23 13:39 UTC, slax57 requested changes
Otherwise this seems good, thanks!

2023-10-23 13:39 UTC, slax57 commented on docs/FilteringTutorial.md
> +    <SearchInput source="q" alwaysOn />,
I'd keep the `TextInput` here since we introduce the `SearchInput` just a few lines below.

2023-10-23 14:43 UTC, slax57 approved these changes

2023-10-24 05:27 UTC, fzaninotto approved these changes

2023-10-24 05:27 UTC, merged