[Doc] Update canAccess doc
marmelab/react-admin pull request #9396
Opened 2023-10-26 08:24 UTC by adguernier

Update the [`canAccess` action](https://marmelab.com/react-admin/canAccess.html#action) doc to match the example in the Enterprise Edition doc

2023-10-26 10:08 UTC, erwanMarmelab approved these changes

2023-10-26 15:09 UTC, slax57 requested changes

2023-10-26 15:09 UTC, slax57 commented on docs/canAccess.md
> +If you want to check a specific action, for instance if the user can `delete` a `post` , you can specify this action in the dedicated prop:
```suggestion
If you want to check a specific action, for instance if the user can `delete` a `post`, you can specify this action in the dedicated prop: 
```

2023-10-26 15:09 UTC, slax57 commented on docs/canAccess.md
> +import { Admin } from 'react-admin';
```suggestion
import { Admin, usePermissions } from 'react-admin';
```

2023-10-26 15:09 UTC, slax57 commented on docs/canAccess.md
> +**Note**: that [ra-rbac's `<Resource>` component](./AuthRBAC.md#resource) check automatically the `list`, `show `, `create` and `edit` actions, so you don't actually need to use `canAccess` if you wa
```suggestion
**Note**: [ra-rbac's `<Resource>` component](./AuthRBAC.md#resource) automatically checks for the `list`, `show`, `create` and `edit` actions, so you don't actually need to use `canAccess` if you want to restrict a whole resource.
```

2023-10-27 11:05 UTC, fzaninotto approved these changes

2023-10-27 11:05 UTC, merged