[Doc] Add documentation for `<DatagridAG>`
marmelab/react-admin pull request #9414
Opened 2023-10-31 14:04 UTC by slax57

2023-11-02 13:27 UTC, adguernier requested changes

2023-11-02 13:27 UTC, adguernier commented on docs/DatagridAG.md
> +  <source src="https://marmelab.com/ra-enterprise/modules/assets/DatagridAG.mp4" type="video/mp4"/>
The video does not work in Firefox

2023-11-02 13:27 UTC, adguernier commented on docs/DatagridAG.md
> +  <source src="https://marmelab.com/ra-enterprise/modules/assets/DatagridAG-enterprise.mp4" type="video/mp4"/>
Does not work on Firefox

2023-11-02 13:27 UTC, adguernier commented on docs/DatagridAG.md
> +  <source src="https://marmelab.com/ra-enterprise/modules/assets/DatagridAG-enterprise.mp4" type="video/mp4"/>
Does not work on Firefox

2023-11-06 08:52 UTC, fzaninotto commented on docs/DatagridAG.md
> +  <source src="https://marmelab.com/ra-enterprise/modules/assets/DatagridAG.mp4" type="video/mp4"/>
This is fixed in the ra-e,terprise doc.

2023-11-06 08:53 UTC, fzaninotto approved these changes

2023-11-06 08:53 UTC, merged

2023-11-06 09:37 UTC, fzaninotto commented
To let users find DatagridAG when they aren't looking for it, I also added various links to that page from other places in the doc. 

See ddde9f75d18ffbf3de9cacb526eb5850641489fe