docs: inspector component details for configuration feature
marmelab/react-admin pull request #9458
Opened 2023-11-20 09:52 UTC by rossb220

2023-11-20 10:07 UTC, fzaninotto commented
Thanks! Could you please add an example of a custom layout with embedded Inspector in this new section?

2023-11-24 09:53 UTC, slax57 requested changes

2023-11-24 09:53 UTC, slax57 commented on docs/Configurable.md
> +The `<Inspector>` component exists within the layouts provided by react-admin. If you are using a custom layout then you should add the `<Inspector>` component within your layout
```suggestion
The `<Inspector>` is already included in the layouts provided by react-admin. If you are using a custom layout, you need to add the `<Inspector>` component to your layout.
```

2023-11-24 09:53 UTC, slax57 commented on docs/Configurable.md
> +import { AppBar, Menu, Sidebar, InspectorButton } from 'react-admin';
```suggestion
import { AppBar, Menu, Sidebar, Inspector } from 'react-admin';
```

2023-11-24 09:53 UTC, slax57 commented on docs/Configurable.md
> +        <InspectorButton />
```suggestion
        <Inspector />
```

2023-11-24 09:53 UTC, slax57 commented on docs/WrapperField.md
> +a group of form fields (in a `<SimpleFormConfigurable>`)
```suggestion
This component simply renders its children. Why would you want to use such a dumb component? To combine several fields in a single cell (in a `<Datagrid>`), in a single row (in a `<SimpleShowLayout>`) or in a group of inputs (in a `<SimpleFormConfigurable>`) .
```

2023-11-24 09:53 UTC, slax57 commented on docs/WrapperField.md
> +);
```suggestion
import { Edit, WrapperField, TextInput, SimpleFormConfigurable } from 'react-admin';
import { Stack } from '@mui/material';

const PostEdit = () => (
    <Edit>
        <SimpleFormConfigurable>
            <TextInput source="title"/>
            <WrapperField source="author">
                <Stack>
                    <TextInput source="author_first_name"/>
                    <TextInput source="author_last_name"/>
                </Stack>
            </WrapperField>
        </SimpleFormConfigurable>
    </Edit>
);
```

2023-11-24 09:55 UTC, slax57 commented
Thanks for the changes.

Unfortunately it seems I do not have the permissions to commit on your branch, so unfortunately I can't commit the suggested changes myself.
Can you please accept them?

Thanks.

2023-11-24 10:16 UTC, rossb220 commented
@slax57 That's been done but would you like me to squash the commits?

2023-11-24 10:18 UTC, slax57 commented
No need I'll do it when merging. Thanks a lot! :pray:

2023-11-24 10:19 UTC, slax57 approved these changes

2023-11-24 10:20 UTC, merged