Introduce default dark theme 2
marmelab/react-admin pull request #9479
Opened 2023-11-29 08:59 UTC by adguernier

The point of this PR is to update the `<Admin>` component to include dark theme by default

## TODO
- [ ] Add the defaultDarkTheme in AdminUI
- [ ] Remove the default darkTheme in stories
- [ ] Update documentation
- [ ] Add upgrade guide

2023-11-29 11:20 UTC, djhi requested changes

2023-11-29 11:20 UTC, djhi commented on docs/Admin.md
> +React-admin provides a [built-in dark theme by default](./AppTheme.md#default). The app will use the `darkTheme` by default for users who prefer the dark mode at the OS level, and users will be able
```suggestion
React-admin provides a [built-in dark theme](./AppTheme.md#default). The app will use the `darkTheme` by default for users who prefer the dark mode at the OS level, and users will be able to switch from light to dark mode using [the `<ToggleThemeButton>` component](./ToggleThemeButton.md).
```

2023-11-29 11:20 UTC, djhi commented on docs/Admin.md
> +If you want to override it, you can provide your custom `darkTheme` in addition to the `theme` prop:
```suggestion
If you want to override it, you can provide your own `darkTheme` in addition to the `theme` prop:
```

2023-11-29 11:20 UTC, djhi commented on docs/Admin.md
> +React-admin provides a [built-in light theme by default](./AppTheme.md#default). The app will use the `lightTheme` by default for users who prefer the light mode at the OS / browser level, and users
```suggestion
React-admin provides a [built-in light theme](./AppTheme.md#default). The app will use the `lightTheme` by default for users who prefer the light mode at the OS / browser level, and users will be able to switch from light to dark mode using [the `<ToggleThemeButton>` component](./ToggleThemeButton.md) if the `darkTheme` prop is provided or leaved by default.
```

2023-11-29 11:20 UTC, djhi commented on docs/Admin.md
> +If you want to override it, you can provide your custom `lightTheme`:
```suggestion
If you want to override it, you can provide your own `lightTheme`:
```

2023-11-29 11:20 UTC, djhi commented on docs/AppTheme.md
> +In addition, users can switch from one theme to the other using [the `<ToggleThemeButton>` component](./ToggleThemeButton.md), which appears in the AppBar as soon as you define a `darkTheme` prop.
```suggestion
In addition, users can switch from one theme to the other using [the `<ToggleThemeButton>` component](./ToggleThemeButton.md), that appears in the AppBar as soon as you define a `darkTheme` prop.
```

2023-11-29 11:20 UTC, djhi commented on docs/ToggleThemeButton.md
> +It is enabled by default in the `<AppBar>` as soon React-admin provides a [built-in dark theme by default](./AppTheme.md#default).
```suggestion
It is enabled by default in the `<AppBar>` as React-admin provides a [built-in dark theme](./AppTheme.md#default).
```

2023-11-29 11:20 UTC, djhi commented on docs/Admin.md
> +- if `theme` is not provided the `lightTheme` prop is ignored;
Are you sure?

2023-11-29 11:20 UTC, djhi commented on docs/ToggleThemeButton.md
> +For this button to work, you must provide a dark theme to the `<Admin>` component. React-admin provides a [built-in dark theme by default](./AppTheme.md#default), but you can override it according to
```suggestion
For this button to work, you must provide a dark theme to the `<Admin>` component. React-admin provides a [built-in dark theme](./AppTheme.md#default), but you can override it according to your needs.
```

2023-11-29 11:20 UTC, djhi commented on docs/Upgrade.md
> +If not themes are configured in the `<Admin>` component prop, React-admin enable the [dark mode feature](https://marmelab.com/react-admin/AppTheme.html#light-and-dark-themes) by default.
```suggestion
If themes are not configured using the `<Admin>` component props, React-admin enables the [dark mode feature](https://marmelab.com/react-admin/AppTheme.html#light-and-dark-themes).
```

2023-11-29 11:20 UTC, djhi commented on docs/Upgrade.md
> +If you don't need the dark mode feature, you need to explicitly disable it:
```suggestion
If you don't need the dark mode feature, you'll have to explicitly disable it:
```

2023-11-29 11:20 UTC, djhi commented on docs/Upgrade.md
> +To best manage the `theme` prop, here are the priorities applied depending on whether the `theme` prop is provided or not:
```suggestion
Here are the priorities applied depending on whether the `theme` prop is provided or not:
```

2023-11-29 11:20 UTC, djhi commented on docs/Upgrade.md
> +- if `theme` is not provided the `lightTheme` prop is ignored (no change from before);
Nope

2023-11-29 17:00 UTC, fzaninotto requested changes
Neat!

2023-11-29 17:00 UTC, fzaninotto commented on docs/Admin.md
> +| `lightTheme`        | Optional | `object`       | `defaultLightTheme` (the default built-in light theme)              | The light theme configuration                             |
We shouldn't document the lightTheme IMO, it's confusing.

2023-11-29 17:00 UTC, fzaninotto commented on docs/Admin.md
> +| `darkTheme`        | Optional | `object`       | `defaultDarkTheme` (the default built-in dark theme)              | The dark theme configuration                             |
you should also set the default value for the `theme` to `defaultLightTheme`

2023-11-29 17:02 UTC, fzaninotto commented
We have many stories that set a custom dark theme. You should revisit these, too. 

<img width="282" alt="image" src="https://github.com/marmelab/react-admin/assets/99944/af6cc1ea-ba18-4d26-a21e-570eaefecf5f">

2023-11-29 17:07 UTC, fzaninotto commented
Interesting side effect: My OS defaults to dark theme, and so every story in the Storybook that uses `<Admin>` or `<AdminContext>` defaults to dark theme, too. 

![image](https://github.com/marmelab/react-admin/assets/99944/37a6968e-94a1-4773-9ad2-b52253da53f2)

I suggest we systematically set the `defaultTheme="light"` in stories to avoid that.

2023-12-04 09:55 UTC, djhi requested changes

2023-12-04 09:55 UTC, djhi commented on docs/Upgrade.md
> +If the `theme` prop is defined but not the `darkTheme` prop, theme switcher button in the app bar isn't displayed:
```suggestion
If the `theme` prop is defined but not the `darkTheme` prop, the theme switcher button in the app bar isn't displayed:
```

2023-12-04 11:24 UTC, fzaninotto approved these changes

2023-12-04 11:37 UTC, djhi approved these changes

2023-12-04 11:38 UTC, merged