Doc: Improve MarkdownInput documentation
marmelab/react-admin pull request #9511
Opened 2023-12-11 16:11 UTC by arimet

2023-12-12 13:59 UTC, djhi approved these changes

2023-12-12 13:59 UTC, djhi commented on docs/MarkdownInput.md
> +| `useCommandShortcut`     | Optional | `boolean`           |     `true`      | Whether use keyboard shortcuts to perform commands|
Can you please reformat this?

2023-12-12 14:41 UTC, djhi approved these changes

2023-12-13 09:29 UTC, adguernier requested changes
Two more things:
- IMO it would be good to add screenshots
- the example that shows how to "Customize the markdown renderer used for the preview" from the RAEE doc is missing 

Otherwise it looks good

2023-12-13 09:29 UTC, adguernier commented on docs/MarkdownInput.md
> +| `source`             | Required | `string`  |            | The field name in the record                                          |
Props should be in alphabetic order in this table, stating with required props.
Ditto for the rest

2023-12-13 09:29 UTC, adguernier commented on docs/MarkdownInput.md
> +`<MarkdownInput>` also accepts the [common input props](https://marmelab.com/react-admin/Inputs.html#common-input-props) and the [editor props](https://nhn.github.io/tui.editor/latest/ToastUIEditorCo
```suggestion
`<MarkdownInput>` also accepts the [common input props](https://marmelab.com/react-admin/Inputs.html#common-input-props) and the [editor props](https://nhn.github.io/tui.editor/latest/ToastUIEditorCore) from the [Toast UI](https://ui.toast.com/) editor.
```

2023-12-13 09:29 UTC, adguernier commented on docs/MarkdownInput.md
> +You can add your own buttons to the markdown editor by using the `toolbarItems` prop. It accepts an array of [toolbar items](https://nhn.github.io/tui.editor/latest/ToastUIEditorToolbar#toolbar-items
Wrong link:

```suggestion
You can add your own buttons to the markdown editor by using the `toolbarItems` prop. It accepts an array of [toolbar items](https://nhn.github.io/tui.editor/latest/tutorial-example15-customizing-toolbar-buttons) and is set to `null` by default.
```

2023-12-13 15:21 UTC, fzaninotto requested changes

2023-12-13 15:21 UTC, fzaninotto commented on docs/MarkdownInput.md
> +<Form record={{ id: 123, title: 'Hello, world!', body: '<p>Lorem Ipsum</p>' }}>
You should use a Markdown value for the body, not an HTML value

2023-12-13 15:21 UTC, fzaninotto commented on docs/MarkdownInput.md
> +
No need for a newline here, and before the `{ % endraw %}`

2023-12-13 15:21 UTC, fzaninotto commented on docs/MarkdownInput.md
> +You can customize the preview style by setting the `previewStyle` prop. It accepts `tab` or `vertical` and is set to `vertical` by default.
I'm not sure I understand what this prop does. You either need to explain it differently, or to add screenshots.

2023-12-13 15:21 UTC, fzaninotto commented on docs/MarkdownInput.md
> +
Is there an easy way to make it 100% height?

2023-12-13 15:21 UTC, fzaninotto commented on docs/MarkdownInput.md
> +## Add Your Own Buttons
```suggestion
## Adding Buttons
```

Or
```suggestion
## `toolbarItem`
```

In any case, you need to add the `toolbarItem` prop to the Props table

2023-12-14 10:53 UTC, adguernier requested changes

2023-12-14 10:53 UTC, adguernier commented on docs/MarkdownInput.md
> +| `helperText`         | Optional | `string`  |            | The helper text to display under the input                                                          |
It seems `helperText` and `height` are not in alphabetic order. Sorry

2023-12-18 09:13 UTC, djhi reviewed
Please make all the examples copy/pastable with imports, etc. Also, write them in TSX

2023-12-18 09:13 UTC, djhi commented on docs/MarkdownInput.md
> +);
Can you complete this example? Imports, real component, etc.

2023-12-19 10:14 UTC, fzaninotto requested changes

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +    <MarkdownInput source="description" label="Description" />
bad example: in this case, you don't need to set the label as it's automatically inferred.

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +If you chose `vertical`, the content and the preview will be displayed side by side. If you chose `tab`, the content and the preview will be displayed in two separate tabs. You can switch between the
```suggestion
- With the `vertical` style, the content and the preview will be displayed side by side.
- With the `tab` style, the content and the preview will be displayed in two separate tabs. Users can switch between the two tabs by clicking on the tab header.
```

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +{% raw %}
no need for raw if no `{{` in the source

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +{% raw %}
no need for raw if no `{{` in the source

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +```tsx
please introduced this example by explaining what you're doing.

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +```JSX
```suggestion
```jsx
```

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +{% raw %}
no need for raw if no `{{` in the source

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +{% raw %}
no need for raw if no `{{` in the source

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +{% raw %}
no need for raw if no `{{` in the source

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +
no need for raw if no `{{` in the source

2023-12-19 10:14 UTC, fzaninotto commented on docs/MarkdownInput.md
> +{% raw %}
no need for raw if no `{{` in the source

2023-12-20 09:17 UTC, adguernier approved these changes

2023-12-21 11:02 UTC, fzaninotto approved these changes

2023-12-21 11:02 UTC, merged