Doc(next): Update documentation for handling App router part
marmelab/react-admin pull request #9513
Opened 2023-12-12 12:17 UTC by arimet

2023-12-12 14:01 UTC, djhi requested changes

2023-12-12 14:01 UTC, djhi commented on docs/NextJs.md
> +"use client"; // remove it if you choose Pages Router
```suggestion
"use client"; // remove this line if you choose Pages Router
```

2023-12-12 14:50 UTC, djhi approved these changes

2023-12-13 09:49 UTC, adguernier commented on docs/NextJs.md
> +This tutorial assumes you're using an `src` folder, so answer 'Yes' to the 5th question. As for the App Router, you can choose to use it or not, this tutorial will explain how to use both. (For new a
```suggestion
This tutorial assumes you're using a `src` folder, so answer `Yes` to the 5th question. As for the App Router, you can choose to use it or not, this tutorial will explain how to use both. (For new applications, Next.js recommends using the App Router).
```

2023-12-13 09:49 UTC, adguernier commented on docs/NextJs.md
> +**Tip**: This example uses the **service role key** here and not the anonymous role. This allows mutations without dealing with authorization (You may have to modify the safety policies.). **You shou
```suggestion
**Tip**: This example uses the **service role key** here and not the anonymous role. This allows mutations without dealing with authorization (You may have to modify the safety policies). **You shouldn't do this in production**, but use the [Supabase authorization](https://supabase.com/docs/guides/auth) feature instead.
```

2023-12-13 09:49 UTC, adguernier commented on docs/NextJs.md
> +// In src/app/api/admin/[...slug]/route.ts
```suggestion
// in src/app/api/admin/[...slug]/route.ts
```

2023-12-13 09:49 UTC, adguernier commented on docs/NextJs.md
> +// In src/pages/api/admin/[[...slug]].ts
```suggestion
// in src/pages/api/admin/[[...slug]].ts
```

2023-12-13 09:49 UTC, adguernier commented on docs/NextJs.md
> +npm install @raphiniert/ra-data-postgrest // or
```suggestion
npm install @raphiniert/ra-data-postgrest 
# or
```

2023-12-13 15:39 UTC, fzaninotto requested changes

2023-12-13 15:39 UTC, fzaninotto commented on docs/NextJs.md
> +**Tips**: If you choose Pages Router, do not forget to remove [the `"use client"` directive](https://nextjs.org/docs/getting-started/react-essentials#the-use-client-directive).
Do we need this tip? If they use the Pages router, the `"use client"` directive does nothing.

2023-12-13 15:39 UTC, fzaninotto commented on docs/NextJs.md
> +For more information about routes handler with the App Router, see [the official documentation](https://nextjs.org/docs/app/building-your-application/routing/route-handlers).
I'd put this comment after the code snippet

2023-12-13 15:39 UTC, fzaninotto commented on docs/NextJs.md
> +For more information about routes handler with the Pages Router, see [the official documentation](https://nextjs.org/docs/pages/building-your-application/routing/api-routes#optional-catch-all-api-rou
I'd put this comment after the code snippet

2023-12-13 15:39 UTC, fzaninotto commented on docs/NextJs.md
> +### Dataprovider
```suggestion
### Data Provider
```

2023-12-14 13:04 UTC, fzaninotto approved these changes

2023-12-14 13:05 UTC, merged