Fix `useReferenceManyFieldController` does not debounce `setFilters`
marmelab/react-admin pull request #9523
Opened 2023-12-13 13:58 UTC by djhi

Fixes #9517

2023-12-13 15:14 UTC, fzaninotto requested changes
Tou probably also need to update `ReferenceManyField` and its documentation

2023-12-13 15:14 UTC, fzaninotto commented on packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
> +            // TODO: we shouldn't import mui components in ra-core
I think this comment should be removed

2023-12-13 15:28 UTC, djhi commented on packages/ra-core/src/controller/field/useReferenceManyFieldController.spec.tsx
> +            // TODO: we shouldn't import mui components in ra-core
```suggestion
```

2023-12-13 17:07 UTC, slax57 requested changes
Code seems good but I agree with @fzaninotto

2023-12-14 08:38 UTC, djhi commented
> You probably also need to update `ReferenceManyField` and its documentation

I don't see anything to update

2023-12-14 10:07 UTC, slax57 requested changes
Better :grin:

2023-12-14 10:07 UTC, slax57 commented on docs/ReferenceManyField.md
> +// wait 1 seconds instead of 500 milliseconds befoce calling the dataProvider
```suggestion
// wait 1 seconds instead of 500 milliseconds before calling the dataProvider
```

2023-12-14 10:08 UTC, slax57 approved these changes

2023-12-15 10:49 UTC, fzaninotto approved these changes

2023-12-15 10:49 UTC, merged