Backport master changes to next
marmelab/react-admin pull request #9525
Opened 2023-12-14 10:58 UTC by slax57

We will do this regularly to make the conflicts resolution easier once the v5 is released.

2023-12-14 12:43 UTC, fzaninotto requested changes

2023-12-14 12:43 UTC, fzaninotto commented on docs/InfiniteList.md
> +    const { isLoading, data } = useInfiniteListController();
```suggestion
    const { isPending, data } = useInfiniteListController();
```

2023-12-14 12:43 UTC, fzaninotto commented on docs/InfiniteList.md
> +                {!isLoading && (
```suggestion
                {!isPending && (
```

2023-12-14 12:43 UTC, fzaninotto commented on docs/InfiniteList.md
> +                    !isLoading && (
```suggestion
            <WithListContext render={({ isPending, data }) => (
                    !isPending && (
```

2023-12-14 12:43 UTC, fzaninotto commented on docs/Features.md
> +};
```suggestion
const PostList = () => {
  const { data, page, total, setPage, isPending } = useListController({
    sort: { field: 'published_at', order: 'DESC' },
    perPage: 10,
  });
  const handleTableChange = (pagination) => {
    setPage(pagination.current);
  };
  return (
    <>
      <div style={{ margin: 10, textAlign: 'right' }}>
        <Link to="/posts/create">
          <Button icon={<PlusOutlined />}>Create</Button>
        </Link>
      </div>
      <Card bodyStyle={{ padding: '0' }} loading={isPending}>
        <Table
          size="small"
          dataSource={data}
          columns={columns}
          pagination={{ current: page, pageSize: 10, total }}
          onChange={handleTableChange}
        />
      </Card>
    </>
  );
};
```

2023-12-14 12:43 UTC, fzaninotto commented on docs/List.md
> +);
```suggestion
const ProductList = () => (
    <ListBase>
        <Container>
            <Typography variant="h4">All products</Typography>
            <WithListContext render={({ isPending, data }) => (
                    !isPending && (
                        <Stack spacing={1}>
                            {data.map(product => (
                                <Card key={product.id}>
                                    <CardContent>
                                        <Typography>{product.name}</Typography>
                                    </CardContent>
                                </Card>
                            ))}
                        </Stack>
                    )
                )} />
            <WithListContext render={({ isPending, total }) => (
                !isPending && <Typography>{total} results</Typography>
            )} />
        </Container>
    </ListBase>
);
```

2023-12-14 12:43 UTC, fzaninotto commented on docs/List.md
> +};
```suggestion
const ProductList = () => {
    const { isPending, data, total } = useListController();
    return (
        <Container>
            <Typography variant="h4">All products</Typography>
                {!isPending && (
                    <Stack spacing={1}>
                        {data.map(product => (
                            <Card key={product.id}>
                                <CardContent>
                                    <Typography>{product.name}</Typography>
                                </CardContent>
                            </Card>
                        ))}
                    </Stack>
                )}
            {!isPending && <Typography>{total} results</Typography>}
        </Container>
    );
};
```

2023-12-14 12:43 UTC, fzaninotto commented on docs/useListController.md
> +      <Card bodyStyle={{ padding: '0' }} loading={isLoading}>
```suggestion
  const { data, page, total, setPage, isPending } = useListController({
    sort: { field: 'published_at', order: 'DESC' },
    perPage: 10,
  });
  const handleTableChange = (pagination) => {
    setPage(pagination.current);
  };
  return (
    <>
      <div style={{ margin: 10, textAlign: 'right' }}>
        <Link to="/posts/create">
          <Button icon={<PlusOutlined />}>Create</Button>
        </Link>
      </div>
      <Card bodyStyle={{ padding: '0' }} loading={isPending}>
```

2023-12-14 13:21 UTC, slax57 commented on docs/useListController.md
> +      <Card bodyStyle={{ padding: '0' }} loading={isLoading}>
nice catches!

2023-12-15 08:38 UTC, slax57 commented
We'll wait for #9481 to be merged before merging this one

2023-12-15 15:02 UTC, slax57 commented
Back to RFR

2023-12-15 15:17 UTC, fzaninotto approved these changes

2023-12-15 15:18 UTC, merged