Feat(usePreference): Throw an error if used outisde right context
marmelab/react-admin pull request #9537
Opened 2023-12-20 19:40 UTC by arimet

Resolve #9526

2023-12-21 09:02 UTC, adguernier requested changes

2023-12-21 09:02 UTC, adguernier commented on packages/ra-ui-materialui/src/preferences/Configurable.stories.tsx
> +export const usePreferenceNotInConfigurable = () => {
```suggestion
export const UsePreferenceOutsideConfigurable = () => {
```

2023-12-21 09:02 UTC, slax57 commented on docs/Configurable.md
> +This hook is only used within a Configurable component.
This line is redundant with the information given above. IMO it's not necessary to add it.

2023-12-21 09:02 UTC, slax57 commented on packages/ra-ui-materialui/src/preferences/Configurable.stories.tsx
> +export const usePreferenceNotInConfigurable = () => {
```suggestion
export const UsePreferenceNotInConfigurable = () => {
```

Not sure it's necessary to create a story for this corner-case though...

2023-12-22 14:16 UTC, djhi approved these changes

2023-12-22 14:38 UTC, merged