Explain how to customize notification message in form validation
marmelab/react-admin pull request #9556
Opened 2024-01-04 10:58 UTC by adguernier

## Problem

The documentation does not explain how to customize the notification message with form server-side validation.

## Solution

Explain how to customize this message in form server-side validation documentation.

2024-01-04 13:07 UTC, fzaninotto approved these changes

2024-01-04 15:09 UTC, slax57 requested changes

2024-01-04 15:09 UTC, slax57 commented on docs/Validation.md
> +        message: 'Error: my custom message in notification popover',
I'm confused. Shouldn't the message be outside the body? :thinking: 
See https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/edit/useEditController.ts#L189 for ref

2024-01-04 15:09 UTC, slax57 commented on docs/Validation.md
> +Note: you can use the `message` key to customize the message displayed in the notification popover but it is not mandatory. By default the notification message is the translatable key `ra.notificatio
I thought this only worked with React 17. Should we really mention this in the docs then?

2024-01-04 15:09 UTC, slax57 commented on packages/ra-ui-materialui/src/form/SimpleForm.stories.tsx
> +export const CustomNotificationMessage = () => (
IMO this story is misplaced. The logic responsible for this feature is actually implemented in `useEditController`, not in `SimpleForm`.

2024-01-15 10:41 UTC, slax57 commented
The solution documented in this PR doesn't work, and what's more it relies on a race condition between the [http_error notification](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/edit/useEditController.ts#L186) and the [invalid_form notification](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/form/useNotifyIsFormInvalid.ts#L29), so it's not robust.

Solving this problem can only be addressed by introducing a new field in the server's response, and supporting the ability to return `message: false` to disable the http_error notification, so this will be done in the upcoming v5.

2024-01-15 10:41 UTC, closed without merging