[Doc] fix jekyll trying to parse jsx code
marmelab/react-admin pull request #9573
Opened 2024-01-10 15:24 UTC by Szulerinio

I didn't run this locally, but my research points to me that this should fix the issue of 
`<Edit mutationOptions={{ onSuccess }} mutationMode="pessimistic">`
being displayed as 
`<Edit mutationOptions= mutationMode="pessimistic">`

![image](https://github.com/marmelab/react-admin/assets/60754055/955f2261-8a55-4209-a757-0f83ef077228)

2024-01-10 15:53 UTC, djhi approved these changes
Thanks!

2024-01-10 15:57 UTC, adguernier approved these changes

2024-01-10 16:04 UTC, adguernier requested changes
Thanks!
But why targeting the “next” branch since this branch is reserved for new features? Can you target the `master` branch? :pray:

2024-01-11 08:20 UTC, Szulerinio commented
I guess i should close this PR and make one based on master branch 
am I correct?

2024-01-11 08:37 UTC, fzaninotto commented
yes, GitHub somehow messed up your rebase.

2024-01-12 14:28 UTC, slax57 approved these changes

2024-01-12 14:29 UTC, merged