Add tests to the ra-data-fakerest generated app
marmelab/react-admin pull request #9578
Opened 2024-01-11 11:10 UTC by djhi

2024-01-11 11:45 UTC, djhi commented on packages/create-react-admin/templates/common/gitignore
> +# Logs
I wondered whether to name this file `.gitignore.template` to make it more explicit

2024-01-11 16:19 UTC, slax57 requested changes
I also have a few more important remarks.

I tested the 'published' version of the CLI (following the instructions in the Readme) and found out that:

1. Running `npm install` to install the build version of the CLI locally fails, because of the following error: `Could not resolve dependency: peer react@"^16.5.2 || ^17.0.0" from ink-select-input@4.2.2` (since we now require react 18) => Do we need to update to a newer version of `ink-select-input`?
2. in the generated app, we have both a `.gitignore` and a `gitignore` file
3. the generated Readme does not explain how to run the tests
4. The test is failing in the generated project, because of a timeout (`Test timed out in 5000ms`) although the app is running properly locally :man_shrugging: 
5. The tests seem to assume we chose an `authProvider`, but it's not mandatory. We should only include the test if an `authProvider` was selected IMO

2024-01-17 09:42 UTC, djhi commented on packages/create-react-admin/templates/ra-data-fakerest/src/App.spec.tsx
> +	await screen.findByText("#11", { selector: "a *" });
Added comments

2024-01-17 14:54 UTC, slax57 requested changes
Code looks good, but:

- There is still a `gitignore` file generated in addition to `.gitignore`
- Tests are still failing when run in the generated project (timeout after 5000 ms)

2024-01-17 16:30 UTC, djhi commented
> Code looks good, but:
> 
> * There is still a `gitignore` file generated in addition to `.gitignore`

FIxed

> * Tests are still failing when run in the generated project (timeout after 5000 ms)

Not sure what happen on your machine. It works fine on mine and on the CI (https://github.com/marmelab/react-admin/pull/9580)

2024-01-23 16:57 UTC, djhi commented on packages/create-react-admin/src/generateAppTestFile.ts
> +});
```suggestion
}, 6000);
```

2024-01-23 16:57 UTC, slax57 commented
> Tests are still failing when run in the generated project (timeout after 5000 ms)

Okay so I pushed the investigation further
- Tests run fine with the parameter `--auth-provider none`
- Tests fail (on my machine) with the parameter `--auth-provider local-auth-provider` (timeout after 5000 ms)
- If I increase the test timeout to 6000 ms then it works

=> Hence I recommend increasing the timeout a bit by default, otherwise we risk having the test fail on the CI too :shrug:

2024-01-23 17:02 UTC, slax57 approved these changes

2024-01-23 17:03 UTC, merged