Update Datagrid documention regarding preferenceKey
marmelab/react-admin pull request #9649
Opened 2024-02-07 10:03 UTC by erwanMarmelab

## Problem
In [React-admin - The Datagrid Component](https://marmelab.com/react-admin/Datagrid.html#configurable) , we don’t mention that you should pass the same preferenceKey to the SelectColumnsButton. That leads to unexpected behaviors when users forget it.

## Solution
Update the documentation and add an example

2024-02-07 16:20 UTC, slax57 requested changes

2024-02-07 16:20 UTC, slax57 commented on docs/Datagrid.md
> +    </List>
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏This code snippet does not show a good example of how you should use `SelectColumnsButton` (it should be used inside the List `actions`). Please create an example based on [this one](https://marmelab.com/react-admin/SelectColumnsButton.html#usage) instead.

2024-02-09 11:00 UTC, adguernier requested changes

2024-02-09 11:00 UTC, adguernier commented on docs/SelectColumnsButton.md
> +        <DatagridConfigurable preferenceKey="postList1">
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**issue:** ‏Strange that the  `preferenceKey` is `postList1` than component is called `<BookList>`. Based on the other example (`<PostList>`), we could set `preferenceKey` to `books.datagrid`

2024-02-12 16:31 UTC, slax57 approved these changes

2024-02-12 16:32 UTC, merged