[RFR] add use of rest parameters in combineDataProviders
marmelab/react-admin pull request #9676
Opened 2024-02-20 05:03 UTC by karpushchenko

This is the solution for https://github.com/marmelab/react-admin/issues/9675
The current implementation doesn't work with dataProvider methods with more than 2 parameters.  According to documentation, the method parameter format is not strictly typed, so it is possible to add as many params as needed and then guess why combineDataProviders doesn't work

2024-02-20 07:11 UTC, fzaninotto commented
Thanks. Could you please add unit tests?

2024-02-20 07:18 UTC, karpushchenko commented
> Thanks. Could you please add unit tests?

Yep, why not, I will update it probably tomorrow

2024-02-21 09:08 UTC, karpushchenko commented
@fzaninotto updated with a corresponding test

2024-02-22 17:49 UTC, fzaninotto requested changes
Great! But this is technically a new feature, so you should PR against `next` rather than `master`.

2024-02-23 01:27 UTC, karpushchenko commented
Ok, I will update it later today, not just a simple retarget of PR

2024-02-28 02:25 UTC, karpushchenko commented
@fzaninotto, done! Sorry for the delay

2024-02-28 06:45 UTC, merged

2024-02-28 06:45 UTC, fzaninotto commented
Thanks!