Introduce ReferenceFieldBase
marmelab/react-admin pull request #9698
Opened 2024-03-04 17:09 UTC by djhi

## Problem

While working on the alternative UI libraries demos, we had to re-implement all the reference fields and inputs logic.

## Solution

Add core headless versions for these components
This PR introduces only the `ReferenceFieldBase`.

## Tasks

- [x] Implementation
- [ ] Tests

2024-03-06 16:23 UTC, erwanMarmelab approved these changes

2024-04-05 08:00 UTC, fzaninotto requested changes

2024-04-05 08:00 UTC, fzaninotto commented on packages/ra-core/src/controller/field/useReferenceFieldController.ts
> +    const record = useRecordContext<RecordType>(options);
throw if reference is empty

2024-04-05 12:47 UTC, djhi commented on packages/ra-ui-materialui/src/field/ReferenceField.tsx
> -        ) : null
Storybook disagrees with you. Having no `id` will disable the query in `useReferenceFieldController` so no `referenceRecord` will be available at L146 in this file thus showing the empty message

2024-04-05 14:10 UTC, djhi commented on packages/ra-ui-materialui/src/field/ReferenceField.tsx
> -        ) : null
There was an error in the `useReferenceFieldController` though. Both the tests and the storybook show that all empty cases are handled

2024-04-05 15:08 UTC, fzaninotto commented on packages/ra-ui-materialui/src/field/ReferenceField.tsx
> -        ) : null
Except in the previous code, the empty text was displayed in a `Typography`. That's no longer the case.

2024-04-08 07:57 UTC, fzaninotto approved these changes

2024-04-08 07:59 UTC, merged