Add better types to data-generator
marmelab/react-admin pull request #9764
Opened 2024-04-10 12:15 UTC by djhi

## Problem

When using the `data-generator-retail` package, the generated is not typed, making consumers declare the generated types themselves.

## Solution

Provide types

2024-04-10 16:24 UTC, fzaninotto reviewed
Would you mind rebasing on `next`? Also, the e-commerce demo redefines those types, it should now import them instead.

https://github.com/marmelab/react-admin/blob/ae7c8ef1f2b0637dc98c7b0a6e15389107779e25/examples/demo/src/types.ts#L5-L73

2024-04-11 07:39 UTC, fzaninotto approved these changes
LGTM. But I'm thinking: since we're targeting v5, maybe we can get rid of the serialized/unserialized date switch? I think it makes more sense to have it always serialized.

2024-04-11 07:41 UTC, djhi commented
> LGTM. But I'm thinking: since we're targeting v5, maybe we can get rid of the serialized/unserialized date switch? I think it makes more sense to have it always serialized.

Sounds good to me.

2024-04-11 08:24 UTC, djhi commented
> LGTM. But I'm thinking: since we're targeting v5, maybe we can get rid of the serialized/unserialized date switch? I think it makes more sense to have it always serialized.

Actually I don't think we should. Many libraries

2024-04-12 11:49 UTC, fzaninotto requested changes

2024-04-12 11:49 UTC, fzaninotto commented on examples/demo/package.json
> +        "dev": "vite --force",
why this change?

2024-04-12 11:49 UTC, fzaninotto commented on examples/demo/package.json
you're missing a bump on the   "json-graphql-server" version, and also an update to the yarn.lock file.

2024-04-12 11:58 UTC, djhi commented on examples/demo/package.json
There are actually some issues with `json-graphql-server`. Still investigating

2024-04-18 16:09 UTC, djhi commented on examples/demo/package.json
> +        "dev": "vite --force",
Reverted

2024-04-18 16:41 UTC, fzaninotto approved these changes

2024-04-18 16:48 UTC, merged