[Next] Backport changes from master
marmelab/react-admin pull request #9765
Opened 2024-04-10 13:27 UTC by slax57

Backporting changes from 4.16.12 to 4.16.15 to the `next` branch.

2024-04-10 16:34 UTC, fzaninotto requested changes

2024-04-10 16:34 UTC, fzaninotto commented on docs/useGetList.md
> +    const { data, isLoading, error } = useGetList(
```suggestion
    const { data, isPending, error } = useGetList(
```

2024-04-10 16:34 UTC, fzaninotto commented on docs/useGetList.md
> +        isLoading,
```suggestion
        isPending,
```

2024-04-10 16:34 UTC, fzaninotto commented on docs/useGetList.md
> +    const { data, isLoading, error } = useGetList(
```suggestion
    const { data, isPending, error } = useGetList(
```

2024-04-10 16:34 UTC, fzaninotto commented on docs/useGetList.md
> +    if (isLoading) { return <Loading />; }
```suggestion
    if (isPending) { return <Loading />; }
```

2024-04-11 12:35 UTC, slax57 commented on docs/useGetList.md
> +    const { data, isLoading, error } = useGetList(
Nice catch! Thanks!

2024-04-11 12:46 UTC, fzaninotto approved these changes

2024-04-11 12:46 UTC, merged