Page title next
marmelab/react-admin pull request #9770
Opened 2024-04-11 05:19 UTC by hiaselhans

follow-up from #9768 to change branch

This PR adds two more choices to the 'title' prop of edit / show views:

- false to display no title
- callback with signature (arg0?: RaRecord) => string

I found this to be the most flexible and efficient way to inject a title

2024-04-15 09:26 UTC, slax57 requested changes
Thank you for your contribution :blush: 

Two more things I'd like to add to the following comments:
- I saw the following warning in the console while testing: `Warning: Failed prop type: Invalid prop `title` supplied to `Show`, expected a ReactNode.`. You may have forgotten to update a propTypes declaration somewhere.
- I'd like to have the approval of @fzaninotto or @djhi on the feature before merging. Guys wdyt?

2024-04-15 09:26 UTC, slax57 commented on packages/ra-ui-materialui/src/detail/Show.spec.tsx
> +
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Why not add tests for Edit too?

2024-04-15 09:26 UTC, slax57 commented on packages/ra-ui-materialui/src/detail/ShowView.tsx
> +>;
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Why did you need that change?

2024-04-15 09:26 UTC, slax57 commented on packages/ra-ui-materialui/src/types.ts
> +        | ((arg0: RecordType | undefined) => string);
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏

```suggestion
        | ((record: RecordType | undefined) => string);
```

2024-04-15 09:26 UTC, slax57 commented on packages/ra-ui-materialui/src/types.ts
> +        | ((arg0: RecordType | undefined) => string);
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏

```suggestion
        | ((record: RecordType | undefined) => string);
```

2024-04-15 09:48 UTC, slax57 commented
Got the approval! :tada: 

Also, realizing this will also fix https://github.com/marmelab/react-admin/issues/9695

2024-05-02 14:49 UTC, fzaninotto commented
Any updates on this one?

2024-05-13 11:35 UTC, fzaninotto commented
Bump, you need to rebase and take the review into account.

2024-07-01 21:32 UTC, fzaninotto commented
No news for some time, closing.

2024-07-01 21:32 UTC, closed without merging