`<DatagridBody>` creates the `<RecordContext>` instead of `<DatagridRow>`
marmelab/react-admin pull request #9808
Opened 2024-04-30 15:49 UTC by adguernier

This PR attempts to delegate the creation of a  `<RecordContext>` to `<DatagridBody>` instead of `<DatagridRow>`

2024-05-02 14:47 UTC, fzaninotto requested changes
You also need to remove the reconrdContextProvider from the DatagridRow

2024-05-02 15:48 UTC, adguernier commented
> You also need to remove the reconrdContextProvider from the DatagridRow

Done, I pushed in a hurry

2024-05-02 15:52 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
> +                            key: record.id ?? `row${rowIndex}`,
we no longer need the `key` here

2024-05-02 15:53 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
> +                <RecordContextProvider value={record} key={record.id}>
Use the same `key` value as previously, i.e. `record.id ?? row${rowIndex}`

2024-05-02 15:55 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/datagrid/DatagridBody.tsx
> -                        record,
This is a breaking change: a custom DatagridRow will no longer receive the record. You must document it in the upgrade guide.

2024-05-07 07:46 UTC, fzaninotto requested changes

2024-05-07 07:46 UTC, fzaninotto commented on docs/Upgrade.md
> +The `<DatagridBody>` component no longer provides a `record` prop to its `<DatagridRow>` children. Instead, it provides a `recordContext` for each row. See the [`<Datagrid body/>`](./Datagrid.md#body
Pleae add a diff to show how the code must be changed (before: record injection, after: useRecordContext)

2024-05-07 07:46 UTC, fzaninotto commented on docs/Upgrade.md
> +## `<DatagridBody>` No Longer Provides `record` Prop To `<DatagridRow>`
Move that to the "List Components" section and make it a 3rd level

2024-05-10 13:28 UTC, erwanMarmelab approved these changes

2024-05-13 07:42 UTC, fzaninotto requested changes

2024-05-13 07:42 UTC, fzaninotto commented on docs/Upgrade.md
> ++               </RecordContextProvider>
wrong diff: you should show how a custom DatagridRow no longer reads the record from its props, but from the Recordcontext.

2024-05-13 07:42 UTC, fzaninotto commented on docs/Upgrade.md
> +Also, `<DatagridRow>` no longer provides a `<RecordContextProvider>` to its children:
that's wrong

2024-05-13 15:34 UTC, erwanMarmelab approved these changes

2024-05-13 15:47 UTC, djhi commented on docs/Upgrade.md
> +The `<DatagridBody>` component no longer provides a `record` prop to its `<DatagridRow>` children. Instead, it provides a `recordContext` for each row:
```suggestion
The `<DatagridBody>` component no longer provides a `record` prop to its `<DatagridRow>` children. Instead, it provides a `RecordContext` for each row: 
```

2024-05-13 15:58 UTC, djhi approved these changes

2024-05-13 15:58 UTC, merged