Use record representation in `<SelectArrayInput>`
marmelab/react-admin pull request #9902
Opened 2024-06-05 14:34 UTC by djhi

This input didn't leverage `recordRepresentation` for the choices texts.

2024-06-05 14:50 UTC, fzaninotto approved these changes

2024-06-05 14:54 UTC, fzaninotto requested changes
Could you also update the `<SelectArrayInput>` doc? We currently have the following in `<SelectInput>`:

![image](https://github.com/marmelab/react-admin/assets/99944/3ae1cd00-a413-43a8-bf95-0c8ccaa2893d)

2024-06-05 14:54 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
> +export const InsideReferenceInput = () => (
```suggestion
export const InsideReferenceArrayInput = () => (
```

2024-06-05 14:54 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
> +export const InsideReferenceInputDefaultValue = ({
```suggestion
export const InsideReferenceArrayInputDefaultValue = ({
```

2024-06-05 14:54 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.stories.tsx
> +export const InsideReferenceInputWithError = () => (
```suggestion
export const InsideReferenceArrayInputWithError = () => (
```

2024-06-05 14:54 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
> +    InsideReferenceInputDefaultValue,
```suggestion
    InsideReferenceArrayInput,
    InsideReferenceArrayInputDefaultValue,
```

2024-06-05 14:54 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
> +            render(<InsideReferenceInput />);
```suggestion
            render(<InsideReferenceArrayInput />);
```

2024-06-05 14:54 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
> +            render(<InsideReferenceInputDefaultValue onSuccess={onSuccess} />);
```suggestion
            render(<InsideReferenceArrayInputDefaultValue onSuccess={onSuccess} />);
```

2024-06-05 15:23 UTC, djhi commented
> Could you also update the `<SelectArrayInput>` doc? We currently have the following in `<SelectInput>`:
> 
> ![image](https://private-user-images.githubusercontent.com/99944/336892720-3ae1cd00-a413-43a8-bf95-0c8ccaa2893d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDExMjksIm5iZiI6MTcxNzYwMDgyOSwicGF0aCI6Ii85OTk0NC8zMzY4OTI3MjAtM2FlMWNkMDAtYTQxMy00M2E4LWJmOTUtMGM4Y2NhYTI4OTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE1MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkY2E5ODg2M2JmNTAxYzE4ZTM1OTg1MmRhZWI1ZmMyOWUwZmViMTM2NWIzNzRmZDRkZGI3OGRkOWE1OTA2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F1cokFyCqyFb2sQzSz_EFENjndrSr3pVaBjoIYOoksA)

Actually, the documentation already mentioned the `recordRepresentation` even though it wasn't implemented ^^

2024-06-05 15:49 UTC, fzaninotto commented on packages/ra-ui-materialui/src/input/SelectArrayInput.spec.tsx
> +    describe('inside ReferenceInput', () => {
```suggestion
    describe('inside ReferenceArrayInput', () => {
```

2024-06-05 15:51 UTC, fzaninotto approved these changes

2024-06-06 09:35 UTC, adguernier approved these changes

2024-06-06 09:36 UTC, merged