Fix DatagridHeader Tooltip when using React element as a field label
marmelab/react-admin pull request #9948
Opened 2024-06-24 10:31 UTC by djhi

## Problem

When using a React element as `label` for a field, the datagrid header tooltip displays `Sort by [object Oject] descending`.

## Solution

Fallback to the default inferred label

![image](https://github.com/marmelab/react-admin/assets/1122076/2aad8d69-0014-4fa5-b4a1-0be35c76d1e5)

2024-06-24 13:21 UTC, fzaninotto requested changes

2024-06-24 13:21 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/datagrid/DatagridHeaderCell.tsx
> +                      : field.props.label,
I'd invert the logic by only using the label if it's a string

2024-06-24 13:21 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/List.stories.tsx
> +export const LabelElements = () => (
his should be a Datagrid story

2024-06-24 15:13 UTC, adguernier approved these changes

2024-06-24 16:00 UTC, fzaninotto requested changes

2024-06-24 16:00 UTC, fzaninotto commented on packages/ra-ui-materialui/src/list/datagrid/Datagrid.stories.tsx
> +import { Admin } from 'react-admin';
Can't you use AdminUI and AdminContext from the current package instead?

2024-06-25 08:46 UTC, fzaninotto approved these changes

2024-06-25 08:46 UTC, merged