[WIP] Forward query options to getMany
marmelab/react-admin pull request #9954
Opened 2024-06-25 14:59 UTC by bendenoz

fix for #9953

2024-06-25 15:45 UTC, slax57 approved these changes

2024-06-25 15:49 UTC, slax57 requested changes
Thanks for the PR :slightly_smiling_face: 

Unfortunately this seems to throw a TS error at build time. Can you check?

2024-06-26 10:23 UTC, bendenoz commented
I rebased on 4.x, is it better?

2024-06-27 08:23 UTC, slax57 commented
Thanks for the rebase.
Unfortunately the issue remains.
This is due to the `queryOptions` being typed as options for the `getList` query, which is not compatible with the `getManyAggregate` query.

It seems I do not have push permissions on your branch, so I published the required change here: https://github.com/marmelab/react-admin/commit/d7ed98ecb729456a178b12c2b0ff180cb1152ee2
This commit makes it so that the `queryOptions` are typed for `getList` query **or** `getManyAggregate` query.

Can you apply it to your branch?

Thanks.

2024-06-27 11:06 UTC, bendenoz commented
cherry-picked and pushed

2024-06-27 12:06 UTC, slax57 commented
Thanks! :slightly_smiling_face: 

I'm sorry I didn't realize this before, but it would be nice to also update the [documentation](https://github.com/marmelab/react-admin/blob/4.x/docs/ReferenceArrayInput.md#queryoptions) to specify that the `queryOptions` are passed to both `getList` and `getMany` now.

Can you update it? :pray:

2024-06-27 13:14 UTC, bendenoz commented
ok :) see latest commit, hopefully it' only in one place?

2024-06-27 14:27 UTC, slax57 reviewed
Thanks! I think we're good :slightly_smiling_face: (apart from this last suggestion)

2024-06-27 14:27 UTC, slax57 commented on docs/ReferenceArrayInput.md
> +Use the `queryOptions` prop to pass options to the `dataProvider.getList()` query that fetches the possible choices, as well as the `dataProvider.getManyAggregate()` query that retrieves the currentl
```suggestion
Use the `queryOptions` prop to pass options to the `dataProvider.getList()` query that fetches the possible choices, as well as the `dataProvider.getMany()` query that retrieves the currently selected choices.
```

2024-06-27 14:58 UTC, slax57 approved these changes
Thanks!

2024-06-27 15:08 UTC, merged

2024-07-17 16:47 UTC, lumpov commented
please release this fix in v4

2024-07-22 14:24 UTC, fzaninotto commented
@lumpov Sorry, this is a new feature and v4 is feature freeze. You'll have to upgrade to v5 if you need this feature.