fix(ra-data-graphql): fix an issue with custom context being overwrit…
marmelab/react-admin pull request #9976
Opened 2024-07-05 09:51 UTC by jspizziri

…ten on queries

fix #9973

2024-07-05 12:58 UTC, djhi approved these changes
Thanks!

2024-07-05 14:03 UTC, djhi requested changes

2024-07-05 14:03 UTC, djhi commented on packages/ra-data-graphql/src/index.ts
> +                apolloQuery.context,
```suggestion
                apolloQuery.context
```

2024-07-05 19:25 UTC, jspizziri commented
@djhi , updated per your feedback.

2024-07-09 14:38 UTC, jspizziri commented
@djhi , friendly ping.

2024-07-10 07:13 UTC, merged