Fix Remix Documentation
marmelab/react-admin pull request #9982
Opened 2024-07-09 08:50 UTC by djhi

Fix #9974

2024-07-09 13:56 UTC, adguernier approved these changes

2024-07-09 13:57 UTC, adguernier commented on docs/Remix.md
> ++		noExternal: ['ra-data-json-server']
```suggestion
+		noExternal: ['ra-data-json-server'] // the dataProvider you are using
```

2024-07-09 14:51 UTC, fzaninotto requested changes

2024-07-10 11:14 UTC, fzaninotto approved these changes

2024-07-10 11:14 UTC, merged